### ISSUE TITLE
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by DJAWatt** [joomla/jissues#1000]
Hi,

We are not able to receive emails from our Joomla website anymore.  Our website (and Joomla) are hosted on a Microsoft Azure VM.

We have configured SMTP details to one of our google gmail accounts (with "less secure apps" active).  The problem only happens with our google account.

We contacted google who say that you need to update the CA certificate.

Please help

#### Steps to reproduce the issue
1. Got to Joomal Global Configuration option
2. Try to send a test email using SMTP settings below:

Host: smtp.gmail.com
Port: 587
Security: STARTTLS

#### Expected result
1. I expected to receive the test email 

#### Actual result
2. Error - Unable to contact SMTP host

#### System information (as much as possible)
please see attached config files for System and PHP that I downloaded as JSON files from Joomla

[JoomlaConfig.zip](https://github.com/joomla/jissues/files/1611136/JoomlaConfig.zip)

#### Additional comments
1. I set debug to log 'everything'
2. I googled the problem in Joomla forum and changed the mail.php setting to temporarily stop checking certificates - see below

Editing file: libraries\joomla\mail\mail.php
Function: useSmtp
Line number approx.: #630
Change the lines:
if ($secure == 'ssl' || $secure == 'tls')
{
$this->SMTPSecure = $secure;
}

To:
if ($secure == 'ssl' || $secure == 'tls')
{
$this->SMTPSecure = $secure;
$this->SMTPOptions = array(
'ssl' => array(
'verify_peer' => false,
'verify_peer_name' => false,
'allow_self_signed' => true
)
);
}
3. The above change worked but I need a proper solution.

4. Attached zip files show logs before and after the above change.

[Everything.zip](https://github.com/joomla/jissues/files/1611116/Everything.zip)

[JoomlaConfig.zip](https://github.com/joomla/jissues/files/1611139/JoomlaConfig.zip)

**Comment by infograf768** [comment]
You are posting on the wrong github repo.
Please redo on https://issues.joomla.org/
