### ISSUE TITLE
Block the bot from removing a pr from a milestone or better why this is happening?

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#1001]
#### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/2596554/34906191-3b123fce-f868-11e7-88af-135cb18193cd.png)

https://github.com/joomla/joomla-cms/pull/14642

This is one example out of many.

#### Expected result

milestone is keept

#### Actual result

milestone is removed for some unknown reason

**Comment by franz-wohlkoenig** [comment]
Similar to #994
