### ISSUE TITLE
Article create date display format error

### ISSUE THREAD

**Issue by westiefan** [joomla/jissues#1003]
#### Steps to reproduce the issue

View any article in the "news & info" section of the "http://www.ruthbridge.com/clients" website (only articles in the news & info section are set to display create date by default).

Note: If accessing the site from the main URL please note that the site has 2 sections that are accessible via image links on the landing page.  To access the pages with the errors from the landing page, choose the image with the link to "click to view our corporate pages" option.

You can access any article in this category by clicking the "News & Info" menu item, and then selecting any of the listed articles (please note that the date format on the news & ifo category page displays correctly, it is only the display in the individual articles themselves that show the format error).

Alternatively you can click the "read more" link in the latest news module, which will take you to 1 article, and from there you can access the other articles using the "prev" / "next" links.

#### Expected result

PHP date format "l jS F Y" (e.g. Friday 12th September 2013) to be displayed on the news & info articles 

#### Actual result

Odd time and date display, e.g. in the format "UTC+00:000_201337th_12thFri_C+0000RE_FriPMUTCE_September+0000RSepPMUTC_0C2".  I have tried using language overrides to format the display, but the overrides have no effect on the formatting

#### System information (as much as possible)
Database Version		5.5.5-10.1.27-MariaDB
PHP Version			7.0.25
Web Server			Apache/2.4.29 (Unix)
Joomla! Version		Joomla! 3.8.3 Stable [ Amani ] 12-December-2017 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

#### Additional comments

I understand from the client that this issue only appeared after the recent update to the Joomla CMS (version 3.8.3 released in December 2017, but was only noticed earlier today when accessing the site to carry out an update to the content.

An example of the error is shown in the highlighted area in the screenshot attached:
![image](https://user-images.githubusercontent.com/8655875/35100780-f2589472-fc54-11e7-91be-63a366d804eb.png)

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns "Issue tracking application extending GitHub's issues and pull requests for the Joomla! project". For this Reason please close this Issue, thanks.

**Comment by westiefan** [comment]
I am reporting a bug that appears to have been introduced since the last update.

 

No amount of changing the settings in Joomla will fix this issue.  The issue was not there before the update to joomla 3.8.3, so how will the forum help me to get a bug fixed?

 

John
