### ISSUE TITLE
Captcha - ReCaptcha is not showing text or image on my web site in joomla.

### ISSUE THREAD

**Issue by sks1990** [joomla/jissues#1016]
I have used the Captcha - ReCaptcha plugin in Joomla. After some time captcha is not showing text or image on website. 
Joomla version: 3.4.6 
url :- https://www.paneast2west.com/solutions-and-services/electronic-components
https://www.paneast2west.com/contact-us

Thanks..

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns i"Issue tracking application extending GitHub's issues and pull requests for the Joomla! project". For this Reason please close this Issue, thanks.

Also please update your Site to latest Version 3.8.5.
