### ISSUE TITLE
Absent User tests don't show anymore in PRs

### ISSUE THREAD

**Issue by infograf768** [joomla/jissues#1021]
As title says.
<img width="768" alt="screen shot 2018-05-09 at 11 06 19" src="https://user-images.githubusercontent.com/869724/39806477-565e9062-537a-11e8-9477-a6a7084aa81f.png">

@zero-24 tells me something will only show after first test.

**Comment by mbabker** [comment]
Right.  The check only gets added when the tests module is hit, nothing was ever written to arbitrarily add the check to all PRs.
