### ISSUE TITLE
Automate Deployments

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#1027]
The new Jenkins CI system for `joomla.org` should be utilized to automate code deployments for this repository.  To that, the following steps are required:

- [ ] Remove compiled assets from this repository
    - Laravel Mix manifest
    - CSS/JS
- [ ] Adjust the live server to support a minimal downtime deployment workflow
    - New `deployments` directory
- [ ] Create a job on the Jenkins system to deploy changes for the application
    - Package is extracted to `deployments` provisioning space
    - Add some kind of "maintenance mode" (`./artisan down` and `./artisan up` thing) to deploy database schema changes as required
    - Ensure persistent assets remain available (i.e. uploads)
    - Change `public_html` to point to new deployment

**Comment by wilsonge** [comment]
Is there anything left to do here?

**Comment by mbabker** [comment]
Since I've decided to just be OK with using git on the live servers, what's in place now is good enough.
