### ISSUE TITLE
"New Issue": More specific on "System Information"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/jissues#1033]
Submitting a new Issue a User get this:

#### System information (as much as possible)

Sometimes User ignore it, sometimes they paste all Parts of "System > System Information" which is Way to much.

Maybe its not clear what "as much as possbile" means. It would be more clear if User get Information "(Your Backend: System > System Information: Part "PHP Built On" to "User Agent").

**Comment by mbabker** [comment]
The issue templates are part of the repos, not something coded in here.  So the relevant files in https://github.com/joomla/joomla-cms/tree/staging/.github should be updated if you think this is going to help.

**Comment by franz-wohlkoenig** [comment]
@mbabker whom can i write this Suggestion?

**Comment by mbabker** [comment]
Whatever repo it is you want to see the issue templates changed at.  The tracker interface pulls the issue templates from the repo.

**Comment by franz-wohlkoenig** [comment]
done https://github.com/joomla/joomla-cms/issues/21793
