### ISSUE TITLE
New Feature Workflow label removed by bot

### ISSUE THREAD

**Issue by wojsmol** [joomla/jissues#1034]
#### Steps to reproduce the issue
Please see https://github.com/joomla/joomla-cms/pull/21858

#### Expected result
New Feature Workflow label should persist after adding RTC

#### Actual result
New Feature Workflowis removed by @joomla-cms-bot when RTC is added 

#### System information (as much as possible)

**Comment by mbabker** [comment]
Duplicate of #947
