### ISSUE TITLE
incompatible with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/jissues#1038]
```Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'joomlaissues.u.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by```

Mysql 5.7.23 - default out of the box config

Url:
http://0.0.0.0/activity/user/jtracker/query?period=1&activity_type=0

**Comment by mbabker** [comment]
Covered by #976 (yeah this has details, but at least the items can be cross-linked and referenced).
