### ISSUE TITLE
since 3.8.11 error ($start !== null) caused by the changes made in file: libraries/src/Router/SiteRouter.php

### ISSUE THREAD

**Issue by toerrijders** [joomla/jissues#1042]
since 3.8.11 I get a error caused by the changes made in file: libraries/src/Router/SiteRouter.php - probably  line 602 if ($start !== null)
On my forum, when a topic consists of many reactions, they are divided into several pages;
[1] [2] [3] when you want to change from 3 to 1, the first message is not displayed.
By using the old file of version 3.8.10 problem is solved
I am using template beez3, forum kunena.
I hope you can undo the changes made in 3.8.11. version 3.8.10 worked perfectly.

**Comment by elkuku** [comment]
Please report issue at https://github.com/joomla/joomla-cms as this Repository is about Issue tracking application.
