### ISSUE TITLE
Joomla\Filesystem\File::delete method chmod issue

### ISSUE THREAD

**Issue by sven420** [joomla/jissues#1049]
When Path::canChmod($file) returns false method throws an exception as if deletion is not possible but some servers have such setup that chmod is not but file deletion is possible.

Because of this I got errors when trying to update extensions but after commenting out this and line below that is trying to chmod file to 0777 update was success.

In my opinion unlink($file) should be executed even if chmod is not possible and this is a bug that can cause issues for some users.

**Comment by zero-24** [comment]
Hi @sven420 

it seams you are talking about an issue with the Joomla! CMS so please open an issue here: https://github.com/joomla/joomla-cms/issues/new?template=Bug_report.md this repo here is for the issue tracker application we build.

**Comment by sven420** [comment]
Ok, didn't know that, I've opened it there, you can delete this one.

**Comment by zero-24** [comment]
@mbabker can you please hit the close button here?
