### ISSUE TITLE
Add a UI indicator for a draft PR

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#1052]
https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by zero-24** [comment]
I would suggest to wait for the draft info beeing moved to stable given the warning added here: https://developer.github.com/v3/pulls/

**Comment by mbabker** [comment]
Nothing in `joomla/github` supports preview APIs anyway (and from what I remember it's next to impossible to shove anything in to customize requests without just not using the package), so any changes have to wait for stable API implementations.

**Comment by wilsonge** [comment]
This seems to be in the hooks now. On a PR incoming event there's a draft boolean. And there's a `ready_for_review` event when it moves from draft to ready for review https://developer.github.com/v3/activity/events/types/#pullrequestevent

**Comment by wilsonge** [comment]
https://github.com/joomla/jissues/pull/1079 Stores stuffy to databases

**Comment by wilsonge** [comment]
Completed with https://github.com/joomla/jissues/pull/1080
