### ISSUE TITLE
Update Alpha 8 to 10 error - A string or Joomla\Uri\UriInterface object must be provided, a "NULL" was provided.

### ISSUE THREAD

**Issue by Chacapamac** [joomla/jissues#1059]
#### Steps to reproduce the issue
Update local Mamp Alpha 8 to 10

#### Additional comments
I get this error on updating from Alpha8 to Alpha 10. 

> a string or joomla\uri\uriinterface object must be provided, a "null" was provided

Not sure if anything is installed but it stay at Alpha 8

**Comment by zero-24** [comment]
Hi this seams to be an issue with Joomla and not with issues.joomla.org please report that issue here: https://github.com/joomla/joomla-cms
