### ISSUE TITLE
I lost my login for JOOMLA builder fo site www.childrenmakingtomorrown.com. Could you please send me user and password for this builder. Thank you

### ISSUE THREAD

**Issue by Ibrom47** [joomla/jissues#1064]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.

**Comment by zero-24** [comment]
Good morning @Ibrom47 

Joomla! does not have access to any of your passwords. Joomla! is only the underlying software used to run your website.  If you have forgotten your password then directions for [manually resetting your password via database access can be found here. ](https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F)

The Joomla project provides an active forum where you can search for answers and post your own question at https://forum.joomla.org/. Alternatively, you can find Joomla! consulting services available from a wide variety of groups via our [Resources](https://resources.joomla.org/en/) section. 

Please note: Joomla! and Open Source Matters, are not able to recommend a specific person, or company for assistance.
