### ISSUE TITLE
Rewrite CLI to use joomla/console

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#1081]
The CLI infrastructure here is probably the most advanced CLI integration written on `joomla/application` and served as a model for all of the CLI integrations used in the .org Framework apps before I decided to build something based on `symfony/console`.  The way it's built though has it as an almost totally segregated application and not something that's just "native" in the application stack, plus it required inlining all of the `Joomla\Application\Cli` namespace in order to upgrade everything to use Framework 2.0 packages.

The CLI integration here should be rewritten to use `joomla/console` as its foundation.

**Comment by wilsonge** [comment]
Completed
