### ISSUE TITLE
Using <? in pull request title breaks issue title on issues.j.o

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/jissues#1092]
#### Steps to reproduce the issue

Created https://github.com/joomla/joomla-cms/pull/30089 which has a title of:

`[4.0] Change all <?= to <?php echo`

Viewed issues.joomla.org and https://issues.joomla.org/tracker/joomla-cms/30089 pages

#### Expected result

Complete title to be displayed

#### Actual result

List View
<img width="707" alt="Screenshot 2020-07-13 at 15 04 15" src="https://user-images.githubusercontent.com/400092/87313732-3c513d00-c51a-11ea-83aa-7d719e7369dd.png">

Issue View
<img width="940" alt="Screenshot 2020-07-13 at 15 06 19" src="https://user-images.githubusercontent.com/400092/87313882-6efb3580-c51a-11ea-9b49-91a1f06818ed.png">

**Comment by mbabker** [comment]
A part of me says to close as intended behavior because our filtering (basically the `Joomla\Filter` API) is probably more strict than GitHub's filtering and short of going to unfiltered inputs I don't know if this one is being addressed safely.

**Comment by richard67** [comment]
Hmm, having a PR with title "Change all" is indeed a bit scary 😉
