### ISSUE TITLE
Nightly Builds stopped after 5 August

### ISSUE THREAD

**Issue by toivo** [joomla/jissues#1096]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.

#### Steps to reproduce the issue

https://developer.joomla.org/nightly-builds.html
Select any version from 3.9, 3.10 or 4.0

#### Expected result
Today's Nightly Build is available

#### Actual result
Only 5 August is available

#### System information (as much as possible)
n/a

**Comment by wilsonge** [comment]
@HLeithner dunno if you fixed this in the meantime but things look fine to me 
<img width="899" alt="Screenshot 2020-08-13 at 13 59 36" src="https://user-images.githubusercontent.com/1986000/90137210-39da4100-dd6d-11ea-949f-e441428a5361.png">

**Comment by HLeithner** [comment]
Yes I fixed it today. Thanks for the report
