### ISSUE TITLE
Too Many URL Code inside Joomla Coding

### ISSUE THREAD

**Issue by mdsha77** [joomla/jissues#1097]
#### Steps to reproduce the issue
Why too many URL and advertisement code inside my joomla coding? Is this a bug?

<div style="position: absolute; filter: alpha(opacity=0);   opacity: 0.001; z-index: 10;"><a href="http://www.pekarekcrandell.com">low   bred 11s</a> <a href="http://www.elaineperlov.com">low   georgetown 11s</a> <a   href="http://www.jrs-inc.net">jordan   11 low georgetown</a> <a   href="http://bambooone.com/">low   bred 11s</a> <a href="http://www.advancedcybernetics.com">jordan   13 low hornets</a> <a   href="http://servingkidshope.org/sponsors">low   georgetown 11s</a> <a   href="http://www.rclnyc.com/">coach   outlet</a> <a href="http://www.salon56.com">jordan   11 low georgetown</a> <a   href="http://www.sbtlaw.com">jordan   11 low georgetown</a> <a   href="http://www.patrickentcorp.com">low   bred 11s</a> <a href="http://www.dittrichassociates.com">adidas   yeezy 750 boost</a> <a   href="http://www.southwestveteranschamber.com/advertising">jordan   13 low hornets</a> <a   href="http://www.schirberandwagner.com">low   bred 11s</a> <a href="http://www.peiowa.org/news/news-events">low   georgetown 11s</a> <a   href="http://www.glangels.org/">michael   kors outlet</a> <a href="http://www.schirberandwagner.com">jordan   11 low bred</a> <a href="http://www.muskogeehousing.org">adidas   yeezy 750 boost</a> <a   href="http://www.harrisonorr.com">jordan   5 metallic silver</a> <a   href="http://www.southwestveteranschamber.com/advertising/">low   hornets 13s</a> <a href="http://www.showersofblessings.org">adidas   yeezy 750 boost</a></div>
--

#### Expected result

What supposed i need to do? And how to delete it if a lot page have this URL?

#### Additional comments

I am new in joomla. Thanks for help

**Comment by HLeithner** [comment]
Pam
