### ISSUE TITLE
PR 31357 was stored as issue 

### ISSUE THREAD

**Issue by chmst** [joomla/jissues#1107]
#### Steps to reproduce the issue
Users tried to submit a test result for a PR. https://issues.joomla.org/tracker/joomla-cms/31357.

#### Expected result
A Test-this button is visible in the issue tracker.

#### Actual result
The issue is still an "issue" and therefor has not a "Test this" button. 

#### System information (as much as possible)
Seems that issue 31357 in the issue tracker and githb issue 31357 are not related.

**Comment by wilsonge** [comment]
Just went to look at this now I got home. The issue and github now seem to be in sync after @HLeithner merged the PR. Do things look correct for you too now @chmst ?

**Comment by chmst** [comment]
Thanks, it is ok now - everything correct and closed. I'll close this issue.
