### ISSUE TITLE
JavaScript error when you want to edit an group

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#1112]
#### Steps to reproduce the issue

https://issues.joomla.org/project/joomla-cms/group/11

#### Expected result

you can edit the group and its members

#### Actual result

you can not as there is a JS error

#### System information (as much as possible)

live site

#### Additional comments

![image](https://user-images.githubusercontent.com/2596554/105644430-d87ada00-5e95-11eb-99e5-1fc07a38a8cc.png)

![image2](https://user-images.githubusercontent.com/2596554/105644433-d9ac0700-5e95-11eb-807f-421e47ead2bd.png)

**Comment by wilsonge** [comment]
PR https://github.com/joomla/jissues/pull/1119
