### ISSUE TITLE
GitHub new feature injects into issue text 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/jissues#1122]
Today Github were all over twitter promoting the fact that every code block in Github now has a new widget to allow one click copy to clipboard.

https://twitter.com/natfriedman/status/1391862005095485440

They badly implemented it. It started showing up in Emails, the iPhone app and other places.

https://twitter.com/koenpunt/status/1391888239481458690
https://twitter.com/meijer_s/status/1391863870504030218
https://twitter.com/myPhilTaylor/status/1392127202347700225

Not sure if this needs fixing, or just sitting it out to wait for Github to fix their stuff?

One place its showing up, is in the Joomla issue tracker.

Example:

<img width="901" alt="Screenshot 2021-05-11 at 21 14 38" src="https://user-images.githubusercontent.com/400092/117878882-262d1e00-b29e-11eb-81f9-d15ace140f63.png">

**Comment by wilsonge** [comment]
Looks like they think they've fixed it https://twitter.com/kdaigle/status/1391913003377995778 is this still an issue for newer issues?

**Comment by PhilETaylor** [comment]
Ill keep an eye out
