### ISSUE TITLE
Joomla 4 Crashes After changing Global Configuration Information

### ISSUE THREAD

**Issue by linuxcourseware** [joomla/jissues#1125]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.

#### Steps to reproduce the issue
Install Joomla4  via upgrade from 3.10 PHP 8 or 7.4  (installing on a subdomain)
Go to Global Configuration and make any change. My first experience was when I tried to change the editor to JCE.  After several attempts, I tried to make and save a change (Hide Author Meta Data) to Global Configuration without any extensions (e.g., JCE, Akeeba...) and save the config file.  Once the save button was pressed a login screen appeared and did not allow me to logon.  I tried to change the password via PHPmyadmin,  but that did not work.  

#### Expected result
Save the file without exiting

#### Actual result
Logs out and cannot login.  I can load extensions and work with extensions successfully, but if I touch Global Configuration after the install  I lose the system

#### System information (as much as possible)
Joomla 4 Upgraded from 3.10  tried with both PHP 8 and then  7.4
I have it installed on a subdomain.

#### Additional comments
Could someone tell me how to fix this.  I have been trying to figure this out for two days.

**Comment by b2z** [comment]
If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new
