### ISSUE TITLE
joomla4: image upload error message "This file is too large to upload."

### ISSUE THREAD

**Issue by djayko** [joomla/jissues#1126]
#### Steps to reproduce the issue
- setup plain joomla4 instance at php 8.0 or 7.3 or 7.4 with mysql 5.7
- keep standard setup values for uploads
- set server memory_limit to -1 (=no limit)
- upload an image via Menu -> Content -> Media 

#### Expected result
- image uploaded

#### Actual result
- error message ""This file is too large to upload."

#### System information (as much as possible)
- shared webspace on Ionos with PHP 8.0.9 mysql 5.7.33
- standard memory set up on serverside is memory_limit=-1 (nolimit)
- php settings from joomla4-system information
Upload Max Filesize | 64M
Post Max Filesize | 64 M
Memory Limit | -1

#### Additional comments
- tested on IONOS - Unlimited Plus - Shared Webhosting (everything is working fine on a joomla 3.10 instance on same webspace)
- tested with different image file types and sizes (from 1KB to 8MB)
- after creating a php.ini or .user.ini with "memory_limit="1024M" it worked well - i also tested lower limits like 32MB, 138MB etc.
- reference discussion: https://forum.joomla.org/viewtopic.php?f=811&t=987786&p=3636942#p3636942

**Comment by b2z** [comment]
If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new

**Comment by djayko** [comment]
> 
> 
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new

Ok, I submitted it there, but I don't understand the different sites and where is the right place for issues!??

**Comment by b2z** [comment]
**About**
**Issue tracking application** extending GitHub's issues and pull requests for the Joomla! project.

It is not a CMS.

**Comment by djayko** [comment]
oh sorry, got it.
