### ISSUE TITLE
If we use note type in xml, then second note is not completely full width in joomla 4

### ISSUE THREAD

**Issue by ashik685** [joomla/jissues#1127]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.

#### Steps to reproduce the issue

If we use note type in xml, then second note is not completely full width in joomla 4

type="note"
class="alert alert-success"

#### Expected result

But two needs to be full width

#### Actual result

One shows full width and second shows half width

#### System information (as much as possible)

Joomla 4

**Comment by b2z** [comment]
If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new
