### ISSUE TITLE
Graphs can no longer render due to State not set in JTracker\Model\AbstractTrackerDatabaseModel

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/jissues#1129]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.

#### Steps to reproduce the issue

Go to https://issues.joomla.org/activity/user/joomla-cms/query 

because this errors, the graphs at https://issues.joomla.org/activity/user/joomla-cms no longer load.

#### Expected result

Now error 

#### Actual result

```
0 UnexpectedValueException
State not set in JTracker\Model\AbstractTrackerDatabaseModel
```

#### Additional comments

Maybe related to @wilsonge recent changes as this was working recently.

**Comment by PhilETaylor** [comment]
testing 123<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/1129">issues.joomla.org/tracker/jtracker/1129</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou! Fixed with https://github.com/joomla/jissues/commit/04755673f5a80f16c63caadab3cb331f5dc2202a
