### ISSUE TITLE
Some stuff about the Project here

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/jissues#1131]
https://issues.joomla.org/project/jtracker

"Some stuff about the Project here"

<img width="628" alt="Screenshot 2021-08-28 at 18 43 47" src="https://user-images.githubusercontent.com/400092/131226360-347fc92e-a2e2-4903-8d7f-ffa079656822.png">

**Comment by wilsonge** [comment]
Well this one has apparently been hardcoded into the view since ever... https://github.com/joomla/jissues/blob/master/templates/projects/project.index.twig#L23 😆
