### ISSUE TITLE
issues.joomla.org reveals a dump including passwords

### ISSUE THREAD

**Issue by stAn47** [joomla/jissues#1133]
Submitting a bug into issues.joomla.org reveals a dump of all variables available to PHP - i experienced it during submission of this bug: https://github.com/joomla/joomla-cms/issues/35426

i.e.:

array(7) { [0]=> array(7) { ["file"]=> string(50) "/home/i...../src/App/Tracker/Model/IssueModel.php" ["line"]=> int(445) ["function"]=> string(8) "getState" ["class"]=> string(43) "JTracker\Model\AbstractTrackerDatabaseModel" ["object"]=> object(App\Tracker\Model\IssueModel)#313 (7) { ["context":protected]=> string(17) "com_tracker.issue" ["name":protected]=> string(5) "Issue" ["option":protected]=> string(7) "Tracker" ["table":protected]=> NULL ["project":"JTracker\Model\AbstractTrackerDatabaseModel":private]=> object(App\Projects\TrackerProject)#350 (13) { ["project_id":protected]=> int(1) ["title":protected]=> string(11) "Joomla! CMS" ["alias":protected]=> string(10) "joomla-..." ["gh_user":protected]=> string(6) "j....." ["gh_project":protected]=> string(10) "j.." ["gh_editbot_user":protected]=> string(14) "joomla..." ["gh_editbot_pass":protected]=> string(40) "b

possible test cases: 
use sql escape character in the title
use code character (triple sql character in the message)

best regards, stan

**Comment by PhilETaylor** [comment]
You should never have posted this on the tracker - just like the issue template told you, it should have been emailed direct to Joomla! Security Strike Team <security@joomla.org>

**Comment by stAn47** [comment]
It should not be security related as far as the accesses are properly configured per IP addresses.

**Comment by PhilETaylor** [comment]
SQL Injection - is a security issue. 
Being able to generate dump containing credentials - is a security issue - regardless of if those credentials can be reused or not.

**Comment by stAn47** [comment]
Ok, i apologize for posting it here, i always thought that the security team is for security bugs in joomla source code, not within the websites managed or hosted by joomla teams. 

There indeed should be more checks with joomla websites: 
- if there a dump going to happen it should be filtered by mod_security keywords so that it doesn't show sensitive information to users
- all passwords used on a site should be also protected by IP accesses
- i do not know if this is a SQL Injection as the dump didn't really say that
- reporting security issues with joomla hosted websites should be possibly mentioned separately as it was not clear to me at all

**Comment by PhilETaylor** [comment]
> if there a dump going to happen it should be filtered by mod_security keywords so that it doesn't show sensitive information to users

mod_security is normally employed on incoming requests, not on responses where doing so is an unnecessary overhead most of the time.

> all passwords used on a site should be also protected by IP accesses

You assume way too much. 

> reporting security issues with joomla hosted websites should be possibly mentioned separately as it was not clear to me at all

You were clearly told to read https://developer.joomla.org/security.html - which contains this extract:

> The JSST operates with a limited scope and only directly responds to issues with the core Joomla! CMS and Framework, as well as processing reports regarding the *.joomla.org network of websites. 

- but you chose to delete that when you edited your post:

<img width="657" alt="Screenshot 2021-08-30 at 19 54 38" src="https://user-images.githubusercontent.com/400092/131391372-afad47a2-6bfe-4599-a237-7070cffa62dc.png">

**Comment by PhilETaylor** [comment]
I have alerted the @joomla/security team of this issue.

**Comment by stAn47** [comment]
ok, thank you and my apologies for not evaluating this properly

**Comment by wilsonge** [comment]
This has now been fixed in source. This was my bad leaving some debug code around from some upgrades last Friday.

**Comment by SniperSister** [comment]
The underlying issue has been resolved: a development debug statement was deployed to production and exposed a stack trace, leading to the exposure of the access token.

The debug statement has been removed, the bot access token has been revoked and the credentials have been resetted. The bot's activity on Github has been reviewed and no suspicious activity was found. No user data was exposed.

**Comment by PhilETaylor** [comment]
I would have worded it like: 

"Dear @stAn47, Thank You for reporting this serious security issue, even though you were unaware of its full consequences which could have been very embarrassing to the project. It is now resolved, thankfully due to the quick actions of @PhilETaylor escalating it, and @wilsonge working late into the night on the issue, while actually on holiday miles from home... "

**Comment by SniperSister** [comment]
Thanks @PhilETaylor, couldn't agree more :)

**Comment by stAn47** [comment]
my apologies again for the stress, my little suggestions in this subject are: 
- use mod_security to make sure no dump is possible per IP filter (with a keyword of /home/{username} or similar)
- add an easter egg keyword in the database so that a dump is not possible via web interface (to be filtered by mod_security)
- allow Joomla to accept $_ENV which can be provided by vhost config purely to index.php instead of DB credentials in the file (same as on laravel)
- to access GIT (or other remote services) use a separate process/system with own queue and security context, so you don't access remote systems from web interface directly

kind regards, stan
