### ISSUE TITLE
Help setting up the environment.

### ISSUE THREAD

**Issue by PriyanshSarvehi** [joomla/jissues#1138]
Can anyone please help me set up the environment so I can start making contributions ASAP?

**Comment by N6REJ** [comment]
try https://docs.joomla.org/Setting_up_your_workstation_for_Joomla_development

**Comment by PriyanshSarvehi** [comment]
Thanks for your response @N6REJ. I guess I have all the dependencies fulfilled. Can you tell me how to actually start working on issues?
I've my git repo cloned so basically I have to locate the file to code, reproduce the issue and debug.
So, how do I start doing the above mentioned task?

**Comment by N6REJ** [comment]
there is a doc explaining things, but basically you use a ide, create a local lamp like wamp & then clone the joomla-cms repo and then start coding.
