### ISSUE TITLE
Joomla! version is "‎4.1.0"‎ Error.php file, Cassiopeia is not redirecting to correct address, Error 500

### ISSUE THREAD

**Issue by BEMorskoi** [joomla/jissues#1141]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.

#### Steps to reproduce the issue
Update Joomla 4.0.6 -> 4.1.0 by Admin Console or Install Fresh Install from Joomla Page
Add a line to error.php in your tempate -> if (($this->error->getCode()) == '404') {header('Location: https://angloschool.com.pl/index.php?option=com_content&view=article&id=82');
exit;
Try writing wrong address to old indexed page from Google to your site or just put something like /test to your html website address.
Or try going to non existent article in your website.
#### Expected result
In Joomla 4.0.6 expected result was a website with Error information.
#### Actual result
The server returned a '500 - whoops like something went wrong.
#### System information (as much as possible)
PHP Version 8.1.0
Linux devel2004.vm.netart 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Checked on Windows 11
Chrome Browser
#### Additional comments
The problem occurs right after an update from the admin panel, but also on a clean install, in general I have never had a similar situation before. I have been updating Joomla for a long time and it has been a long time since I got such an error. PHP 8.1 is not important here, because even when I switched to version PHP 8.0 the same problem occurred.

**Comment by wilsonge** [comment]
As noted in the top of your issue this is not a tracker for the Joomla CMS - it's for the Joomla issue tracker. Please report this issue to https://github.com/joomla/joomla-cms/issues/new instead.
