### ISSUE TITLE
Project II: Guided Tour [GSOC 2022]

### ISSUE THREAD

**Issue by ForchaGlen** [joomla/jissues#1147]
Hi everyone congratulations to Joomla on being a selected organization for GSOC 2022.
1-Please How may I start contributing?
2-Please for the link to join the Joomla developer group.

**Comment by pearlpriyanka** [comment]
Fill out this form: https://forms.gle/eiHgWehmWQKE9jBJ7 to join the Joomla developer group in the ring central app!
