### ISSUE TITLE
Domain Joomla Users Action Log Message error

### ISSUE THREAD

**Issue by qgunxfme** [joomla/jissues#1180]
The message reports an incorrect user account for login. It reports the user account of the administrator instead of the user account.

#### Steps to reproduce the issue
Message content:
There was a new sign-in with the account: XXXXXXX (account of administrator)

Device: Windows
Browser: Firefox
IP Address: [xxxx:a46b:8340:1:110c:fb15:xxxx:xxxx](https://ipinfo.io/ip-address)

LET OP: Dit bericht is automatisch gegenereerd door domain (https://domain.com).

#### Expected result
Content should be:
There was a new sign-in with the account: XXXXXXX (account of the user logged in)

**Comment by qgunxfme** [comment]
Joomla version 4.2.7

**Comment by wilsonge** [comment]
This is the tracker for the issue tracker of joomla itself - hence your issue has fallen through the cracks a bit. Please raise this in the main joomla repo here https://github.com/joomla/joomla-cms if it’s still valid. Thanks!
