### ISSUE TITLE
Browser Screens jumbled up and not active Joomla 4.3.4 after install - web domain jumbled and joomla admin jumbled

### ISSUE THREAD

**Issue by berrydr** [joomla/jissues#1189]
#### Steps to reproduce the issue
Fresh install of joomla 4.3.4 on godaddy, 

#### Expected result

Expect to see my a normal looking website and administrator web site for my domain,

#### Actual result

Chrome and Edge screens are jumbled

https://www.tekmetrix.com/stage/

https://www.tekmetrix.com/stage/administrator/index.php

SEE SCREEN SHOT BELOW

#### System information (as much as possible)

4.3.4

#### Additional comments

![Joomla Jumbled](https://github.com/joomla/jissues/assets/119514350/349d07ef-be8c-4247-9aa6-dab5a86fd27d)

**Comment by wilsonge** [comment]
This is the tracker for the issue tracker of joomla itself - hence your issue has fallen through the cracks a bit. You should raise issues about your site on the forum (forum.joomla.org)
