### ISSUE TITLE
Set Search Tool 'Tests' give 'Uncaught TypeError: o.data.items is undefined'

### ISSUE THREAD

**Issue by fgsw** [joomla/jissues#1209]
#### Steps to reproduce the issue
Click any of the 3 'Tests'-Filter.

#### Expected result
Issue tracker show pull request filtered by selected filter.

#### Actual result
![screen shot 2023-12-03 at 02 53 54](https://issues.joomla.org/uploads/2/57d1d893bfc7e2f053610b95bb2be16c.jpg)

#### System information (as much as possible)
Firefox 120, macOS 14.1.2

#### Additional comments
While writing this issue at issue tracker i noticed that the 'Preview'-Tab also show an error: ```Uncaught ReferenceError: e is not defined```

**Comment by wilsonge** [comment]
Thanks for reporting this - i'll try and look into this over the coming week

I think I've fixed the preview issue :) That's just me copy/pasting really badly!

**Comment by fgsw** [comment]
> I think I've fixed the preview issue

You fixed it, thanks.

**Comment by wilsonge** [comment]
Sorry for taking so long with this one. Think I've fixed it with https://github.com/joomla/jissues/commit/7ac78af9dfbfce73acf80ca070f7614ea1336f56

**Comment by fgsw** [comment]
Thanks @wilsonge.
