### ISSUE TITLE
finder

### ISSUE THREAD

**Issue by mirekernst** [joomla/jissues#1263]
I have a site with 43305 articles on my joomla 4 site. Table bpp16_content has 106 MB. But if I use smart search indexing then table bpp16_finder_links_terms has 10 million records and 747 MB and table bpp16_finder_links has 43305 records 740 MB. In total, my database has grown to 2.2 GB which is not enough for many servers. What to do? Why is so much data being indexed? Isn't it some kind of bug?

**Comment by fgsw** [comment]
You can get support at the [forum](https://forum.joomla.org/) as this repository is about the ```Issue tracking application extending GitHub's issues and pull requests for the Joomla! project.```

Please close the issue.
