### ISSUE TITLE
Template Cassiopeia Issue

### ISSUE THREAD

**Issue by gioacchino54** [joomla/jissues#1272]
On some sites I am having this problem.
If I have installed two templates (any one and Cassiopeia), if the default template is the first one and I want to assign the Cassiopeia - Default style to a menu item, the Cassiopeia template is not loaded on the page.
On the other hand, it works.

**Comment by fgsw** [comment]
@gioacchino54 You can get support at the [forum](https://forum.joomla.org/) as this repo ist about ```Issue tracking application extending GitHub's issues and pull requests for the Joomla! project. ```

Please close the issue.
