### ISSUE TITLE
Proposed workflow

### ISSUE THREAD

**Issue by eddieajau** [joomla/jissues#241]
I'm a firm believer in the principle that the issue tracker is just a different way of viewing the data that is already on Github. Ideally, someone could use the tracker and use Github and they more or less both marry up at the end of the day. To that end, I think it's worth describing what the workflow would be like on Github so that we can translate it to the issue tracker.

It is also important to remember that Github separates resolving issues (an issues like we'd have on JoomlaCode) from evaluating patches. In JoomlaCode we'd attach a patch to an issue. In Github we create a pull request and Github has a special interface to evaluating the submitted code in detail, something which is not possible at all with JoomlaCode. This also allows a clear separation of the workflow between a description of a problem and the coded solution for a problem.

Here's my proposed paradigm:

### Use labels to show a blended priority and impact setting:

* P1-Urgent (Software stops working, bad security issues)
* P2-High (Software working but seriously impeded, less-bad security issues)
* P3-Normal
* P4-Low

The issue tracker would have a mapping table for Github label to "list" (in this case priority).

### Use labels to show category

For example:

* /Administator
* /Installation

The principle here is to use a common prefix to group lists in Github. The mapping table mentioned previously takes care of how that looks in the Issue Tracker. We don't even need a UI for this, just update the db mapping table by hand "for now".

### Use milestones and the natural separation of Issues and Pull Requests to map the workflow. 

To this end I'd suggest the following:

* New issues are Open with no milestone.
* A confirmed issue (comment with #confirmed) moves to a "Confirmed" milestone
* All pull requests are automatically considered ready for testing. PR's must link to an issue they fix or address if one exists.
* Anyone who tests a PR and it passes comments with a #test or #tested.
* A PR that is tests moves to a "Review Ready" milestone where it awaits the commit team to review.

We can create a very simple Joomla-Jenkins job to change the milestones when it detects those special hash tags in comments.

### Change the testing requirements

* Unless specified otherwise, PR's require 2 good tests.
* Changes to non-code text (DocBlocks, language strings, etc) do not need any testers and go straight to "Review Ready"
* The pull team may ask for more testers where the degree of change or impact warrants it.

### Cookie jars and backlogs

* Optionally use labels to show a degree of complexity, more so people can identify easy bugs to fix. I work with a Fabonacci sequence and prefix with a tidle, so it goes like ~1, ~2, ~3, ~5, ~8 ... and it would roughly translate into hours but it really means that a ~8 bug is 8 times more difficult or time consuming that a ~1.
* Use special labels for backlog (things we should have done but didn't get around to) and new tasks or wish lists (things we could or should do).

### Manage teams on Github

We should be managing the teams using the Github teams system so that both the Github org and the Issue Tracker share the same access control groups (no need to have any UI to manage groups in the Issue Tracker).

***

On Github you do need pull rights to be able to assign milestones and labels. This is where the Issue Tracker steps in to bridge that gap. Nevertheless, all of the above is possible now to do just in Github if we wanted to. But in the mean time I think it's important to discuss and finalise the workflow.

**Comment by elkuku** [comment]
has not been implemented.
