### ISSUE TITLE
Issue Status

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#318]
I can see how I can edit an item to change its status (is that something everyone can do or is it because of my own account settings) but is that the best way to do it. Currently you cannot change status and comment at the same time.

**Comment by zero-24** [comment]
@b2z any more questions or problems here? I also would like to see the labels on github. Prefix `~` sounds ok for me (if we realy need one)

I think for theory we need to run a `addStatusAsLabel` function on the save action on JTracker as we can only change the Jissues status there.

Maybe a similiar thing that we have for the closed and open state?
https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Issue/Save.php#L100-118

Example code could be look like this:
```php
	private function getLabelForStatus($issue_id)
	{
		switch ($issue_id)
		{
			case 1:
				$label = '~Open';
				break;
			case 2:
				$label = '~Confirmed';
				break;
			case 3:
				$label = '~Pending';
				break;
			case 4:
				$label = '~RTC';
				break;
			case 5:
				$label = '~Fixed';
				break;
			case 6:
				$label = '~Review by Maintainers';
				break;
			case 7:
				$label = '~Information Required';
				break;
			case 8:
				$label = '~Platform';
				break;
			case 9:
				$label = '~No Reply';
				break;
			case 10:
				$label = '~Closed';
				break;
			case 11:
				$label = '~Expected Behavior';
				break;
			case 12:
				$label = '~Known Issue';
				break;
			default:
				$label = '~Unknown Status';
		}

		return $label;
	}
private function addLabelToGitHub(...)
{
// let the github bot add it if needed
}
```
switch and ID --> Status based on: https://github.com/joomla/jissues/issues/318#issuecomment-39342217

Some code is allready there for the RTC label (https://github.com/joomla/jissues/commit/08be5c5be7f612778c7930be96dde9eed925b7b9) but it only run on a new commit. i think we should run our function on the issue save on Jissues.

**Comment by b2z** [comment]
@zero-24 nope, no questions here. Simply I do not have enough time as earlier to implement it. There are still more issues to fix and this one is not the prior one...

**Comment by zero-24** [comment]
Ok sorry @b2z Thanks!

**Comment by zero-24** [comment]
@b2z i hope you can have a look into: https://github.com/joomla/jissues/pull/598

**Comment by mbabker** [comment]
Is there still interest in having statuses as labels?  If so, someone care to take a stab at this?

**Comment by b2z** [comment]
If interest still there I will try to do it. BTW - what labels on GitHub already represent statuses on tracker, like RTC? Those should not be synced?
