### ISSUE TITLE
Multilingual Issue No. 2

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#488]
If you switch language then the pre-filled markdown text is always in english.

In addition the non-english version should probably ask people to only post in english

**Comment by mbabker** [comment]
So we switched the issue template to pull from GitHub if the repo supports it, and GitHub doesn't support translating these.  Unless we revert #750 then merge #749 and work a way to push those templates into a .pot file I'm not sure this is something we can deal with.

**Comment by mbabker** [comment]
Last call on this.  As much of an improvement as it would be, I'm not 100% what we can/should do on this or whether it's practical to do anything.

**Comment by mbabker** [comment]
Last call was ignored.  Unless someone's got a bright idea, I think we're as good as we're going to get here.
