### ISSUE TITLE
Categories mouseover show html 

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#514]
#### Steps to reproduce the issue

1. edit a issue
2. add one category (e.g. Fronted)
3. mouseover the dropdown

#### Expected result

the selected category will show

#### Actual result

is show html code like 
`<span class="label" style="background-color: #eb6420;">  </span>Front End`

#### Additional comments

If we select more than one category it is ok.

**Comment by zero-24** [comment]
@mbabker 1.6.4 is released see: https://github.com/silviomoreto/bootstrap-select/releases/tag/v1.6.4 :smile:

**Comment by mbabker** [comment]
Ran a Bower update and deploying updated media to live now.

**Comment by zero-24** [comment]
hmm is it expeced that we don't see the changes here? https://github.com/joomla/jissues/commit/d12075912fc4ef30f5cdea7e8fbe7c6ad7c50cd8

**Comment by zero-24** [comment]
but it works :smile: Thanks!

**Comment by mbabker** [comment]
There isn't a lock file like for Composer that you would see a version change and the `www/vendor` folder that Bower assets are downloaded to is gitignored.

**Comment by zero-24** [comment]
Thanks!
hmm maybe realted that the `search box` is not closed now?
![dropdown](https://cloud.githubusercontent.com/assets/2596554/7101096/d227142c-e045-11e4-9641-cab79e6e0cd9.PNG)
