### ISSUE TITLE
Sync of the title field Github -> JTracker and JTracker -> Github

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#515]
#### Steps to reproduce the issue

see here:
https://github.com/joomla/joomla-cms/issues/4376#event-171151816
and here:
http://issues.joomla.org/tracker/joomla-cms/4376

The Titel was not updated

After i add a category on JTracker
http://issues.joomla.org/tracker/joomla-cms/4376#event-36154
It update the title on github
https://github.com/joomla/joomla-cms/issues/4376#event-171185349

#### Expected result

If somone change the titel on gitub it is synced to JTracker

#### Actual result

If somone change the titel in github it is not synced to JTracker

**Comment by b2z** [comment]
Is it still valid?
