### ISSUE TITLE
Handling bounces

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#537]
See http://issues.joomla.org/tracker/joomla-cms/4666

We need a way to not include bounces and out of office replies

**Comment by mbabker** [comment]
I don't know if this is something we can handle as we're just receiving data posted to GitHub.  So if GitHub's receiving those emails and converting them into issue comments...

**Comment by mbabker** [comment]
Closing as "can't fix".  This should be a feature request to GitHub.
