### ISSUE TITLE
Sync issue with original post

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#541]
I have edited a LOT of reports so that we have correct test instructions and descriptions etc. 

One user has done the same for their own but I am assuming he did it on github not on jissues

The changes he did on github are not reflected on jissues
https://github.com/joomla/joomla-cms/pull/4770#issuecomment-59606929
http://issues.joomla.org/tracker/joomla-cms/4770

I would be really grateful if someone could check into this as it is causing issues as you can see by the comments

**Comment by b2z** [comment]
Is this still valid?

**Comment by zero-24** [comment]
@b2z yes but as far I know as expected behavior. :smile:

Change a issue on JTracker Updates Github. Change a issue on Github will be synced back to the state of JTracker if the cron runs :smile:

**Comment by b2z** [comment]
Yeah previously we have had some problems with this cron job. Now it seems that we are running fine.

Anyway I am not sure that we can make it live. There is a `rename` event, but it is only provided for `renamed` events. As I understood we can not create a webhook for it. @mbabker am I right?

**Comment by elkuku** [comment]
I assume that this has been fixed.
