### ISSUE TITLE
Redesign Language Switcher Module

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#582]
The more languages we get, the longer that dropdown gets.  Any suggestions on improving the design/layout of the language switcher?

![screen shot 2014-12-19 at 1 46 01 pm](https://cloud.githubusercontent.com/assets/368545/5509400/6af33d76-8785-11e4-96e0-c23f73b91d93.png)

**Comment by b2z** [comment]
I like what @brianteeman has proposed. Will try to implement.
