### ISSUE TITLE
Permalink button don't work with more than one selection

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#584]
#### Steps to reproduce the issue

- access: http://issues.joomla.org/tracker/joomla-cms
- filter per category `Router / SEF`
- and filter per User `Hackwar`
- try the permalink button

#### Expected result

![screen shot 2014-12-28 at 18 12 55](http://issues.joomla.org/uploads/2/a86e31bd40b395c6cbee71ee248cd8e0.png)

All PRs that match to both conditions get displayed (as we have if we select it manually)

#### Actual result

![screen shot 2014-12-28 at 18 12 47](http://issues.joomla.org/uploads/2/8c3178fc79547ce66f73fe04b2afb8cc.png)

All PRs by the user get displayed.

**Comment by b2z** [comment]
The issue is that the button "takes" the category name. And honestly I do not have any idea how to pass alias instead of name to it, because alias is not available in the template :(

**Comment by b2z** [comment]
You are welcome to test it in #592

**Comment by zero-24** [comment]
closing here as the PR #592  by @b2z fix this issue. Thanks!
