### ISSUE TITLE
Posts deleted at github not deleted on the tracker

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#586]
#### Steps to reproduce the issue
Compare https://github.com/joomla/joomla-cms/issues/5148 and http://issues.joomla.org/tracker/joomla-cms/5148

#### Expected result
Spam posts deleted at github are also removed on the issue tracker

#### Actual result
spam posts are not deleted

**Comment by mbabker** [comment]
This one is going to be tricky.  If the API doesn't send some sort of event that indicates a post was deleted nor does it return a response with a message or status code indicating that, I'm not too sure what we could possibly do to remove posts other than manually purge the database.

**Comment by brianteeman** [comment]
Well is it possible to give those of us with permission to delete / edit a
post on GitHub the same abilities on jissues?

**Comment by mbabker** [comment]
I hadn't realized GitHub allowed deleting comments.  Maybe it is possible to update that in the automated handlers as long as there's some sort of API trigger.  As for app permissions, shouldn't be too troublesome to add a delete action.

**Comment by brianteeman** [comment]
Thanks. Really appreciate you looking into this

**Comment by b2z** [comment]
Well I am not sure that we can make it - we do not have any comment ids on the tracker so we can not map them to GitHub comments.

**Comment by mbabker** [comment]
We have the comment ID in the activities table.

**Comment by b2z** [comment]
Yeah thought we did not. Then need to code this feature :laughing: Will try

**Comment by elkuku** [comment]
Honestly, I don't think that this is an enhancement.
We should call it a *critical* bug and try to fix at least the part that removes comments from the JTracker&trade; db when they are removed on GitHub. Otherwise we have to delete spam entries manually from the database...

Let's do the "deleting on JTracker" in a separate PR, unless @b2z feels like he could also code this feature so I wouldn't try to stop him, of course :wink:

**Comment by b2z** [comment]
> Let's do the "deleting on JTracker" in a separate PR

Yeap I will break it into two different tasks:

1. Delete on GH -> delete on JTracker
2. Delete on JTracker -> delete on GH

If you will you can help me out to complete them please let me know which task will you code to avoid duplicate work :)

**Comment by allenzhao** [comment]
I can help on this if no volunteers :)


-------------------------------------------------------------
顺颂时祺  |  Best Wishes

赵泽涵  |  Allen Zhao

中国·对外经济贸易大学 /  信息学院2011级 / 电子商务(国际商务方向)
E-Business and International Business | School of Information Technology and Management Engineering | Class of 2015
University of International Business and Economics, Beijing, P.R.China
 

Tel:+86 18810467408
E-mail: i@allenzhao.com / 201136040@uibe.edu.cn / cnallenzhao@gmail.com
地址：中国·北京市朝阳区惠新东街10号对外经济贸易大学汇智公寓457室
Address:Room 457, Huizhi  Buliding, University of International Business and Economics, No,10 Huixin East Street, Beijing, P.R.China 
--------------------------------------------------------------
This message is a private communication. The information contained in this message or attached to this communication may be protected from disclosure and may contain information that is legally privileged, proprietary, and/or confidential. If you are not the intended recipient, please do not read, copy, use, or disclose it to others. Please notify the sender of the delivery error by replying to this message, and then delete it and any attachments from your system. Thank you. 

-------------------------------------------------------------

**Comment by b2z** [comment]
> I can help on this if no volunteers :)

Then you can take the second part :) 

I already have started to implement the first part. Though I have some difficulties with it because GH does not have any web hooks for comment delete. I think I found the way how to bypass it, but it will take too many resources and I am not sure that it is the best way. I need some time to think more on it :thought_balloon:

**Comment by elkuku** [comment]
@b2z 
> I think I found the way how to bypass it,

Well my thought here would be to just add it to the CLI script where we get the comments [here](https://github.com/joomla/jissues/blob/master/cli/Application/Command/Get/Project/Comments.php#L311) (I hope deleting comments changes the last modified date - no time for testing currently..).
So it would be processed when the cron job runs.

@allenzhao 
> I can help on this if no volunteers :)

Go for it :wink:

**Comment by b2z** [comment]
@elkuku hmm could be an option. But it will work only if issue is changing on delete. I'll need to test it :)

BTW my initial thought was to create new [update command](https://github.com/joomla/jissues/tree/master/cli/Application/Command/Update), but it will require to process all issues :(

**Comment by b2z** [comment]
So the first pat is implemented. Need a review.

**Comment by b2z** [comment]
@allenzhao any news on it? Will manage it or pass it to me? ;)

**Comment by allenzhao** [comment]
Ah, so sorry I’ve been busy and missing all the messages here. But I guess I need to discuss it with you and get some updates from you before I can get started.

I think I can finish it this weekend, but first I’ll have to get everything set up after I re-installed OS X on my mac, it was a total disaster.

So the thing I need to do, is to add a event when deleting a comment on JTracker, I found an API of this, so will this work?


https://developer.github.com/v3/issues/comments/#delete-a-comment

If this is the way to do it, I can make a pull request this weekend ;)

But first I need to get vagrant up and running on my mac…

Sorry for the delay again!




-------------------------------------------------------------
顺颂时祺  |  Best Wishes

赵泽涵  |  Allen Zhao

中国·对外经济贸易大学 /  信息学院2011级 / 电子商务(国际商务方向)
E-Business and International Business | School of Information Technology and Management Engineering | Class of 2015
University of International Business and Economics, Beijing, P.R.China
 

Tel:+86 18810467408
E-mail: i@allenzhao.com / 201136040@uibe.edu.cn / cnallenzhao@gmail.com
地址：中国·北京市朝阳区惠新东街10号对外经济贸易大学汇智公寓457室
Address:Room 457, Huizhi  Buliding, University of International Business and Economics, No,10 Huixin East Street, Beijing, P.R.China 
--------------------------------------------------------------
This message is a private communication. The information contained in this message or attached to this communication may be protected from disclosure and may contain information that is legally privileged, proprietary, and/or confidential. If you are not the intended recipient, please do not read, copy, use, or disclose it to others. Please notify the sender of the delivery error by replying to this message, and then delete it and any attachments from your system. Thank you. 

-------------------------------------------------------------

**Comment by b2z** [comment]
It's ok :) Not only event, but also user interface on JTracker (like delete button or something). Currently we do not have such :)

**Comment by allenzhao** [comment]
Oh, I thought we supported that.
And we're missing editing as well. So maybe editing as another enhancement or shall I implement them together?

**Comment by elkuku** [comment]
> shall I implement them together?

I'd make it two steps since it would be easier to review and would solve the current issue.

BTW: Great to have you back - internet access seems to get worse every day in your country - must be really frustrating :disappointed:

**Comment by allenzhao** [comment]
Sure, I will implement delete first.



Yes, especially after they blocked Google, I have some trouble in using Gmail for a while. But luckily I got some reliable proxy services makes it better.



-------------------------------------------------------------
顺颂时祺  |  Best Wishes

赵泽涵  |  Allen Zhao

中国·对外经济贸易大学 /  信息学院2011级 / 电子商务(国际商务方向)
E-Business and International Business | School of Information Technology and Management Engineering | Class of 2015
University of International Business and Economics, Beijing, P.R.China
 

Tel:+86 18810467408
E-mail: i@allenzhao.com / 201136040@uibe.edu.cn / cnallenzhao@gmail.com
地址：中国·北京市朝阳区惠新东街10号对外经济贸易大学汇智公寓457室
Address:Room 457, Huizhi  Buliding, University of International Business and Economics, No,10 Huixin East Street, Beijing, P.R.China 
--------------------------------------------------------------
This message is a private communication. The information contained in this message or attached to this communication may be protected from disclosure and may contain information that is legally privileged, proprietary, and/or confidential. If you are not the intended recipient, please do not read, copy, use, or disclose it to others. Please notify the sender of the delivery error by replying to this message, and then delete it and any attachments from your system. Thank you. 

-------------------------------------------------------------

**Comment by b2z** [comment]
@allenzhao are you working on it? If no I could make it.

**Comment by allenzhao** [comment]
I'm working on this, hopefully I will open a pull request this weekend.
Sorry for the delay, I was on a vacation and didn't had Internet connection
at all.

**Comment by b2z** [comment]
:+1:

**Comment by elkuku** [comment]
> I'm working on this, hopefully I will open a pull request this weekend.

Hmm, seems that weekend was long :wink:

**Comment by mbabker** [comment]
This still need action?

**Comment by brianteeman** [comment]
I think so. There was a guy who posted his password the other day and I
deleted the post on github but I think it's still in the tracker. On my
phone right now but will check again later

**Comment by mbabker** [comment]
For deleting from GitHub the last I remember they aren't sending a webhook on that activity so it relies on the cron job that runs every half hour to handle that.  And we still don't have the delete button in the app it looks like.

**Comment by brianteeman** [comment]
30 minutes is probably OK but a delete button would be better

**Comment by b2z** [comment]
Closing #782
