### ISSUE TITLE
Email notification and subscribe

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#588]
Are there any plans to add email notifications and subscriptions to JIssues

Currently the only option is to do this via github which has limited options.  (I would love the ability to stop the tracker sending me emails when specific users post as 99% of the time they are off topic and irrelevant but I still have to read them to check)

It would be so much better if we have email notifications coming from jissues so that links in emails for example are all to jissues and not github.

**Comment by b2z** [comment]
Is it the same as #168 ?

**Comment by infograf768** [comment]
I wish a Notification system was introduced indeed which lets choose the category(ies) one wants to follow.

**Comment by b2z** [comment]
So if we will create such a system should we silently "Unsubscribe" (and may be also "Unwatch") a user from the issue on the GitHub?

**Comment by mbabker** [comment]
We do need our own email integration, but IMO priority should go to admin stuff over frontend user traffic at first.  At a minimum this should be wired into the webhook and CLI systems to ping on critical failures.
