### ISSUE TITLE
Make JForm::getFieldset to choose if >>group<< don't should be set

### ISSUE THREAD

**Issue by ststay** [joomla/jissues#589]
Joomla! Version 3.3.6 Stable
------------------------------------
By creating forms with the ease of structured XML-files and "getFieldset", i ran into a "neither want controls nor want groupings" of the name-attribute and saw that it's a fixed statement in the getFieldset-function.

.../libraries/joomla/form/form.php

Don't know why fixed groupings (for the name attribute) should be necessary, but for me it would be easier to decide in some cases, not to use groupings at all...

**Comment by elkuku** [comment]
Hi,
this repository is for the Joomla! Issue Tracker application. Your issue pertains to the Joomla! CMS, please report your issue at https://github.com/joomla/joomla-cms/issues/new

Thanks!
