### ISSUE TITLE
Jissues bot - no code attached yet

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#590]
If an issue is created directly on github then the bot runs and the label `No Code attached Yet` is applied
But If an issue is created directly on Jissues then the bot does not run and the label is not applied even though the issue is created on github but by JIssues and not the end user

I have just manually applied the No Code attached Yet` label

**Comment by b2z** [comment]
@brianteeman I am not so familiar with the JBS workflow - should this label be always set for non-PRs ?

**Comment by mbabker** [comment]
The behaviors should be consistent when an issue is created on GitHub versus created from the app.

**Comment by b2z** [comment]
> The behaviors should be consistent when an issue is created on GitHub versus created from the app.

Sure, but when this label is being added? This is not clear to me :)

**Comment by zero-24** [comment]
@b2z

>Sure, but when this label is being added? This is not clear to me :)

The ```No Code attached Yet` label``` is added if it is no pull request. So all github `issues` should have this label :smile:

**Comment by mbabker** [comment]
It's being added in the webhook controllers, specifically the event listener for the CMS repo.

**Comment by b2z** [comment]
See my PR. No more manual work for @brianteeman and others I hope :wink:
