### ISSUE TITLE
Add "Language" label assignment to CMS Pull Listener

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#591]
See https://github.com/joomla/user-interface-text/issues/30

Whether this gets followed through on or not, I'm going to add a "Language" label to the CMS repo and logic to the pull listener to label pulls that have changes to the language strings.

**Comment by brianteeman** [comment]
Awesome - thanks

On 8 January 2015 at 13:33, Michael Babker <notifications@github.com> wrote:

> See joomla/user-interface-text#30
> <https://github.com/joomla/user-interface-text/issues/30>
>
> Whether this gets followed through on or not, I'm going to add a
> "Language" label to the CMS repo and logic to the pull listener to label
> pulls that have changes to the language strings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/591>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by b2z** [comment]
Test comment do not reply

**Comment by brianteeman** [comment]
Did you ever do this?

**Comment by mbabker** [comment]
Not yet.  I do mean to get to it (if someone else doesn't), I just need to carve out some time.
