### ISSUE TITLE
Tracker is not in sync on the issue #5681

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#593]
#### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/issues/5681
http://issues.joomla.org/tracker/joomla-cms/5681

#### Additional comments

Looks like the Tracker is not in sync on this issue.
The comment by @brianteeman is missing on JTracker.

#### Other Question

How should sync issues like this report? Via Tracker or something else?

**Comment by brianteeman** [comment]
At the time I made that comment issues.joomla.org was down. I was waiting
to see if it synced before raising an issue. It obviously hasn't. Thats
@zero-24

On 12 January 2015 at 12:47, zero-24 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> joomla/joomla-cms#5681 <https://github.com/joomla/joomla-cms/issues/5681>
> http://issues.joomla.org/tracker/joomla-cms/5681
> Additional comments
>
> Looks like the Tracker is not in sync on this issue.
> The comment by @brianteeman <https://github.com/brianteeman> is missing
> on JTracker.
> Other Question
>
> How should sync issues like this report? Via Tracker or something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/593>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
An issue here is fine for those notes.  The usual cause is that GitHub times out trying to send the webhook to the tracker (which shows in the webhooks log on the CMS), so anyone with access to the webhook management on the CMS repo can go in and resend the missing data (which has a warning indicator to make it easy to find).
