### ISSUE TITLE
Post test results with comment on edit (JBS) view

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#594]
Hi,

@b2z implements here: https://github.com/joomla/jissues/pull/563 the `Post test results with comment` function.

Can we add this also to the second text box on the issue edit view?

![post_test_results_by_comment](https://cloud.githubusercontent.com/assets/2596554/5744929/2d23c664-9c25-11e4-9b53-b63d1acc4d53.PNG)

**Comment by b2z** [comment]
I think so...

**Comment by zero-24** [comment]
Fixed with the new test option
