### ISSUE TITLE
Undefined index 'easy'

### ISSUE THREAD

**Issue by wilsonge** [joomla/jissues#600]
I edited an issue on the issue tracker from "Closed" to "Expected Behaviour" and the screen flashed up with a php warning of an undefined index of 'easy'. However the issue appears to have saved as expected with the change of status successful.

Any ideas?

**Comment by b2z** [comment]
Should be fixed 42b0b59. Not deployed yet.

**Comment by wilsonge** [comment]
Ahhh awesome :) Way ahead of me :P Nice one!

**Comment by mbabker** [comment]
Missed that notification, deployed
