### ISSUE TITLE
Add weblinks repo

### ISSUE THREAD

**Issue by wilsonge** [joomla/jissues#603]
Spent some time looking for a way to do this but guessing I don't have the permissions. So can we add the weblinks repo please as a project?

**Comment by mbabker** [comment]
http://issues.joomla.org/tracker/weblinks

**Comment by elkuku** [comment]
What about com_localise - any interest? :wink:

**Comment by wilsonge** [comment]
I guess as it's core maintained we probably should :unamused:  (see now you made me think about it :stuck_out_tongue: )
