### ISSUE TITLE
Issue not in sync

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#605]
compare https://github.com/joomla/joomla-cms/pull/5958 with http://issues.joomla.org/tracker/joomla-cms/5958

Regarding the images

**Comment by mbabker** [comment]
They look the same to me.  On both sites, the URL for the image is missing which creates the broken Markdown syntax.

![screen shot 2015-02-03 at 1 25 15 pm](https://cloud.githubusercontent.com/assets/368545/6026354/39a0b5ae-aba8-11e4-97ea-8483a6994ca7.png)
![screen shot 2015-02-03 at 1 25 39 pm](https://cloud.githubusercontent.com/assets/368545/6026357/3b2f90c0-aba8-11e4-84c8-00b970be1de4.png)

**Comment by zero-24** [comment]
hmm looks like i removed it by adding the category :smile: I will ask the TE for re adding it via jissues thanks for checking.
