### ISSUE TITLE
Recently Updated ?

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#607]
Select the recently updated filter.

I would expect this to sort the issues by the most recently updated.

Not sure what it is sorting by but an issue with ID 4022 is at the top of the list. It is almost as if all issues created after this one are not included in the results

**Comment by b2z** [comment]
Well I do not know why but issues from 4022 to 920 has a `Modified 2015-02-04`. That is why these are on the top of the list. If you click on page 4 then you can see that there are issues starting from 5966. That is weird, but seems that `modified_date` was altered.

**Comment by brianteeman** [comment]
OK so that explains why it happened

Can it be fixed to make this feature usable

On 4 February 2015 at 12:32, Dmitry Rekun <notifications@github.com> wrote:

> Well I do not know why but issues from 4022 to 920 has a Modified
> 2015-02-04. That is why these are on the top of the list. If you click on
> page 4 then you can see that there are issues starting from 5966. That is
> weird, but seems that modified_date was altered.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/607#issuecomment-72846928>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by b2z** [comment]
I hope @mbabker can look into it and alter the `modified_date` in the DB. I do not see other ways how to fix it :(

**Comment by mbabker** [comment]
It has to be something that was done in the cron jobs.  The modified dates of 160 items on this tracker correspond with the cron that ran at 2015-02-04 13:00:00 GMT and the cron log itself supports this:

```sh
[2015-02-04 07:00:02] JTracker.INFO: Start retrieve Issues [] []
[2015-02-04 07:00:02] JTracker.INFO: Processing project: J!Tracker [] []
[2015-02-04 07:00:07] JTracker.INFO: Retrieved 607 items from GitHub. [] []
[2015-02-04 07:00:42] JTracker.INFO: 0 added, 161 updated. [] []
```

**Comment by b2z** [comment]
omg today these issues have 02-05-2105. Something really weird happening here ...

**Comment by b2z** [comment]
Fixed
