### ISSUE TITLE
Updating Travis status

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#613]
If you look at #4211 on the issue tracker you will see it has a status of failed and the link to travis at the top of the page shows the failure.

However if you look at it on github you can see that travis passes because there was an update to the PR and the linked one used on i.j.o has not been updated

**Comment by elkuku** [comment]
This looks good now.

Might have been solved by a recent change (I hope) - Could you have an eye on it if possible?

**Comment by elkuku** [comment]
Seems fixed - no reply :wink:
