### ISSUE TITLE
Dublicate issue on Jissues #5966

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#615]
#### Steps to reproduce the issue

http://issues.joomla.org/tracker/joomla-cms/5966
and
http://issues.joomla.org/tracker/joomla-cms

#### Additional comments

see: ![screen shot 2015-02-04 at 15 22 52](http://issues.joomla.org/uploads/1/2a817219d0a5e3046050a8b6e026702c.png)

**Comment by mbabker** [comment]
Gone

**Comment by b2z** [comment]
@mbabker do you have an idea why did it happen?

**Comment by mbabker** [comment]
None at all
