### ISSUE TITLE
Mail Integration

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#619]
We probably should wire up our automated tasks (cronjobs and web hooks) to have some sort of e-mail notification in case of a failure so we can more readily catch and respond to issues from those events.

**Comment by b2z** [comment]
Do you mean catching all exceptions or only errors from CLI jobs?

**Comment by mbabker** [comment]
If it gets triggered automatically and doesn't display an error message to a user, we should have some sort of logging and notification around it.

**Comment by b2z** [comment]
Actually currently we are showing all Exceptions to a user in non CLI application (and that is definitely not a good idea). What I think is that instead we should show some generic error message and log this exception or in some cases send an email with exception details.

**Comment by mbabker** [comment]
Use #588 for all email integration stuff.
