### ISSUE TITLE
syncing milestones back to github

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#622]
Hi,

### current behavior

- add a milestone on github
=> JTacker gets it too (i think with the cron job)

- add a milestone on JTracker
=> It don't get synced back to github.

### expected behavior

If we add a milestone on JTracker and save the issue the milestone gets synced.

### A way to fix it

I think we can add some code to the `updateGithub` methode here:
https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Issue/Save.php#L271

Or should this also wait? As it is to projekt specific?

**Comment by b2z** [comment]
Yeap it's again the same situation. We do not need to put it into main controllers.

**Comment by elkuku** [comment]
I wonder if this is not something we want to do for all projects managed on GitHub?...

**Comment by mbabker** [comment]
I think I'd add it to a pool of actions and probably make it more of an opt-out thing at the project level.

All this action stuff might make for a good GSoC project...

**Comment by b2z** [comment]
And what about #596. I have a feeling that it might work?

**Comment by b2z** [comment]
> I wonder if this is not something we want to do for all projects managed on GitHub?...

Agree it is not too project specific as I thought. That is why I've made it in the #425. It will sync along with the labels. And yes - it is in the main controller currently :see_no_evil: 

> I think I'd add it to a pool of actions and probably make it more of an opt-out thing at the project level.

This should be the second phase. At least we have it abstracted in the separate method.

**Comment by zero-24** [comment]
Closing as this gets fixed with: https://github.com/joomla/jissues/pull/425 Thanks!
