### ISSUE TITLE
com_patchtester integration

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#623]
Cross reference to https://github.com/joomla-extensions/patchtester/issues/65

Is it possible to do this via the [tracker app's save issue controller](https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Issue/Save.php) or is a separate response point needed?

**Comment by b2z** [comment]
You will need a [Controller/Comment/Ajax/Submit.php](https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Comment/Ajax/Submit.php)
But what about a user? You are planning to authorize him through the `com_patchtester`?

Small tests of routes also is something to explore:
http://issues.joomla.org/tracker/submit/comment
```
0 RuntimeException
No id given
```

http://issues.joomla.org/tracker/jtracker/submit/comment
```
404 JTracker\Router\Exception\RoutingException
Bad Route
```

**Comment by elkuku** [comment]
> You are planning to authorize him through the com_patchtester?

The authorization thingy is also something that I don't really know how to accomplish it.

Thoughts?

**Comment by mbabker** [comment]
Something in the component to authenticate to the site (which in turn authenticates to GitHub) and the site returns the OAuth token to the component perhaps?
