### ISSUE TITLE
Contact default template : need a space after the contact class (line 16)

### ISSUE THREAD

**Issue by tramber91** [joomla/jissues#624]
Hi
Issue when I add a page class on contact menu item. I need a space to use the new class

Line 16 of /components/com_contact/views/contact/tmpl/default.php should have a space added after the contact class.
Out of that the new class is sticked to the contact like class="contactnewclass"
#### System information (as much as possible)

joomla 3.4 and below

**Comment by brianteeman** [comment]
The default documented action when adding any new class in the relevant
fields is always to precede it with a space.

On 25 February 2015 at 23:45, tramber91 <notifications@github.com> wrote:

> Hi
> Issue when I add a page class on contact menu item. I need a space to use
> the new class
>
> Line 16 of /components/com_contact/views/contact/tmpl/default.php should
> have a space added after the contact class.
> Out of that the new class is sticked to the contact like
> class="contactnewclass"
> System information (as much as possible)
>
> joomla 3.4 and below
> Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/624>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by b2z** [comment]
Hi!

This is tracker for JIssues Project, not for CMS. Anyway @brianteeman is right - you should always precede it with a space if you want to add as a separate class, not a suffix to existing.

**Comment by brianteeman** [comment]
Oops I didnt notice that the post was on the wrong tracker.

On 26 February 2015 at 08:32, Dmitry Rekun <notifications@github.com> wrote:

> Hi!
>
> This is tracker for JIssues Project, not for CMS. Anyway @brianteeman
> <https://github.com/brianteeman> is right - you should always precede it
> with a space if you want to add as a separate class, not a suffix to
> existing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/624#issuecomment-76140159>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by tramber91** [comment]
Curious I was sure to add a comment, I retry?
You close the post OK

But for my side I have an issue with Rockettheme template contact page. And they told me that issue coming from Joomla!

So, I agree that It is OK for contact class itself when I add a space before class but, in that case, I cannot play with the body class because Joomla add a minus "-" instead of space to my custom class (page class)
change " newclass" by "-newclass"

**Comment by brianteeman** [comment]
The correct tracker is http://issues.joomla.org/tracker/joomla-cms

On 26 February 2015 at 13:10, tramber91 <notifications@github.com> wrote:

> Curious I was sure to add a comment, I retry?
> You close the post OK
>
> But for my side I have an issue with Rockettheme template contact page.
> And they told me that issue coming from Joomla!
>
> So, I agree that It is OK for contact class itself when I add a space
> before class but, in that case, I cannot play with the body class because
> Joomla add a minus "-" instead of space to my custom class (page class)
> change " newclass" by "-newclass"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/624#issuecomment-76175288>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by tramber91** [comment]
Thanks sorry Brian
I have to recreate a post ?

**Comment by b2z** [comment]
@tramber91 I am not sure that this is an issue. We have a consistent behavior between all CMS components - this class is a suffix, not a separate class. It always was. So the contact page design of Rockettheme template is wrong if it does not support the default behavior of the CMS.

**Comment by tramber91** [comment]
Ok thanks
anyway i can found a trick to resolve my contact page issue (In french) it is OK in english
My first post in your bug tracker tools !! Not a bug, Not in right place, should be better next time ;=)

have a nice day

take care

**Comment by b2z** [comment]
@tramber91 nobody is perfect :wink:  Take care
