### ISSUE TITLE
Closed items dont get removed from the open only view

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#629]
see:
![screen shot 2015-03-06 at 16 41 22](http://issues.joomla.org/uploads/1/5cb1f9bd9edb0ad437281c57d41c3947.png)

**Comment by brianteeman** [comment]
This seems to happen only when an issue is closed at github.  I closed a few that way today and this is the result<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/629">issues.joomla.org/jtracker/629</a>.</sub>

**Comment by brianteeman** [comment]
OK I was wrong above. I just closed an issue directly on the tracker and this is also still being displayed <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/629">issues.joomla.org/jtracker/629</a>.</sub>

**Comment by b2z** [comment]
I do not understand how it can be, but confirmed. The same problem also for JTracker project :(

**Comment by b2z** [comment]
Well just updated the dependencies and have the same issue locally. Seems that again there is some filtering problem. Trying to fix.

**Comment by brianteeman** [comment]
thank you for looking into this

On 7 March 2015 at 17:20, Dmitry Rekun <notifications@github.com> wrote:

> Well just updated the dependencies and have the same issue locally. Seems
> that again there is some filtering problem. Trying to fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/629#issuecomment-77699152>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by b2z** [comment]
Seems that the bug is in the Registry class. This line return `null` instead of `0`:

```php
$filter = $this->state->get('filter.state');
```

@mbabker we need your support also here :zap:

**Comment by mbabker** [comment]
Wow, I can close issues across organizations and repos :smiley:

https://github.com/joomla-framework/registry/commit/e15549ebdd6a12d67235ce21bd24ee7465b0b13a adds test cases which reproduces the failure we were htting here and https://github.com/joomla-framework/registry/commit/5c2e607ff61f8df07c3c0630ed62a8c3d892469e has the fix for it.

**Comment by b2z** [comment]
@mbabker you are the saver :+1: :laughing:

**Comment by zero-24** [comment]
Thanks :+1: looks fixed now!
