### ISSUE TITLE
GSoC

### ISSUE THREAD

**Issue by Hils** [joomla/jissues#630]
A suggestion:

Wouldn't it be a good idea to add a special label for GSoC PRs? Some 2014 PRs are still open but they should be highlighted to draw attention to them. Mentors put a lot of work into these PRs, Google paid a lot - so testers might pay special attention to them if they knew what they were.

**Comment by mbabker** [comment]
Don't need the issue tracker for that.  Just ping someone who has permissions on the CMS repo to add labels and they can take care of it.

**Comment by Hils** [comment]
So - all testers should ping someone who has permissions on the CMS repo to get labels added? You know I know to do that. But this is generally not for me. Or should the mentors & GSoC coders just be in the general queue? I was trying to think of how we could avoid our 2010 debacle. Or is there a label ready for Mentors to add to their PRs?

**Comment by mbabker** [comment]
On the adding labels thing, yes.  The issue tracker is just displaying the GitHub data, which includes labels.  If we were discussing a way to programmatically add labels to items on a recurring basis, this would indeed be the place to get it coded.

Unfortunately labels can't be managed by anyone except for those with high enough permissions on GitHub.  So the only real way to get labels added right now is to ping someone who can do so.

**Comment by Hils** [comment]
Gotcha - thank you Michael :)

**Comment by alikon** [comment]
i'm not so sure  that adding a label like "GSoC" to a PR will speed-up the tests,  
but let's try , can someone add that label to  #4115 , #4107
