### ISSUE TITLE
Repurposing the Easy test option

### ISSUE THREAD

**Issue by roland-d** [joomla/jissues#631]
This is not a bug report but a feature request. In the Joomla Issue tracker we have an option to set a tracker item to an Easy test, this is currently not being used.

Before every PBF (Pizza, Bugs and Fun) event someone has to go through the issue tracker and create a list of issues and classify it as easy, medium, or hard. This is used to get the PBF group started.

Rather than having to do this every time we have a PBF I would like to be able to do this as I work with the issue tracker.

My request is to:
1. Rename the Easy test to Level
2. Add the options Easy, Medium, and Advanced

Thanks for your consideration.

**Comment by brianteeman** [comment]
What do you mean it is not being used. I regularly set PR to easy

**Comment by roland-d** [comment]
That is good to know you are setting PRs to Easy. When I checked before (not today but months ago) I found PRs set to Easy that were not Easy. I am aware that classifying a PR is a judgement call.

In any case, it will be useful to add the other two levels so we can separate the PRs a little more than just Easy or everything else.

**Comment by brianteeman** [comment]
@roland-d Irrespective of whether the easy tag is being used correctly it is still not the best way to achieve what you want to do.

In the issue tracker there is no batch tagging. It would be much easier for your use case to add a label in github <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/631">issues.joomla.org/jtracker/631</a>.</sub>

**Comment by roland-d** [comment]
I just know we have this easy dropdown in the Jissues and figured that would be useful since it basically has the same use.

Why would the labels be a better fit?

**Comment by brianteeman** [comment]
1. Labels are displayed on the list view - the easy status does not
2. Labels appear on both the issue tracker and github - the easy status
does not
3. Batch adding and removal is possible with labels

On 15 March 2015 at 10:28, RolandD <notifications@github.com> wrote:

> I just know we have this easy dropdown in the Jissues and figured that
> would be useful since it basically has the same use.
>
> Why would the labels be a better fit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/631#issuecomment-80948132>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
4. Easy != PBF
We always have a mix of people at a PBF and it is better (imho) to be able
to show people a list if issues that we want to tackle at the PBF and that
would include "easy" and "hard" issues

By using both EASY and PBF we can let people filter first on PBF and then
if they are not advanced they can filter again on EASY

**Comment by roland-d** [comment]
I don't want to add a PBF label to the issues, just want to classify the issues as more than just easy. It is because of the mix that I want more than just the easy option. These issues we write on post-it notes and hang them on the wall for people to take, to get them off their seat and make the wall interactive and they can see the progress.

The gap between easy and hard is too large as far as I am concerned. There are quite a bunch of issues that fall in between. If we classify an issue as hard the majority of users will go for the easy ones. Medium ones they will try but they won't try hard issues.

The way issues are classified as Easy now is no different than classifying them as easy for a PBF event I think. If there is, then we have different set of how things are classified and then my point is moot to repurpose this.

**Comment by b2z** [comment]
So :) What is the final decision here?

**Comment by roland-d** [comment]
Sorry for the late reply but real life got in the way. I am still wanting an option where I can classify the easy/medium/advanced status of an issue. Now we have to do this over and over again for every PBF, not very efficient. Yes, it is not an exact science but it is better than nothing.

**Comment by brianteeman** [comment]
I just dont see why it is  over and over again and who is going to be doing
it. It should be part of the continual process. Plus if we were stricter
about removing useless issues and pull requests and feature requests for
things that are never going to happen and addressing the PR (10%) that are
waiting for a maintainer to make a decision on is it even something that we
need to do. Sorry but I really see this as a band aid to proper management
of the tracker

On 24 March 2015 at 17:14, RolandD <notifications@github.com> wrote:

> Sorry for the late reply but real life got in the way. I am still wanting
> an option where I can classify the easy/medium/advanced status of an issue.
> Now we have to do this over and over again for every PBF, not very
> efficient. Yes, it is not an exact science but it is better than nothing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/631#issuecomment-85604745>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by roland-d** [comment]
> It should be part of the continual process.

Exactly the reason I am asking to have more options than just easy. So we can use it not only during the PBF but also in regular usage.

>  Plus if we were stricter about removing useless issues and pull requests and feature requests for things that are never going to happen and addressing the PR (10%) that are waiting for a maintainer to make a decision on is it even something that we need to do. 

That is irrespective of the status. Even if this was cleaned up a 100% you would still have the issue of needing to say what kind of test it would be.

> Sorry but I really see this as a band aid to proper management of the tracker

I think we are talking about two different things.

As I don't see this going anywhere, I will close my request and thank you all for your time.
