### ISSUE TITLE
Label with spaces can't be created

### ISSUE THREAD

**Issue by rdeutz** [joomla/jissues#632]
#### Steps to reproduce the issue
Try to create a label like "This is a label"

#### Expected result
A label "This is a label"

#### Actual result
A label "Thisisalabel"

It can be changed over the github website so not a big issue

**Comment by brianteeman** [comment]
I see what you mean but I question if we should even be able to create labels on the issue tracker. They cant be applied to an issue. That can only be done in github<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/632">issues.joomla.org/jtracker/632</a>.</sub>

**Comment by rdeutz** [comment]
@brianteeman there is an option to it so it should work or the option should be removed.

**Comment by elkuku** [comment]
> They cant be applied to an issue.

There is actually some code ready in #425 to provide this functionality but the discussion about it has somewhat stalled...

**Comment by rdeutz** [comment]
@elkuku would be cool if we can have this. Is there also some "code ready" for adding a milestone?

**Comment by b2z** [comment]
We have this already.

чт, 19 марта 2015, 17:28, Robert Deutz <notifications@github.com>:

**Comment by elkuku** [comment]
> Is there also some "code ready" for adding a milestone?

That should already be possible if you have the access rights (which you should have). 

It should look like this (in german) :wink: :
![bildschirmfoto von 2015-03-19 10 34 53](https://cloud.githubusercontent.com/assets/33978/6734039/ddfe0122-ce23-11e4-9652-a7eb23a80dae.png)

**Comment by rdeutz** [comment]
ok, thanks for the quite response. I do need the proper rights to so? So if I can do it over github directly I can do it in the tracker?

**Comment by b2z** [comment]
> I do need the proper rights to so? So if I can do it over github directly I can do it in the tracker? 

Actually we do not have rights mapping from GitHub on tracker. Currently access groups on the tracker are: Public, User, JBS and PLT. Only PLT have "manage" right which is enough to manage milestones.

**Comment by rdeutz** [comment]
I am not asking for me ;-) But thanks for the info!
