### ISSUE TITLE
Looks like we have dublicate issues on the CMS

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#633]
#### Steps to reproduce the issue

see: http://issues.joomla.org/tracker/joomla-cms

#### Expected result

only one entry per issue

#### Actual result

![screen shot 2015-03-19 at 16 30 29](http://issues.joomla.org/uploads/1/4142b91cd433b469ba2158385daa36be.png)

**Comment by b2z** [comment]
Again some kind of synce issue?

**Comment by mbabker** [comment]
Cleared

**Comment by brianteeman** [comment]
Thanks

**Comment by elkuku** [comment]
Do we know what has caused this issue?

Am 21.03.2015 10:46 schrieb "Brian Teeman" <notifications@github.com>:
