### ISSUE TITLE
Looks like we have again a dublicate issues on the CMS

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#634]
See:
![screen shot 2015-03-22 at 15 33 11](http://issues.joomla.org/uploads/2/8036cdf0d4e6307c5a29ca257cde0b03.png)

Maybe we have sync issues if the github label was added bevor the sync to jissues?

Every time we have different sets of github labels for the "sync issue" - PRs? Same here: http://issues.joomla.org/tracker/jtracker/633

**Comment by mbabker** [comment]
I'd have to figure out what order the events are happening in to sort it out.  Long and short, nothing should be getting created before the issue/PR is actually opened (and based on the webhook log, this looks to be the case).  There'd have to be a race condition somewhere causing this.

**Comment by zero-24** [comment]
Now we have also open/closed dublicates on the jissues Tracker see:

![screen shot 2015-04-13 at 10 44 06](http://issues.joomla.org/uploads/2/dd9515db4bddbbe13f3ba34a6360c53b.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/634">issues.joomla.org/jtracker/634</a>.</sub>
