### ISSUE TITLE
Closed or open :D On issue is closed on the issue view but open on the main site

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#636]
#### Steps to reproduce the issue

see:
http://issues.joomla.org/tracker/joomla-cms/6599
![screen shot 2015-03-29 at 13 52 20](http://issues.joomla.org/uploads/2/b2a61ab712aa33a1ace05113f6bc0513.png)

and
![screen shot 2015-03-29 at 13 50 00](http://issues.joomla.org/uploads/2/c3d2097b1abff2e4f0d6c05a8224ccfe.png)

#### Expected result

The issue should show closed on the main site and the issue. ;) As Brian closed it.

#### Actual result

The issue is open on the main view and closed on the issue view ;)

**Comment by mbabker** [comment]
Ya, I got nothing.  Database shows it closed.

**Comment by zero-24** [comment]
did we have a site cache enabled?

**Comment by mbabker** [comment]
Nope

**Comment by brianteeman** [comment]
Before I closed one of them there were two on the tracker

On 29 March 2015 at 20:10, Michael Babker <notifications@github.com> wrote:

> Nope
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/636#issuecomment-87456259>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
I found 2 open activity records and deleted one.  Otherwise everything is fine as far as data integrity goes.
