### ISSUE TITLE
A big issue with the installation of joomla 3.0

### ISSUE THREAD

**Issue by Limax2014** [joomla/jissues#637]
I'm an italian girl and i don't speak (and write) english very well so i start whit excuse for the mistakes that i'll certainly do!!

I've tried to install the new version on Joomla but i think i do a b******t!!

I've followed the instruction that i found in the italian manual of Joomla but now every action that I try to do opens a blank page and a message like this: "Fatal error: Call to protected method JRequest::_cleanVar() from context 'FOFInput' in /home/uvfqtah5/domains/frimax.it/public_html/libraries/fof/input.php on line 30"

Please help me!! What i have to do? 

Sorry again for my english :(
![problema con joomla](https://cloud.githubusercontent.com/assets/11775880/6971144/b1d4cede-d97a-11e4-8b23-1c40c21221ee.png)

**Comment by zero-24** [comment]
@Limax2014 This is the Tracker of the Jissues application please try this Tracker for Joomla Core related issues: http://issues.joomla.org/tracker/joomla-cms<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/637">issues.joomla.org/joomla-cms/637</a>.</sub>
