### ISSUE TITLE
JTracker clean the title with 

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#638]
#### Steps to reproduce the issue

See:
http://issues.joomla.org/tracker/joomla-cms/6685

and
http://issues.joomla.org/tracker/joomla-cms/6684

The first `Differences` Tab.

There we remove code like `<jdoc>` and `<input type=text />` from the title

#### Expected result

The title will not changed automagic

#### Actual result

The title is changend by JTracker itself without user action.

**Comment by mbabker** [comment]
I'm not so sure how I feel about this one.  To change this in essence requires us to allow HTML input in the title and description fields and implement a filter that matches GitHub so we aren't opening ourselves up to a hack.

**Comment by zero-24** [comment]
as for  description it works ok with commenting like `<br>` but not for title see: http://issues.joomla.org/tracker/jtests/82 (try to use esting `<br>`)

if someone what us to hack this days he needs to open a issue on github with the code into the title this gets synced without cleaning into JTracker. Only on saving the issue it gets cleaned.

Did we have a chance to handel it by only removing the `<...>`? I'm not sure for the security impact.

But so we have all data there ;) If someone realy need full HTML Codes they should use commeting like `<your very bad html or other code>` into the description

**Comment by mbabker** [comment]
Description works fine because it doesn't filter data (we may be able to put the HTML filter around that, not so sure what side effects it could cause); the title is filtered as a string through the filter package.  As for the hooks they probably need to be refactored to store through the IssueModel versus IssueTable object as the model is doing all the filtering.

**Comment by b2z** [comment]
So #639 should fix it?

**Comment by mbabker** [comment]
Well, partially.  Now both sides should be using the same rules.  But, HTML is getting stripped in the title for both elements now.  So, we may need to use the HTML filter in Joomla's InputFilter object to make things work.
