### ISSUE TITLE
Select Categories looks bad now

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#640]
#### Steps to reproduce the issue

try to edit the category of an item. or add it on the submit view
![screen shot 2015-04-11 at 15 18 09](http://issues.joomla.org/uploads/2/da73bcf871ed374bf5c849603ab4fa05.png)

#### Expected result

You see the checked categorys.
the search don't get out of the view point

#### Actual result

- You can't see which category you add
- the search goes out of the view point.

#### System information (as much as possible)

looks like something is changed on updating the external libary here: https://github.com/joomla/jissues/issues/514

**Comment by mbabker** [comment]
All I've figured out is it is a change in bootstrap-select introduced in 1.6.4.  Installed 1.6.3 locally and the search box is fine.  Their demos render OK too, so I wonder if it's a quirk because of our template or a Bootstrap 2 thing since it seems they're mainly focusing on Bootstrap 3.

**Comment by mbabker** [comment]
Between 1.6.2 and 1.6.3, there looks to be a lot of changes to the rendering of the internal list.  This is where the active selections look to have broken.  Between 1.6.3 and 1.6.4 is when the search bar lost the right margin.

**Comment by zero-24** [comment]
Maybe it is fixed with 1.7.x? https://github.com/silviomoreto/bootstrap-select/releases/latest
