### ISSUE TITLE
login fails to authenticate - with no error messages.

### ISSUE THREAD

**Issue by watsonrj** [joomla/jissues#644]
Joomla version 3.4.1.
The login (with known credentials) fails (frontend and backend) with no error message.
Records are written in the xxx_user_keys table even when Captcha is turned off.
Everything seems to be correct - the page re-directs to the designated page after the 'failed' login.

I have done much research into this.
I installed a new clean 'one-click' install by softaculous into a sub domain.
[b]The login works.[/b] (for now)

After a lot of comparison between the databases of the new working site and the old working site - including all the cookies/sessions and deleting them for cleaning etc I have found the only difference is that the the old site creates records in the "[b]xxx_user_keys[/b]" table and the new one doesn't.

Both sites have system Captcha disabled - in the new site it was never turned on.
BUT the old site had the Captcha activated and then disabled.
Does this have any bearing? What part of the CMS produces the xxx_user_keys records?

I obviously tried deleting the xxx_user_keys records in the old site - but they were re-made as soon as I tried to log in again.
After the 'failed' login - the site did re-direct to the home page - showing its getting right through the login process successfully.
But no editing icons show in the front end - and no login occurs in the back end - and no error messages appear either.

**Comment by brianteeman** [comment]
Set to "closed" on behalf of @brianteeman by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/644">issues.joomla.org/jtracker/644</a>
