### ISSUE TITLE
Double posts

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#645]
Looks like we have the problem with multiple records for individual issues again in the CMS tracker

**Comment by mbabker** [comment]
The only one I've chased so far is joomla/joomla-cms#6816 and I don't see any record of it getting duplicated via the webhook logs.  But the description uses our template so it seems it was submitted via the app and potentially saved twice (once added by hook and once added by the app).

One way around this would be a unique index on the `#__issues` table as it should enforce at the database level a single record for each issue within a project.

```sql
ALTER TABLE `#__issues` ADD UNIQUE `issue_project_index`(`issue_number`, `project_id`);
```

**Comment by b2z** [comment]
Let's try it?
