### ISSUE TITLE
Again a open / closed issue

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#646]
#### Steps to reproduce the issue

see: http://issues.joomla.org/tracker/joomla-cms/
![screen shot 2015-04-29 at 16 23 38](http://issues.joomla.org/uploads/1/d2ccdd95a75e7031aee3e8ae82c4620a.png)

and: http://issues.joomla.org/tracker/joomla-cms/6834
![screen shot 2015-04-29 at 16 23 44](http://issues.joomla.org/uploads/1/0e7e78da70b12d00fc5e244e6ca2ee24.png)

#### Expected result

Closed issues don't shown on the issues list

#### Actual result

The closed issues is shown on the issues list

**Comment by mbabker** [comment]
Gone, will be restored on next cron.

**Comment by zero-24** [comment]
:+1:
