### ISSUE TITLE
Change the link to the diff

### ISSUE THREAD

**Issue by roland-d** [joomla/jissues#650]
#### Steps to reproduce the issue
Open an issue which has code attached and look at the link for the diff, it is shown as:
https://github.com/joomla/joomla-cms/pull/3108.diff however this URL redirects to https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/3108.diff. For CLI use, the latter URL is usable and the former is not. The former gives the following error:
fatal: unrecognized input

when doing curl https://github.com/joomla/joomla-cms/pull/3079.diff | git apply

#### Expected result
Get the real URL to the diff.

#### Actual result
Currently it shows the nice URL rather than the real url.

#### System information (as much as possible)
Windows 8.1
FireFox 37.0.2

**Comment by mbabker** [comment]
That must be a recent change in GitHub because the first URL used to work just fine.

**Comment by roland-d** [comment]
@mbabker I agree, I also think it is a recent change because it used to work in the past. Thanks for the fix.
