### ISSUE TITLE
Date is incorrect for new comment

### ISSUE THREAD

**Issue by roland-d** [joomla/jissues#651]
#### Steps to reproduce the issue
When placing a comment on an issue the date shown is 2015-05-03T10:23:50Z however on refresh the date is shown as 3 May 15.

#### Expected result
Get the correct date as in Day Month Year and I would expect the year to be 4 digits not 2.

#### Actual result
Date is shown in wrong format of 2015-05-03T10:23:50Z.

#### System information (as much as possible)
Windows 8.1
FireFox 37.0.2

**Comment by b2z** [comment]
Fixed. Also added an offset that was introduced by me a long time ago (#304), but not used because of the bug in Twig. It was fixed and now can be used :+1:
