### ISSUE TITLE
Make username linkable to GitHub page

### ISSUE THREAD

**Issue by roland-d** [joomla/jissues#652]
#### Steps to reproduce the issue
Open any issue and the name of the submitter is shown as plain text. It would be nice to link this name to the GitHub user page. Which is always formatted as https://github.com/<username>

#### Expected result
The username linked to the GitHub user page.

#### Actual result
It is a plain text name.

#### System information (as much as possible)
Windows 8.1
FireFox 37.0.2

**Comment by b2z** [comment]
May be we should link to a profile as it is in the issues list?

**Comment by roland-d** [comment]
With all due respect, the issues list profile page has little to no information. So I think the user page on GH is better suited. Personally I use the GH user page more often than the issue list profile page.

**Comment by b2z** [comment]
Makes sense :) Let's change it also in the issues list?

**Comment by roland-d** [comment]
That sounds good to me, I do think we should keep the menu entries but we could link it to the GH pages.

**Comment by mbabker** [comment]
The intent was at one point to grow out that profile to have more "stuff" (http://developer.joomla.org/tracker/roadmap.html has some ideas).  If we're deciding now it has no value, I'd rather us dump the profiles completely versus have unused features.

**Comment by roland-d** [comment]
@mbabker Thanks for joining in. Extending the profile is a good idea as well. Since it is on the roadmap, we can link to the issue profile for now. If at some point in the future these features do not materialize we can always change the link. Perhaps add a link to the GH profile from the profile page?

**Comment by b2z** [comment]
It's already there ;)

пн, 4 мая 2015, 16:06, RolandD <notifications@github.com>:

**Comment by roland-d** [comment]
Wow you are fast @b2z :tongue: Just kidding, I didn't remember it was there. So only thing we need to do then, is create the link from the issue tracker to the profile page on the issue tracker.
