### ISSUE TITLE
Labels event is duplicating

### ISSUE THREAD

**Issue by b2z** [joomla/jissues#655]
I just noticed that labels event is duplicating for some reason. For example in [6893](http://issues.joomla.org/tracker/joomla-cms/6893)

@zero-24 how do you change labels - on the tracker? Just want to replicate and fix it.

**Comment by brianteeman** [comment]
Where is the duplicate? I dont see anything twice

On 5 May 2015 at 14:35, Dmitry Rekun <notifications@github.com> wrote:

> I just noticed that label events are duplicating. For example in 6893
> <http://issues.joomla.org/tracker/joomla-cms/6893>
>
> @zero-24 <https://github.com/zero-24> how do you change the label - on
> the tracker? Just want to replicate and fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/655>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
If you look at the event history on the linked issue (on the issue tracker, not GitHub), you'll see two events adding the `PR-staging` label.

**Comment by brianteeman** [comment]
Ah I see that now. I thought for those ones they were always done by robots

On 5 May 2015 at 14:38, Michael Babker <notifications@github.com> wrote:

> If you look at the event history on the linked issue (on the issue
> tracker, not GitHub), you'll see two events adding the PR-staging label.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/655#issuecomment-99079917>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by b2z** [comment]
Interesting that [here](http://issues.joomla.org/tracker/joomla-cms/6883) and [here](http://issues.joomla.org/tracker/joomla-cms/6877) there are no duplicates... 

@zero-24 are you a robot? :smile:

**Comment by zero-24** [comment]
@b2z 

>@zero-24 how do you change labels - on the tracker? Just want to replicate and fix it.

No i don't have access to the label manangement on jissues (as i have now only `manage` access but no `admin` access ;)). I use github for adding labels and jissues for moving to Pending.

@brianteeman 
>Ah I see that now. I thought for those ones they were always done by robots

No since some time the bot don't run on it see: https://github.com/joomla/jissues/issues/647
The bot didn't add any label and don't move the issue to pending (if it is a PR).
So we now need to do it manually.

>you'll see two events adding the PR-staging label.

Maybe I'm to fast or faster than github together with jissues? :smile: 

The prozess now is:
- edit the issue on issues.joomla.org (set to pending / categorys)
- save
- go to github (sometimes the github page is open bevor so this can be done quite fast)
- add the label(s)

>@zero-24 are you a robot? :smile:

Yes :smile:

**Comment by mbabker** [comment]
I don't have an answer on #647 either as nothing in any of the logs is showing an error being hit after some fixes I made at the end of last week.  It's like the hooks are exiting early for some reason.

**Comment by b2z** [comment]
So after struggling with this issue I have only one solution: to disable "labeled/unlabeled" event from the sync. I will explain why - labels are added with webhooks. Then on sync they are synced one more time, because an issue have "labeled/unlabeled" event in its history of events. So labels get synced on more time.

@mbabker if you have any other suggestions how to prevent this duplicates then I am ready to try them. Otherwise lets remove.

**Comment by mbabker** [comment]
I don't have any better ideas at the moment.  Disable it.
