### ISSUE TITLE
Milestone is removed on jissues but still on github. But i don't remove it?

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#656]
see: http://issues.joomla.org/tracker/joomla-cms/6858 and https://github.com/joomla/joomla-cms/pull/6858

### currect behavior
I'm unable to manage milestones on jissues but jissues removed the milstone.

And the tracker don't updte github too? Something looks wrong?

### expected
if you did not have access to the milestone management nothing should be changed. (not on jissues and not on github)

![milestone-jissues](https://cloud.githubusercontent.com/assets/2596554/7478975/bc63f5e8-f35e-11e4-8b6d-2742f9999cd4.PNG)
![milestone-github](https://cloud.githubusercontent.com/assets/2596554/7478983/c38793b6-f35e-11e4-8936-7a858bf61299.PNG)

**Comment by b2z** [comment]
This is really strange. I've tested this several times - if you have no access to remove milestones then they should not be removed. Need to retest.

**Comment by zero-24** [comment]
>if you have no access to remove milestones then they should not be removed.

Agree but there are 2 points special with my account.
- I have access to the github repo (Collaborator)
- My account is in 2 edit groups (JBS and PLT) on JIssues.

But JBS nor PLT have access to label an milestone manangement on jissues.

So it is really strange that i remove the milestone on jissues (where i have no access) but not on github (where i have access).

My first thought is that somewhere we initial a variable like `$milestone = null` but as i don't have access to the milestone managment we don't set it to the right / current value. And as i have access to edit / manage the issue the still initial `$milestone` variable gets saved and removed the current milestone from jissues?

**Comment by zero-24** [comment]
@b2z it looks like the issue is in the sync script.

example: http://issues.joomla.org/tracker/joomla-cms/6904 / https://github.com/joomla/joomla-cms/pull/6904 I'm only add the label but jissues also remove the milestone on sync.

**Comment by b2z** [comment]
You have added the label on the tracker?

**Comment by zero-24** [comment]
No i have add the label on github.

**Comment by b2z** [comment]
Still can't understand how it happens. The latest changes was only handling of Events - just add them to the activities table, so this code does not touch Issues...

**Comment by zero-24** [comment]
@b2z now I'm totaly confused see:

http://issues.joomla.org/tracker/joomla-cms/6904 &
![milestone](https://cloud.githubusercontent.com/assets/2596554/7517526/d1a7c2b8-f4d5-11e4-932f-1bc07b60535f.JPG)

It looks that every event via hook (here adding a label) send a `remove milestone` message and that only remove the milestone from Jissues but not from github.

But on the sync via cron script the milestone comes back.
You can see at the issue above that the mileston was removed 4 times without adding it back again.

I know there are code for get hook data but i can find it. Can you point me to the right folder / file?

The cron script looks good but it looks for me that the hook script do something unexpected e.g. passing a wrong variable to the tracker etc. Or do I search in the total wrong direction to catch the issue?

**Comment by b2z** [comment]
I am not sure about hooks these were coded by @mbabker, but as far as I know there is no hooks for labeled/milsetoned events
https://developer.github.com/webhooks/#events

> But on the sync via cron script the milestone comes back.

Hmm are you sure? I do not see that http://issues.joomla.org/tracker/joomla-cms/6904 got milestone back.

**Comment by zero-24** [comment]
>Hmm are you sure? I do not see that http://issues.joomla.org/tracker/joomla-cms/6904 got milestone back.

hmm I'm sure that it was there until i have add and remove the `CodeStyle` label for testing.

And bevor this the milestone was removed 3 times.

How often the cron will run? The last i remember is 30 minutes?

But here @mbabker explain it is 5 Minutes? Is this still valid?
>An issue we're hitting is there are cron jobs now running every 5 minutes except for :25 and :55 after the hour to support all of the repositories in the live app.
https://github.com/joomla/jissues/issues/617#issuecomment-73124413

I have just set it back to pending so we have the same state as bevor. And i hope the milestone comes back. :smile:

**Comment by b2z** [comment]
> And i hope the milestone comes back. 

It is not :(

More strange is that I've just tested it locally - I do not have this problem. See https://github.com/jtester/tests/issues/85 and this is how it looks after the sync:

![test](https://cloud.githubusercontent.com/assets/3051676/7530446/38cdd344-f551-11e4-9a63-d6009f01fe9a.png)

Moreover I've synced http://issues.joomla.org/tracker/joomla-cms/6904 and it is also looking good - no duplicates, no unnecessary removes. 

![test](https://cloud.githubusercontent.com/assets/3051676/7530469/8d5f8dd0-f551-11e4-9fb6-88f340e7e9bf.png)

Really I am lost here :( 

@mbabker your suggestions?

**Comment by b2z** [comment]
@zero-24 while we do not have a fix here can you please change labels on the tracker as a temporary solution?

**Comment by b2z** [comment]
So after setting up a test server and webhooks I managed to fix it :) 7445858d That was a silly issue :confused:

**Comment by zero-24** [comment]
Thanks :)
