### ISSUE TITLE
Javascript error data fetching when github password contains "@"

### ISSUE THREAD

**Issue by vinespie** [joomla/jissues#657]
### # Steps to reproduce the issue

1- Click "Options"
2- In field "GitHub Account Password", insert "@"
3- Go to "Joomla! Patch Tester" and fetch data

#### Expected result
Fetching data from github

#### Actual result
Javascript error when fetching

ReferenceError: Joomla is not defined in fetcher.js line 62
jQuery('#patchtester-progress-header').text(Joomla.JText._('COM_PATCHTESTER_FETC...

**Comment by zero-24** [comment]
@vinespie this is the tracke for the issues tracker. The tracker for the patchtester is here: https://github.com/joomla-extensions/patchtester Can you please open a issue there? Thanks :smile:
