### ISSUE TITLE
Regression  of  module mod_login  in  Joomla 3.4.1

### ISSUE THREAD

**Issue by bertyinfos** [joomla/jissues#658]
#### Steps to reproduce the issue

Hello,
New in this forum, sorry if i don'follow stricly the rules !

I performed the update of my website to Joomla version 3.4.1 from version 3.3.6.
and I met a connection module behavior error that worked well so far:

I use the standard login module that, after entering the ID and password, made a redirection to a menu link, which in my case is a registered access menu that I do appear after logging in and disappears after disconnection, with redirection to the home page.

This parameter in the login module with the fields "Redirection after connecting" and "Redirect after logout."

Or the Joomla disconnection does not return to the home page (the one requested) but to a login page:
../index.php?option=com_users&view=login

instead of my menu link on the home page redirection after:
../index.php?option=com_content&view=featured&Itemid= 101

It is an example but other problems happen with this module depending on the way you make a connexion and deconnexion, there are several wrong behaviors. 

After multiple attempts,  I noticed that the redirect parameters don't work well in this version so I was forced to restore  to Joomla 3.3.6 version, which works well.

By going on the forums it seems I am not alone in seeing this problem in version 3.4.1, for example here:
https://github.com/joomla/joomla-cms...mment-86489519

11-05-2015
CORRECTION BYPASS:

Well, I continued to analyze this regression version 3.4.1 and for that I performed the following manipulation:

I went to look in the directory joomla ../modules the folder "mod_login" of Joomla version 3.3.6 , I substituted for that of version 3.4.1 and now I'm found the normal functioning of the connection module ! For me, thus demonstrate that there is indeed a regression on the module in this  version 3.4.1.
In my case here gives me a correction palliative for 3.4.1, but I will still restore to the stable version 3.3.6, pending a formal correction.
Regards
bertyinfos

#### System information (as much as possible)
joomla release 3.4.1
mod-login

**Comment by zero-24** [comment]
@bertyinfos you are in the wrong tracker :smile: please move your report to the CMS issue Tracker here: http://issues.joomla.org/tracker/joomla-cms/

This Tracker is for the Tracker application itself :smile:

**Comment by bertyinfos** [comment]
Ok I don't know the way this forum is working , it was only to inform about what I noticed in Joomla 3.4.1
But I saw my issue is written in the wrong part (ref.zero-24)  and it was passed in a status closed par B2Z.
It was just to inform developpement team  if it could be useful.
I give up because I don't know the running of Github .
Regards

**Comment by zero-24** [comment]
>But I saw my issue is written in the wrong part 

Not the Problem :smile: Just open a new issue here: http://issues.joomla.org/tracker/joomla-cms/add

>It was just to inform developpement team if it could be useful.

We are is very appreciative of your report :smile: 

>I give up because I don't know the running of Github

you don't need to know how github is running just open a issue (like this) here: http://issues.joomla.org/tracker/joomla-cms/add

Thanks for your report.
