### ISSUE TITLE
Mi paguina no aparece en la web

### ISSUE THREAD

**Issue by Maurogom2015** [joomla/jissues#659]
Mi sitio no aparece pero en el Cpanel esta mi cuenta al dia

**Comment by zero-24** [comment]
@Maurogom2015 i guess you use the wrong tracker :smile: this is the tracker for the Joomla Tracker Application. Please use: http://issues.joomla.org/tracker/joomla-cms for CMS Issues and http://forum.joomla.org/ for support requests. Thanks :+1:
