### ISSUE TITLE
Milestone issues again. Sorry

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#661]
Since the fix here: https://github.com/joomla/jissues/issues/656 by @b2z it looks better but now we have a reversed behavior.

The milestone gets removed on github (and it looks i don't get synced):
http://issues.joomla.org/tracker/joomla-cms/6966
https://github.com/joomla/joomla-cms/pull/6966

George added the milestone.
Moving to RTC
Peter added a commit
The bot adds the RTC label
*and*  remove the milestone :cry: 

see:
![milestone_again](https://cloud.githubusercontent.com/assets/2596554/7676505/a5619f72-fd44-11e4-820e-cc845140a114.PNG)
![milestone_again_tracker](https://cloud.githubusercontent.com/assets/2596554/7676506/a562b312-fd44-11e4-8f56-498513049343.PNG)

**Comment by b2z** [comment]
Nasty bot :( 

What bothers me is that the milestone is not synced back. I am testing it now here:
http://jissues.j4devs.ru/tracker/jissues-test/2
https://github.com/b2z/jissues-test/issues/2

You can see that it is synced. I have a cron job running there once per hour, lets see in the next hour will it sync back the removal of the milestone.

P.S.
Still labels are duplicating. But that's the next task for me.

**Comment by b2z** [comment]
Well as you can see [here](http://jissues.j4devs.ru/tracker/jissues-test/2) all is synced :confused: 

@zero-24 can you make a test in the CMS repo - add milestone/remove milestone?
For example here:
https://github.com/joomla/joomla-cms/issues/6859 (Issue)
and here:
https://github.com/joomla/joomla-cms/pull/6968 (Pull request)

Thanks :)

**Comment by zero-24** [comment]
@b2z just added for testing the 4.0 milestone.

**Comment by b2z** [comment]
Yeah thanks. Now we will wait and see what will happen :smile:

**Comment by b2z** [comment]
Well - nothing :disappointed: 

@mbabker is there any problem with the cron job? Also how do you think why nasty *joomla-cms-bot* removed the milestone?

**Comment by mbabker** [comment]
Crons might be hitting limits again or something.  The log file shows a couple of the repos not finishing.  I might need to start writing the raw output from the jobs to the filesystem again.

**Comment by mbabker** [comment]
And in general the crons shouldn't be removing the milestones unless [this line](https://github.com/joomla/jissues/blob/master/cli/Application/Command/Get/Project/Issues.php#L289) has a bug in its logic.

**Comment by b2z** [comment]
> And in general the crons shouldn't be removing the milestones unless this line has a bug in its logic.

Crons should be fine, I've tested several times (see my tests above).

**Comment by b2z** [comment]
> Crons might be hitting limits again or something.

I think we should increase time between them for some projects. For example for JTracker or JTests we might run it every 2 hours or something.

**Comment by mbabker** [comment]
The time won't matter if it's hitting the rate limits.  It'll just cause one hour to not be limited and another will.  If it's another error, catching the output for the cron jobs will help figure out what to do.

**Comment by b2z** [comment]
@mbabker I hope you will fix it ;)

@zero-24 I think you can remove this testing milestone till the cron job will be fixed.

**Comment by zero-24** [comment]
>@zero-24 I think you can remove this testing milestone till the cron job will be fixed.

Done :smile:

**Comment by b2z** [comment]
So @zero-24 we can test again now. I think it should be fixed.

**Comment by zero-24** [comment]
Ok lets try :smile: I have add the 3.4.0 milestone again to 

https://github.com/joomla/joomla-cms/issues/6859
and
https://github.com/joomla/joomla-cms/pull/6968

**Comment by b2z** [comment]
Still nothing... :confused:

**Comment by b2z** [comment]
@mbabker can you look into it please? I have milestones synced normally on my test server. See [this](http://jissues.j4devs.ru/tracker/jissues-test/3) for example. But on the CMS tracker they are not synced. @zero-24 right?
