### ISSUE TITLE
Can't able to register into joomla forum

### ISSUE THREAD

**Issue by jextnsupport** [joomla/jissues#662]
I got a error when registering into a Joomla support is,

You have incorrectly sorted the items to the correct list of the confirmation question.
Your IP 106.51.252.234 has been blocked because it is blacklisted. For details please see http://www.stopforumspam.com/api?ip=106.51.252.234.
An entry on the blacklist may have several reasons:
1. You are a well-known spammer.
2. Last time a well-known spammer was using the dynamic IP address which you got from your ISP (Internet Service Provider), your e-mail address or the username you have choosen.
3. Your ISP is well-known for a lot of spamming customers and is not fighting against spammers enough.

Please give a solution to register into a joomla forum.

Waiting for your response,

**Comment by b2z** [comment]
Hi!

Sorry, but this is a tracker for Joomla! Issue Application. Unfortunately I do not know who you should contact regarding this problem :disappointed:

**Comment by jextnsupport** [comment]
Hi,

Thanks for your reply...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/662">issues.joomla.org/jtracker/662</a>.</sub>
