### ISSUE TITLE
Open / Closed isses again?

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#663]
hmm it is strange but see here: http://issues.joomla.org/tracker/joomla-cms/7095

it has the status `New` but is merged by Thomas as we can see in the history:

![new](https://cloud.githubusercontent.com/assets/2596554/7920901/0a1ec35a-08a2-11e5-9f0d-69193027970b.PNG)
......
![closed](https://cloud.githubusercontent.com/assets/2596554/7920913/15fb96da-08a2-11e5-83d8-1706cc389e6c.PNG)

**Comment by zero-24** [comment]
One more. it looks like we have much PRs that are still open on jissues but closed on github see:
http://issues.joomla.org/tracker/joomla-cms/4645

and
https://github.com/joomla/joomla-cms/pull/4645

We are also unable to edit the issue on jissues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/663">issues.joomla.org/jtracker/663</a>.</sub>

**Comment by onimaro** [comment]
I have the same problem, tested on multiple installations on different servers
