### ISSUE TITLE
Uncessary <filename> Tag for index.html in install.xml

### ISSUE THREAD

**Issue by imanickam** [joomla/jissues#665]
In Joomla, the file index.html is no longer used in the directories.

However, in the file install.xml the following line of code is there.
		<filename>index.html</filename> 

The file install.xml is available in both the directories \administrator\language\en-GB and \language\en-GB.

Since en-GB is native to Joomla and not getting installed just like any other language pack, the issue is not seen.  If someone copies thse file to create a language pack, the language pack installation will fail as there would not be any file named index.html.

Action to be taken:
 Please remove the above mentioned tag from the install.xml files that are available in the directories mentioned.

**Comment by zero-24** [comment]
@imanickam i guess you choose the wrong repo? http://issues.joomla.org/tracker/joomla-cms/7155

If so please close here :smile:
