### ISSUE TITLE
No code attached label if the issue is created on github

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#668]
Hi,

if some one open a issue on github we need to manually add the `No Code Attached Yet` label.

As the code that manage it looks wrong to me?

This trigger the event: https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Hooks/ReceiveIssuesHook.php#L135

```php
$this->triggerEvent('onIssueAfterCreate', $table, array('action' => $action));
```

but we use it only with one argument here:

https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsIssuesListener.php#L32

```php
public function onIssueAfterCreate(Event $event)
```

Is there a reason to pass the action? As we don't use it later. To get the action we use the following code:

```php
		// Pull the arguments array
		$arguments = $event->getArguments();
		// Only perform these events if this is a new issue, action will be 'opened'
		if ($arguments['action'] === 'opened')
		{
```

**Comment by mbabker** [comment]
The trigger is right.  The way the Framework's [Event class](https://github.com/joomla-framework/event/blob/master/src/Event.php) is designed, all of your arguments have to be added through the `addArgument()` method (unless you subclass it and add a "pretty" API for setting arguments) and then within the event listener you have to fetch out your arguments array via the `getArguments()` method.  If you dig into the [triggerEvent() method](https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/AbstractHookController.php#L526) you'll see that we default inject a bunch of arguments into the event and that third argument (the array with the action) allows additional optional arguments for the event based on context.

**Comment by zero-24** [comment]
hmm than it looks correct. Do you have any idea why it fails than?

**Comment by mbabker** [comment]
I've got nothing.  No log messages and the class name is correct for the expectation to register the listener.

**Comment by zero-24** [comment]
@mbabker can we try the following debug code here:
https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsIssuesListener.php#L36

```php
			$logger->info(
				sprintf(
					'onIssueAfterCreate for %s/%s #%d - Action: %s',
					$project->gh_user,
					$project->gh_project,
					$hookData->issue->number,
					$arguments['action']
				)
			);
```

If that is in i can open a issue on github. To be sure we get in and no other "action" than `opened` is set here?
