### ISSUE TITLE
Can we add the markdown link on the editor?

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#669]
Can we add the markdown link on the editor? e.g. like github here:

![markdown](https://cloud.githubusercontent.com/assets/2596554/8280874/52ffa3e6-18e2-11e5-935a-def4215f8dc1.JPG)

Link would be http://issues.joomla.org/markdown

As requested here: https://github.com/joomla/joomla-cms/issues/7240#issuecomment-114069847 by @artur-stepien

**Comment by b2z** [comment]
Is this will be ok?

![2015-07-02_21-32-55](https://cloud.githubusercontent.com/assets/3051676/8484740/00b2afca-2102-11e5-9a64-fa7c00b9dc97.png)

**Comment by artur-stepien** [comment]
Not so obvious for most. Maybe add link as tab after Preview?

**Comment by b2z** [comment]
Like this?
![2015-07-02_21-45-30](https://cloud.githubusercontent.com/assets/3051676/8485054/b0b3aaa4-2103-11e5-8e21-87dc33683e5e.png)

**Comment by artur-stepien** [comment]
Yeah, awesome

**Comment by b2z** [comment]
Does anyone has something against? :wink:

**Comment by artur-stepien** [comment]
You can also try to move it to right and add this markdown icon. So it will be similar to Github comment window. Easier to get used to for most users.

**Comment by b2z** [comment]
Well it is inside `<li>` so pulling to the right is not possible.

**Comment by artur-stepien** [comment]
.pull-right class? :)

**Comment by mbabker** [comment]
Should be able to give the `<li>` element a `pull-right` class (for the tab anyway), I don't know what you can do with the toolbar.

**Comment by artur-stepien** [comment]
I just tried to give float:right on tab from comments window. And it worked nice.

**Comment by b2z** [comment]
Ok, pull-right for li worked. But it looks quite funny on mobile view

![2015-07-02_22-43-17](https://cloud.githubusercontent.com/assets/3051676/8486206/d5753d32-210b-11e5-9465-d01882d9fd98.png)

![2015-07-02_22-42-58](https://cloud.githubusercontent.com/assets/3051676/8486208/d902b3d0-210b-11e5-8079-5c1783f46c53.png)

**Comment by artur-stepien** [comment]
Stil better :) Maybe even better then full width on mobile.

**Comment by zero-24** [comment]
@b2z do we have a `hidden-phone` available?

**Comment by b2z** [comment]
Yeap it is BS2 ;) Do you want to hide on mobile?

**Comment by artur-stepien** [comment]
Probably not. Important information.

**Comment by zero-24** [comment]
>Probably not. Important information.

@artur-stepien if you are one a smartphone?

This is a help, but
all that know the github markdown don't need this,
all that see the page one time or two don't need this and
only users that send the first comment with code on a mobil phone

If we hide on a smartphone we save some space that we can use for the editor. I think.

Why do you what to have this on mobile?

**Comment by artur-stepien** [comment]
This is documentation on the page where markup is not so obvious. And Yes I have a smartphone.

**Comment by b2z** [comment]
So let's leave it on mobile view?

**Comment by artur-stepien** [comment]
If you ask me, yes :)

**Comment by b2z** [comment]
I am asking in general :smile: IMO we can leave it. If more people will complain then we will remove, that's not such a big deal :wink:

**Comment by artur-stepien** [comment]
Yeah. It does not take much space and in my opinion looks good. But what most important it gives the information people will need.

**Comment by elkuku** [comment]
I'd like to see it on my mobile too :)

Artur Stępień <notifications@github.com> schrieb am Di., 7. Juli 2015 09:03:

**Comment by b2z** [comment]
Done b22397d
