### ISSUE TITLE
Create 'All' botton next to 'Open' and 'Closed' button

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/jissues#672]
#### Steps to reproduce the issue
At issues.joomla.org we have some buttons.
Two of them are to make a quick choise (Open and Closed items).
This morning I reported an issue. Of course I checked if the issue was reported already (with the default 'Open' choise). I could not find it, so I reported it.
It was an issue which could be solved with cleaning the browser cache and was reported before (and was Closed).
To avoid this: Can we make a button 'All' next to 'Open' and 'Closed' and make it the default so people who don't use the issues tracker so much (like me) find duplicate issues (and will not report them).

**Comment by elkuku** [comment]
Makes perfect sense.

**Comment by b2z** [comment]
I am not sure that ALL issues should be opened by default. But of course this is IMO :wink: Need some more opinions before we will implement it :tongue:

**Comment by mbabker** [comment]
Just as he suggests, I would make it a third button next to the Open/Closed buttons and keep open as the default selected one.

**Comment by elkuku** [comment]
I was also under the impression that the intent is to make the ALL option
the default since it does mean something like "no filters applied".

Michael Babker <notifications@github.com> schrieb am Do., 2. Juli 2015
13:38:

**Comment by mbabker** [comment]
Oh, reading back ya that's what he's asking.  Personally, I don't think I'd make that the default option but having it as an available option is definitely a :+1: .
