### ISSUE TITLE
Missing link in case $modMenuId

### ISSUE THREAD

**Issue by minonario** [joomla/jissues#674]
Hi,

I got me with the following error in my application after update to version 3.4.3. I go to the menus list and in the column Linked Modules appears Notice: Undefined variable: link in .... /administrator/components/com_menus/views/menus/tmpl/default.php on line 207

When i check after the line 200 I realized that in creating the link to add menu module is the variable $link and is not previously defined, i guess is that the error. My solution was to assign the JRoute to the $link variable before the generation of the link.

Attach an image.

I hope this help you.

Greetings, Jose

![screen shot 2015-07-03 at 9 50 55 pm](https://cloud.githubusercontent.com/assets/10578976/8506102/b4e915d0-21cd-11e5-815b-4b932578735a.png)

**Comment by b2z** [comment]
Merged in CMS :laughing:
