### ISSUE TITLE
Joomla Update check fails silently with allow_url_fopen disabled

### ISSUE THREAD

**Issue by chrullrich** [joomla/jissues#675]
On a fresh installation of a third-party package including Joomla 3.4.1, there is no indication in the control panel of an available update, and Components/Joomla Update even explicltly claims that

    You already have the latest Joomla! version, 3.4.1.

This is clearly wrong, because the latest release is currently 3.4.3.

The PHP configuration on this server disables `allow_url_fopen`. With it enabled, the available update to 3.4.3 is immediately detected and offered for installation.

I'm aware that I'm reporting a bug in an older version, but since it is inherently irreproducible in the current release, I thought I'd do it anyway.

**Comment by zero-24** [comment]
@chrullrich please report it to the CMS issues Tacker. This is the Tracker for the Tracker application ;) Thanks :smile: http://issues.joomla.org/tracker/joomla-cms
