### ISSUE TITLE
JBrowser detect ie 11

### ISSUE THREAD

**Issue by jenyokcoder** [joomla/jissues#679]
jimport('joomla.environment.browser');
$browser = &JBrowser::getInstance();
//view page from msie 10
        $browserType = $browser->getBrowser(); // return msie
        $browserVersion = $browser->getMajor(); // return 10
//view page from msie 11
        $browserType = $browser->getBrowser(); // return firefox
        $browserVersion = $browser->getMajor(); // return 5
/*
this solution for ie 11 (preg_match('|Trident.+rv\:([0-9.]+)|', $this->agent, $version)) !
change string in file "/libraries/joomla/environment/browser.php" and line 271 : 
elseif ((preg_match('|MSIE ([0-9.]+)|', $this->agent, $version)) || (preg_match('|Internet Explorer/([0-9.]+)|', $this->agent, $version))) to
			elseif (
				(preg_match('|MSIE ([0-9.]+)|', $this->agent, $version)) ||
				(preg_match('|Internet Explorer/([0-9.]+)|', $this->agent, $version)) ||
				(preg_match('|Trident.+rv\:([0-9.]+)|', $this->agent, $version))
			)
*/
// result view page from msie 11
        $browserType = $browser->getBrowser(); // return msie
        $browserVersion = $browser->getMajor(); // return 11

**Comment by zero-24** [comment]
@jenyokcoder can you send your changes as pull request against the CMS Repo? This here is the Repo of our custom Tracker application :smile: 

Go here:
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/environment/browser.php

- click the edit button
- change the code
- commit it
- add testinstructions and title etc.

see: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by jenyokcoder** [comment]
thanks @zero-24
