### ISSUE TITLE
Pending or open?

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#699]
see:

![pending_or_not](https://cloud.githubusercontent.com/assets/2596554/9438778/50188976-4a61-11e5-941d-c0a09569aab0.JPG)

The staus is `New` but on the activity line we see that we have moved it to `Pending`? Looks strange to me.

Tracker link: http://issues.joomla.org/tracker/joomla-cms/7760

**Comment by zero-24** [comment]
I have munually moved it to pending now

**Comment by b2z** [comment]
Definitely strange. Can we replicate it somehow?

**Comment by zero-24** [comment]
@bz2 do you have access the the sql error log on the live site? maybe it is only a failed SQL query to update the status on the database?

**Comment by elkuku** [comment]
Another detail is that the status has been moved to "pending" by the OP which doesn't seem to be correct. This is not the first PR that I saw like this, maybe unrelated but also strange ...

**Comment by zero-24** [comment]
@elkuku this is the behavior since we do "auto pending" Pulls. I don't think it is wrong? Maybe we should add our bot as actor?
