### ISSUE TITLE
Feature proposal: Negative filtering

### ISSUE THREAD

**Issue by javigomez** [joomla/jissues#702]
Hi, with @roland-d  we are preparing a Bug Squashing session and we found that it would be awesome for us to have the possiblity to filter issues with a NEGATIVE condition. In particular: `show all issues EXCEPT the ones with tag "no code attached yet"`. 
<img width="348" alt="screen shot 2015-09-04 at 12 17 17" src="https://cloud.githubusercontent.com/assets/1375475/9687086/d311eaee-52fd-11e5-8757-65d4b591155d.png">

Maybe something like github does allowing to select more than one tag at the same time:

<img width="353" alt="screen shot 2015-09-04 at 12 19 30" src="https://cloud.githubusercontent.com/assets/1375475/9687148/2b0e5ef8-52fe-11e5-85b5-528309971557.png">

Thanks :smile:

**Comment by zero-24** [comment]
@javigomez 

`show all issues EXCEPT the ones with tag "no code attached yet". `

This particular is quite simple. Just filter on the status (not label) `Pending`: http://issues.joomla.org/tracker/joomla-cms/?sort=issue&status=3

Thats are all Pull requests that not set RTC, NRW, Information Required ;)

Other way arround is: https://github.com/joomla/joomla-cms/pulls as this shows all Pull Requests.

I'm not sure if we can implement this in a easy way ;) But that is my `no coder` position. Maybe someone has an Idea to implement it. :smile:

**Comment by mbabker** [comment]
Either way, it isn't too terrible.  It's basically turning things into a multi-select, making sure the values get read out of the request correctly, and changing the WHERE clauses of the query from `WHERE tag = 3` to `WHERE tag IN (3)`.

**Comment by elkuku** [comment]
We have a "special" table field `has_code` to differentiate issues from PR, so we might just add a new filter to have a display the GitHub way using `issues` or `pulls` (or both).
We could have a multi select for labels, as @mbabker said.
Or we might just implement both :wink:

**Comment by b2z** [comment]
@javigomez we have #703 now. Is it enough?

**Comment by roland-d** [comment]
For me it works with the type filter although this only works for the difference between issues/PRs and not for the rest of the labels. This already helps me a lot. Thanks.

**Comment by b2z** [comment]
Nice :) But multiselect would be greater for labels, yeah? :)

**Comment by roland-d** [comment]
A multiselect would be more flexible, just don't know how often it will be used. Perhaps leave it as-is and wait to see if more requests come in for it.
