### ISSUE TITLE
Banners do not display if meta word search is active.

### ISSUE THREAD

**Issue by N6REJ** [joomla/jissues#706]
![meta](https://cloud.githubusercontent.com/assets/1850089/10086913/a2b49106-62d6-11e5-846e-c2c37fa8788f.jpg)

**Comment by zero-24** [comment]
@N6REJ can you open that issue against the CMS Repo?

http://issues.joomla.org/tracker/joomla-cms
or
https://github.com/joomla/joomla-cms/issues

This here is the Tracker App not the CMS ;)

**Comment by N6REJ** [comment]
whoops, sorry guys
