### ISSUE TITLE
Type selector not available for translation?

### ISSUE THREAD

**Issue by MAT978** [joomla/jissues#709]
Maybe I missed something but I didn't see the Type Selector (Type - Pull Request - Issue) available for translation on Transifex... to come?
Thanks
![type selector](https://cloud.githubusercontent.com/assets/1972717/10265778/6c8468a8-6a0c-11e5-89ca-f2ad41310fcc.png)

**Comment by b2z** [comment]
Yeah obviously files were not pushed to tx... @mbabker will update I hope ;)

**Comment by MAT978** [comment]
@mbabker ????
NOOOOOOOOO!
don't let him play with his bots... ;)
![111 3](https://cloud.githubusercontent.com/assets/1972717/10280619/6f342922-6b3c-11e5-80c0-b7c6d474c881.jpg)

**Comment by mbabker** [comment]
Happy Monday! :wink:

**Comment by MAT978** [comment]
closed since @mbabker ruined my Monday!

**Comment by elkuku** [comment]
Another :beer: for the bots :wink:
