### ISSUE TITLE
staying on the same screen after submitting a test result

### ISSUE THREAD

**Issue by MATsxm** [joomla/jissues#716]
after submitting a result by clicking "Submit test result", the secreen remains the same and therefore suggests that the submission didn't proceeded.
This must explain the fact that for some tests, we can see 4 results submitted.
thanks
(screenshot is the screen after having submitted a test result)
![sans titre2](https://cloud.githubusercontent.com/assets/1972717/10414127/1c17e90e-6f92-11e5-8d9b-74e4704675b1.png)

**Comment by b2z** [comment]
Agree. What would be the option? Hide `Submit test result` block?

**Comment by MAT978** [comment]
IMHO I guess it would be the best option then we can "see" an action occurred ;)

**Comment by b2z** [comment]
It's already there, but not so visible - above the `Submit test result` button.

**Comment by zero-24** [comment]
Maybe we can enque a message and close the "test this" field?

**Comment by MAT978** [comment]
yup but tbh, the way the <code>Submit test result</code> block stays open is a bit disturbing, and I don't think I'm the only one. If you think it's enough, no prob for me................ now that I know :wink:

**Comment by elkuku** [comment]
> the way the Submit test result block stays open is a bit disturbing, and I don't think I'm the only one.

You are not.

I also think we should simply close the test field after successful submission and display "some notification".

Suggestions, or even better some code, are welcome :wink:

**Comment by zero-24** [comment]
PR is: https://github.com/joomla/jissues/pull/727 Would be cool to get some tests :)
