### ISSUE TITLE
On my mobile Phone the 3. Button "All" dont looks nice

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#717]
On my mobile device the third button dont looks nice. Maybe just a CSS change after we habe the third button?

![wp_ss_20151013_0001](https://cloud.githubusercontent.com/assets/2596554/10450058/fa1f8d18-7197-11e5-9975-4da0fa235066.png)

**Comment by mbabker** [comment]
I'll just be honest.  That button is the least of our mobile layout worries.

**Comment by zero-24** [comment]
Ok
