### ISSUE TITLE
"Has two tests" filter don't understand the "sha"

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#718]
Try to set the filter `Has two tests` on the CMS Tracker and jump into an issue like: http://issues.joomla.org/tracker/joomla-cms/8064 here you see there are no tests (on the last sha) but the filter shows it as `has two tests`. That is wrong for me. I expect to see only that issues that have 2 successfull tests on the lastest sha.

Thanks.

**Comment by b2z** [comment]
This will be magically fixed when your 713 will be tested and merged ;)

**Comment by zero-24** [comment]
Hmm correct. I miss that. Thanks.
