### ISSUE TITLE
Redirect old URI schemes

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#729]
Older URI schemes are still being linked to and indexed.  For those cases, an .htaccess rule should be implemented.  For the other stuff that's just bad routes, not much to do about that.

![screen shot 2015-11-25 at 12 48 24](https://issues.joomla.org/uploads/2/21dca6ba2536987b85c19b6a03eb432d.png)

**Comment by zero-24** [comment]
So what is The plan? Redirect them to The CMS Tracker? or issues.joomla.org? What of them are formaly good routes? They all Looks bad to me?!

**Comment by mbabker** [comment]
`301 /tracker/joomla-cms-3-issues* /tracker/joomla-cms/*` for example

**Comment by b2z** [comment]
@mbabker can you give a list of all this incorrect URLs? And what "Older URI schemes" do you mean?

**Comment by mbabker** [comment]
The two schemes I pointed out above are the common ones (before we renamed the aliases for the CMS & issue tracker to what they are now).  Just fixing those two then letting Google re-index should make the remaining results more usable.

**Comment by b2z** [comment]
Have you tried to apply the rules above to .htaccess? :)

**Comment by mbabker** [comment]
Nope.  I have a hard enough time with .htaccess rules on my own.  I `*THINK*` these might work, but someone who understands .htaccess better than me should verify.

```.htaccess
RewriteRule /tracker/joomla-cms-3-issues^(.*)$ https://issues.joomla.org/tracker/joomla-cms$1 [R=301,L]
RewriteRule /tracker/jtracker-bugs^(.*)$ https://issues.joomla.org/tracker/jtracker$1 [R=301,L]
```

**Comment by b2z** [comment]
Did your commit help?

**Comment by mbabker** [comment]
Well, Search Console isn't giving me any crawl errors right now so I'd say yes.
