### ISSUE TITLE
[issue-fix found alone] Override Module template function modChrome_NAME style="NAME"

### ISSUE THREAD

**Issue by alexonbalangue** [joomla/jissues#731]
i assign other template than default template used
[site]/templates/[tpl-name]/html/module.php
function modChrome_NAME($module, &$params, &$attribs) {
	echo '<.h1.>' . $module->title . '<./h1.>'; 
	echo $module->content;
}
[site]/templates/[tpl-name]/index.php
<jdoc:include type="modules" name="footer8" style="NAME" />

The $module->title function not take charge.
![tpl_custom](https://cloud.githubusercontent.com/assets/6099946/11570289/c64b8d16-99f6-11e5-8fe6-2cb96e76b9f2.PNG)
![tpl_customoutput](https://cloud.githubusercontent.com/assets/6099946/11570290/c64d03b2-99f6-11e5-8976-e130f1dcdefe.PNG)

i also edit config advanced on module not take too.
Found alone just do
[site]/templates/[tpl-name]/html/mod_custom/default.php

add 
defined('_JEXEC') or die;
$headerTag = htmlspecialchars($params->get('header_tag', 'h1'));
if ($module->showtitle) { echo '<' . $headerTag . '>' . $module->title . '</' . $headerTag . '>'; }
echo $module->content;

**Comment by elkuku** [comment]
Hi!

This is the tracker is for the JIssues project.
Please create a new issue on Joomla CMS project tracker here:
https://github.com/joomla/joomla-cms/issues

Thank you!
