### ISSUE TITLE
Menu item published even though set to unpublish

### ISSUE THREAD

**Issue by N6REJ** [joomla/jissues#733]
Very strange behavior in 3.4.5 where if you remove the component assigned to a menu item, and its therefore "unpublished" it still publishes the menu item.  See video for example.

https://www.facebook.com/N6REJ/videos/920954987989247/?l=4005882963949316918

**Comment by brianteeman** [comment]
Wrong tracker - please post at https://issues.joomla.org/tracker/joomla-cms<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/733">issues.joomla.org/jtracker/733</a>.</sub>

**Comment by brianteeman** [comment]
Set to "closed" on behalf of @brianteeman by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/733">issues.joomla.org/jtracker/733</a>
