### ISSUE TITLE
Association articles isn't working on 3.4.5 and 3.4.6

### ISSUE THREAD

**Issue by Gettyk** [joomla/jissues#735]
**Steps to reproduce the issue**
● creating new association:
Open an article without articles in another language associated  with.
Open the association tab in the back-end, navigate and choose the article you want to associated. The title of the chosen article appears in the box as expected (next to the button "Select" and "Clear"). 
Save the article. 

● removing existing association:

**Expected result**
● creating new association:  The two articles should be associated. 
● removing existing association: The existing associations between two articles should be removed

**Actual result**
● creating new association
When the page is reload, open the the association tab and here the title of the associated articles has disappears from the box. 
● removing existing association: two articles which were associated before the update can't be disassociated 

**Additional comments**
Before the update I could associated to articles in different languages (multilingual website) but since I've updated to 3.4.5 I can't. I've update to 3.4.6 thinking it could solve the bug but I still have the bug. 
This is happening on 2 different websites (one was on 3.2 before the update and the other one 3.3.3). 

All the association before the update are working.

**Comment by infograf768** [comment]
From which J version did you update to 3.4.5 ?

**Comment by infograf768** [comment]
oops, just saw it above, sorry

**Comment by infograf768** [comment]
I can't reproduce the issue here.
I guess your updates went wrong.

**Comment by Gettyk** [comment]
Thanks for your reply! Could be but it's weird as this happened on two different websites, and from two different version. I am not sure which way I should go to debug that. As a starting point wouldn't you happen to know which files are used for managing the articles associations? I could compared mine with the one from a fresh install.

**Comment by Gettyk** [comment]
Sorry I made a mistake in the title: I meant 3.4.5 and 3.4.6

**Comment by infograf768** [comment]
Could you first test if you have the same issue for categories and menu items?

**Comment by Gettyk** [comment]
Thanks for your help! Yes both menu items association and categories association work. Fr both, menu items and categories, I can create new association as well as deleting existing ones. So only articles association seems to get the bug.

**Comment by infograf768** [comment]
You may have a corrupted file.
I suggest to upload a full 3.4.6 joomla pack (without the installation folder) overwriting your install.

**Comment by elkuku** [comment]
This belongs to the CMS
https://github.com/joomla/joomla-cms

**Comment by infograf768** [comment]
Or even to the forum :smiley:

**Comment by Gettyk** [comment]
Sorry for the off-topic, and thanks a lot for your help

**Comment by Gettyk** [comment]
I found the bug: I have made an override for this file administrator\components\com_content\views\article\tmpl\edit.php. To fix the bug, I had to create a new override with the new administrator\components\com_content\views\article\tmpl\edit.php from the 3.4.6 joomla fresh install and copy paste the edit from the first override in the new one.

**Comment by infograf768** [comment]
:smiley:
