### ISSUE TITLE
Submitting a Test result doesn't clear the test

### ISSUE THREAD

**Issue by C-Lodder** [joomla/jissues#737]
![issue](https://cloud.githubusercontent.com/assets/2019801/11914641/c918377c-a67d-11e5-90e1-22be5b057a1a.png)

When a test result has been submitted successfully there is no visual feedback to say the test result is successful.

The text should either disappear and success notification show OR maybe the entire test area gets re-minimized with a success message.

**Comment by b2z** [comment]
Hi ;) See #716
