### ISSUE TITLE
Tags works only with a menu

### ISSUE THREAD

**Issue by frigi83** [joomla/jissues#738]
I have found that in my Joomla 3.4.6 (and 3.4.7 too), I can't have only a popular tags module in my homepage. I have to add a tags menu.

Without a menu the link of a tag is like this: www.website.ch/component/tags/tag/1-mytag
If I click on this link with SEO mode and mod rewrite active, it show me a blank page (no error).

With a menu the link is like this: www.website.ch/menuname/1-mytag

**Comment by brianteeman** [comment]
A blank page is a php error in disguise. Please set your error level to
development and see what the error is

**Comment by frigi83** [comment]
Thanks for the tip. The problem is a plugin.

Sorry
