### ISSUE TITLE
(test) php7.0.2 j3.4.8

### ISSUE THREAD

**Issue by alexonbalangue** [joomla/jissues#742]
Fatal error: Cannot use Joomla\String\String as String because 'String' is a special class name in C:\SERVER\libraries\vendor\joomla\registry\src\Format\Json.php on line 12

**Comment by mbabker** [comment]
No CMS release before Joomla 3.5 will run correctly on PHP 7.  This is a known and fixed issue in that project.

**Comment by alexonbalangue** [comment]
ok

**Comment by alexonbalangue** [comment]
ok
