### ISSUE TITLE
Upload server information

### ISSUE THREAD

**Issue by wilsonge** [joomla/jissues#744]
At the moment we ask for relevent server information. Since 3.5 we now have an export feature (
![image](https://cloud.githubusercontent.com/assets/1986000/13035259/04c36278-d343-11e5-9aae-0f7230868ff5.png) ) can we add support for just uploading that config into jissues please?

**Comment by b2z** [comment]
I think so. Should we support other file extensions like pdf, docx etc?
https://github.com/blog/2061-attach-files-to-comments

**Comment by wilsonge** [comment]
It depends how you wanna render them. pdf.js is only GPLv3 and higher for example... :(

**Comment by brianteeman** [comment]
That's not necessarily a problem as long as it is used on jissues and not
in the cms itself

**Comment by wilsonge** [comment]
Edited comment above for clarity - although I think Brian's point still stands...

**Comment by mbabker** [comment]
We don't have to support rendering them though.  Just use "normal" browser behaviors for text file types like that (link it and let the user/browser decide to open in browser, download file, etc.).  With images there's an expectation to render them inline, files not so much.

**Comment by wilsonge** [comment]
Fine. Although doing some kind of export treatment for the Joomla server info would be nice - so people can see it as part of the issue 'automagically'

**Comment by mbabker** [comment]
If you really wanted to inline the data you could tell people to upload the JSON file and our code could read that and spit out "human friendly" text.  But honestly I don't see it being mandatory to do that as long as the data gets uploaded/attached to an issue in any form.

**Comment by wilsonge** [comment]
I don't think it should be mandatory. But it be an option.... I think there's a decent number of bug reports where users don't know what server info to upload

**Comment by mbabker** [comment]
To an extent, I agree.  But ultimately, the tracker's comment fields shouldn't be doing too much beyond what GitHub offers (all our extra functionality is around features GitHub doesn't have).  This borderline crosses into "we're doing something that the user cannot do on GitHub" if we start manipulating comment text based on file uploads matching certain criteria.  Support file uploads the same way GitHub does, +1 all day every day.  Magically take a JSON or TXT file exported from Joomla, uploaded through the regular file processor, and spit it into the user's input field?  I wouldn't encourage it.

**Comment by brianteeman** [comment]
Def more useful for the forum than for the tracker

**Comment by b2z** [comment]
Please test #744
