### ISSUE TITLE
MP4 files not supported

### ISSUE THREAD

**Issue by Werner6** [joomla/jissues#745]
#### Steps to reproduce the issue
Whereas mp4-files where supported in 3.4.8, the following messages appears with 3.5: Video-Format or mime-type not supported.
Example: https://herzschule.eu/herzschule-i-d-medien/video-herzinfarkt-herzschule.html

#### Expected result
Video should work

#### Actual result
Following message appears: 3.5: Video-Format or mime-type not supported.

#### System information (as much as possible)
Einstellung 	Wert
 
PHP erstellt für 	Linux dd2336 3.13.0-76-generic #120-Ubuntu SMP Mon Jan 18 15:59:10 UTC 2016 x86_64
Datenbankversion 	5.6.27-nmm1-log
Datenbankzeichensatz 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP-Version 	7.0.2-nmm1
Webserver 	Apache
PHP-Interface für den Webserver 	fpm-fcgi
Joomla!-Version 	Joomla! 3.5.0-beta2 Beta [ Ember ] 27-January-2017 23:00 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by brianteeman** [comment]
This is the issue tracker for the issue tracker - please report here https://issues.joomla.org/tracker/joomla-cms

**Comment by Werner6** [comment]
thanks, that’s where I reported it. I give up...
