### ISSUE TITLE
issue navigation #602

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#752]
thanks for applying this as it will be really useful
Just one problem. It just goes to the next/previous ID when it should imho go to the next/previous OPEN issue

**Comment by mbabker** [comment]
Well, it's not all that smart.  In theory you'd actually want it to follow whatever filter(s) you're using on the list view for the most optimal experience.  The best I could probably suggest with it is the pager is based on the issue's state (if open, page to open items; if closed, page to closed items).
