### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#758]
Lots of these messages in the PHP error log:

Trying to get property of non-object in /src/App/Tracker/Controller/Issue/Item.php on line 78

**Comment by b2z** [comment]
Hmm...
```
if ($item->commits)
{
	$commits = json_decode($item->commits);
	$lastCommit = end($commits);
	$sha = $lastCommit->sha; // this line throws an error
}
```
Possible check for object could work, but why `$lastCommit = end($commits);` does not give an object all the time. That's interesting.

**Comment by mbabker** [comment]
Maybe change to `if (!empty($item->commits)) { //... }`?

**Comment by b2z** [comment]
This will work, I just wonder why `if ($item->commits)` does not work - when not empty string is not a proper JSON string that gives us an error,

**Comment by mbabker** [comment]
Guess it would depend on whether it's actually an empty value or something
filled with white space characters which would invalidate things.

**Comment by b2z** [comment]
Then make it `if (!empty($item->commits))` and lets close it for now :)

**Comment by b2z** [comment]
Finally we solved it? :)

**Comment by mbabker** [comment]
Looks like it.  No new errors in the last 2 days.

**Comment by elkuku** [comment]
Could it be that this happens on issues that haven't been updated?
A db dump would help...
Anyway... `666 - Bad Coder Error` :(

**Comment by mbabker** [comment]
No idea honestly.  If it's supposed to trigger when the commits column isn't empty, then we have rows with what looks to be empty data but actually has some kind of empty character in it.  I do see a few pull requests where the commits column is completely empty and a few others where the value is `[]`.  Either way I ain't got a clue but the error isn't triggering anymore.
