### ISSUE TITLE
Optimize Page Loading

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#764]
We've got some "heavy" pages and a lot of assets getting loaded, even with the compiled production stuff.  Let's try to optimize a bit.

These screenshots may not be totally fair to the everyday user, generally I leave browser caching off, but it's a good way to gauge the affect of needing to download all the things.

Tracker listing page:
![screen shot 2016-03-21 at 12 30 48 pm](https://cloud.githubusercontent.com/assets/368545/13925996/d6d8e1c8-ef60-11e5-94b2-2746a628d5f7.png)

Single issue view (CMS 9504):
![screen shot 2016-03-21 at 12 33 37 pm](https://cloud.githubusercontent.com/assets/368545/13926101/3b134002-ef61-11e5-9f06-72c697c84173.png)
![screen shot 2016-03-21 at 12 34 39 pm](https://cloud.githubusercontent.com/assets/368545/13926123/55c98d7a-ef61-11e5-9d58-2f127be7af55.png)

Projects list page:
![screen shot 2016-03-21 at 12 35 37 pm](https://cloud.githubusercontent.com/assets/368545/13926162/82c3f464-ef61-11e5-8660-675f80f79c41.png)

**Comment by b2z** [comment]
Do you think this is actual as we have HTTP/2 almost the standard de facto?

**Comment by mbabker** [comment]
AFAIK Joomla's hosting servers aren't supporting HTTP/2 right now.  Even if they do there are still ways we could optimize things (could we use SVG's for the flags instead of separate GIF's that cause 18 additional resource loads per page?).  Some of it's going to be in optimizing the media resources and some of it's going to be in optimizing the PHP code base.

**Comment by mbabker** [comment]
This is in better shape for now.
