### ISSUE TITLE
Joomla 3.5: Problems with hits counter

### ISSUE THREAD

**Issue by Wojtek98** [joomla/jissues#768]
#### Steps to reproduce the issue

If you have webpage with restricted access hits counter for articles does not increase.

#### Expected result

Hits counter should also increment if you have webpage for registered users only.

#### Actual result

If you have webpage with restricted access hits counter for articles does not increase.

#### System information (as much as possible)

Joomla 3.5

#### Additional comments

I checked this problem and my analysis is below

The root of problem is in the file:
/components/com_content/controller.php

lines 72-76:
		
if ($user->get('id')
			|| ($this->input->getMethod() == 'POST'
			&& (($vName == 'category' && $this->input->get('layout') != 'blog') || $vName == 'archive' )))
		{
			$cachable = false;
		} 

These lines sets cachable to false in some cases, also when you are logged user. For this reason the condition in the line 104 is not fulfilled and hits are not added.

		if ($vName == 'article' && $cachable)
		{
			// Get/Create the model
			if ($model = $this->getModel($vName))
			{
				$model->hit();
			}
		}

**Comment by brianteeman** [comment]
Hi - you have reported this on the wrong issue tracker - this is the tracker for the issue tracker itself.

BUT
This has already been reported (i think) please see https://issues.joomla.org/tracker/joomla-cms/9563

**Comment by Wojtek98** [comment]
Ok, I just registered. Shall I do something with it now?


W dniu 2016-03-25 12:44, Brian Teeman napisał(a):

**Comment by brianteeman** [comment]
Its ok - someone will close this here - but please check the link I gave to ensure it is in fact the same issue

**Comment by Wojtek98** [comment]
i've checked, yes, it's the same problem. I will not submit it again.

W dniu 2016-03-25 12:47, Brian Teeman napisał(a):
