### ISSUE TITLE
About the confusing Voting feature

### ISSUE THREAD

**Issue by MATsxm** [joomla/jissues#773]
Bonjour,
Today, someone began to communicate about a new feature request on the issue tracker, asking people to vote for his request via the "Voting feature". To his point of view, more votes would imply the request will be more taken into account.
IMHO, we should answer the question with more precisions: does the voting feature is a popularity feature or one in relation with the priority (see https://docs.joomla.org/Bug_and_Issue_Tracker_Priority) ?
 
Anyway, I think we should explain it a bit more because it seems unclear for many. Perhaps a tooltips would be sufficient. 
Thoughts?

Thanks

**Comment by brianteeman** [comment]
Popularity was the intention of the vote

On 1 April 2016 at 16:32, Marc-Antoine Thevenet <notifications@github.com>
wrote:

> Bonjour,
> Today, someone began to communicate about a new feature request on the
> issue tracker, asking people to vote for his request via the "Voting
> feature". To his point of view, more votes would imply the request will be
> more taken into account.
> IMHO, we should answer the question with more precisions: does the voting
> feature is a popularity feature or one in relation with the priority (see
> https://docs.joomla.org/Bug_and_Issue_Tracker_Priority) ?
>
> Anyway, I think we should explain it a bit more because it seems unclear
> for many. Perhaps a tooltips would be sufficient.
> Thoughts?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/773>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
It was designed pretty much as a copy of PHP's own voting mechanism on their tracker (https://bugs.php.net/bug.php?id=71941).  Honestly I'm not sure if anyone even does anything with the data.

It's not designed to replace the issue priority field.  It's basically a way for users to :+1: an issue with a score (1-5, low to high) of how important (important being whatever the user defines it to be).

**Comment by MATsxm** [comment]
Ok then let's say that the first question is solved: it's a popularity vote!

then now, this doesn't fix the way that some understand it as Popularity and other as Priority then I would say, this is not clear enough explained.

Also, if it is concidered as a Popularity vote then what.... what to do with? Does mods have permissions to check this "popularity"? are there differences in treatment on the basis of this popularity?
TBH I'm a bit lost about this, but maybe it's just me ;)

**Comment by mbabker** [comment]
It's seriously just a popularity vote, nothing more, nothing less.  If someone votes on an issue, total (aggregate) data is displayed for everyone to view, see https://issues.joomla.org/tracker/joomla-cms/9687 as an example.
