### ISSUE TITLE
Option `View mode` don't look as nice as bevor

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#774]
#### Steps to reproduce the issue

On the issue submit screen we have the option `View mode`
#### Expected result

the Option looks nice
#### Actual result

![view_mode](https://cloud.githubusercontent.com/assets/2596554/14394947/24100300-fdcf-11e5-8a0a-041b40c581df.JPG)

**Comment by mbabker** [comment]
Unless I screwed up implementing something when updating [bootstrap-switch](http://www.bootstrap-switch.org/) to the current version I can't figure out why it's not working right.  When I was debugging the JavaScript that manipulates the switch when the page is loading is targeting what I think is the wrong element to calculate the sizes (specifically one of the inner spans), but that's as far as I got with it.

**Comment by Sandra97** [comment]
It contains too small widths causing a display issue
Hard for me to explain for me how to solve it.
If you replace all the widths of this part, the display will be ok
Currently we have: 84px / 56px / 28px and margin of -28px and 28px
If we could have: 120px / 80px / 40px and margin of -40px and 40px

**Comment by Sandra97** [comment]
With my sizes: 
![joomla cms - new item 2016-06-22 18-46-12](https://cloud.githubusercontent.com/assets/4682328/16286309/a418dae4-38a9-11e6-9b3f-1d42f8cfeb15.png)

**Comment by mbabker** [comment]
Part of the problem is it's all converted/computed by the bootstrap-switch JavaScript.  It converts [this line](https://github.com/joomla/jissues/blob/master/templates/tracker/issue.add.twig#L45) into its "fancy" display on page load.  So we've either got some kind of conflict between third party assets or found a bug in bootstrap-switch.

**Comment by zero-24** [comment]
I have fond something interesting:
http://bootstrapswitch.com/options.html

And there the `data-size` attribute saddly it don't work if I just change it using the console can you try the values `'normal'` & `'large'` maybe it helps :crossed_fingers:

**Comment by zero-24** [comment]
did this data-size thing work?
