### ISSUE TITLE
Two Tests logic bug

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#775]
In the filters is an option called Tests which should allow me to filter by issues that match but there is a logic bug somewhere in the following scenario.

1. Create a New pull request
2. Someone tests it (thats test one)
3. Update the pull request (that resets all tests)
4. Someone tests it (that should be test one)

But the filter will select this issue only when the option is set to Two tests

**Comment by zero-24** [comment]
Yes this is a logical bug. The problem is that we don't realy reset the tests.if you add a commit the sha gets changed. And for the UI we try to get tests for the sha we currently have on that pull request. The dropdown don't care about the sha and show / count all tests.

**Comment by mbabker** [comment]
I think I figured out this one.  I added a WHERE clause on the query to limit the test table results to those where either the SHA is null (legacy behavior before it was tracked this way) or matching the current PR commit SHA.  If someone could verify...

**Comment by zero-24** [comment]
Hmm maybe a different issue but we have also two failed tests in that list now https://issues.joomla.org/tracker/joomla-cms/11395

Do you want me to open a new issue for that?

Any other looks good. Thanks Michael :+1:

**Comment by mbabker** [comment]
Depends on the filter you use.  The one for "Needs Tests" doesn't filter on successful tests, the other two do.

**Comment by mbabker** [comment]
I tweaked it a little more, now give it a run.

**Comment by zero-24** [comment]
Works for me. Thanks :+1:
