### ISSUE TITLE
Error displaying the error page: Application Instantiation Error: Failed to start the session

### ISSUE THREAD

**Issue by ninad1987** [joomla/jissues#778]
#### Steps to reproduce the issue
Joomla Update to 3.5.1
PHP 7
Hit the home page of the site.

#### Expected result
Error displaying the error page: Application Instantiation Error: Failed to start the session

#### Actual result
Display the home page

#### System information (as much as possible)
PHP 7. Joomla 3.5.1

#### Additional comments
Done Database test with core PHP. Works fine. Configuration is fine.

**Comment by brianteeman** [comment]
This is almost certainly something specific with your site - probably an extension. Please use the forum for support http://forum.joomla.org

**Comment by ninad1987** [comment]
The site is working on localhost. Just transferred it to server.

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org
