### ISSUE TITLE
Feeling Lucky - or not

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#780]
Havent used it for  while but today the feeling lucky button always returned the exact same item. Tried it about 5 different times before I recorded this video.

![screen shot 2016-04-25 at 14 40 28](https://issues.joomla.org/uploads/2/715a288ac8db09b31f5d8a94732c43c9.gif)

**Comment by brianteeman** [comment]
And whatever was causing this behaviour has now stopped - weird<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/780">issues.joomla.org/jtracker/780</a>.</sub>

**Comment by mbabker** [comment]
Unless there's something being cached somewhere, you'd think your luck wouldn't be so bad...

https://github.com/joomla/jissues/blob/master/src/App/Tracker/Model/IssueModel.php#L368

**Comment by brianteeman** [comment]
Must have been some sort of cache somewhere

On 25 April 2016 at 21:07, Michael Babker <notifications@github.com> wrote:

> Unless there's something being cached somewhere, you'd think your luck
> wouldn't be so bad...
>
>
> https://github.com/joomla/jissues/blob/master/src/App/Tracker/Model/IssueModel.php#L368
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/780#issuecomment-214503746>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
So something's definitely getting cached somewhere because I just hit the button three times and hit the same issue.  We should probably add a filter to that query so it excludes the issue you're already viewing if you're on an issue page at least.

**Comment by brianteeman** [comment]
That filter would be just a band aid though - it wouldnt address the root
cause that there is something being cached that you are not currently aware
of

**Comment by mbabker** [comment]
Well, yes and no.  Maybe there is no cache and the query just so happens to return the same result for whatever reason, or maybe MySQL is caching results since it's not something on the PHP side.  Feeding an additional filter into the query makes it less likely to hit that cache if it is existing, and if it isn't there then it's just a good guarantee you don't hit the same result again.

**Comment by zero-24** [comment]
hmm strang. This does not fix the complete issue :smile: 

https://issues.joomla.org/
--> Feeling Lucky
=> 8437
--> Feeling Lucky
=> 11976
--> Feeling Lucky
=> 11976
--> Feeling Lucky
=> 11976
--> Feeling Lucky
=> 11976
...

Or is the code not live yet?

**Comment by mbabker** [comment]
I think it's just you 😜 

Just tried it 5 times and got 5 different items.

**Comment by mbabker** [comment]
Check your browser and see if the request for `https://issues.joomla.org/tracker/joomla-cms/random` is getting cached.  That might be your issue.

**Comment by zero-24** [comment]
Correct. If i disable caching it works. Thanks! :+1:

**Comment by mbabker** [comment]
The code's issuing a no-cache directive now too.  There might be a few other places we need to do that.
