### ISSUE TITLE
GitHub and Tracker don't agree on issue state

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#784]
Trying to close items in the tracker is causing issues with GitHub's API somehow.  Specifically these two items having issues:

https://issues.joomla.org/tracker/joomla-cms/8507 (Closes and re-opens)
https://issues.joomla.org/tracker/joomla-cms/10214 (GitHub API giving a HTTP 422 response)

**Comment by zero-24** [comment]
hmm on such issues i have just one idea. Could the job (every 15 min i guess) and the human interaction crash?
