### ISSUE TITLE
Any Value in the Reactions API

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#785]
https://developer.github.com/changes/2016-05-12-reactions-api-preview/

Any possible value to us for using it for anything?

**Comment by brianteeman** [comment]
not really although I guess it could be used instead of the Votes section
which no one really uses

On 12 May 2016 at 21:15, Michael Babker <notifications@github.com> wrote:

> https://developer.github.com/changes/2016-05-12-reactions-api-preview/
>
> Any possible value to us for using it for anything?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/issues/785>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
That's kind of what I was thinking too since Reactions became available.  That module is really tracker specific and not heavily used (FWIW it was based on the PHP bug tracker's vote system), it could be expanded/replaced with reactions and we just sync those for the base issue/PR as appropriate.

**Comment by mbabker** [comment]
The Reactions API is still in beta, any thoughts on using it to phase out the voting module?

**Comment by mbabker** [comment]
Closing, no time myself and seems to be no interest.
