### ISSUE TITLE
Translations - Use Crowdin?

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#787]
Joomla has started using Crowdin for its translation projects - https://crowdin.com/projects/Joomla

Granted, this happened only very recently while we've been using Transifex for years, there have been a couple recommendations for moving to Crowdin.

From my own perspective getting things set up for the patch tester and evaluating tools, things I see as advantages are:

- Import existing translations, so we won't lose anything
- Puts our resources on "project property" (everything Joomla translation is in one spot)
- A [maintained PHP API](https://github.com/akeneo/php-crowdin-api) as well as a [CLI client](https://github.com/crowdin/crowdin-cli) (whereas 4 years after I started it I still have the only Transifex PHP library)

Migrating basically means:

- Writing replacements for the `get transifex` and `update transifex` CLI commands to work with Crowdin
- Setting up the project on Crowdin

Thoughts?

**Comment by MATsxm** [comment]
Should I add a + :100: ?

Not being a dev myself, I am unable to, and I don't want to talk about the pros and cons of a tool rather than another from a developer point of view.
 
However, working everyday on many different t9n platforms and managing different l10n projects, I can certify that today (things changes quickly in this matter), Crowdin is far ahead the other tools from a translator point of view.

The translators' work is easier with also features that improves the quality of the translations. For example, the Crowdin voting system (also used on Twitter Translation Center) allows a genuine exchanges and collaborative work following the Joomla! spirit. In addition, the features offered for project managers allow a better QA/QC than other platforms do today.
 
Finally, and this may be of interesting for devs, Crowdin is a company that wants to work with J! and move forward with accessible and highly responsive support.

**Comment by mbabker** [comment]
Copying in relevant comments from @elkuku on the import/export stuff:

## Lost in transition

The "percentage completed" values are different on Transifex and Crowdin. I did a quick check on some language files and it seems that Crowdin calculates the "completed" value based on the untranslated **words** while Transifex uses **strings**.

Anyway, I believe that all translations should be checked carefully for every language by the respective translators, just to ensure that we do not loose some precious work.

Crowdin does not seem to support po file header informational comments which are supported (and updated) by Transifex. See:

![2016-06-14-095426_1366x768_scrot](https://cloud.githubusercontent.com/assets/33978/16048963/9d754784-321b-11e6-839d-28230ee3b13e.png)

This information is used by our script to generate a list of translators which is included in the [credits file](https://github.com/joomla/jissues/blob/master/Documentation/Development/Dependencies.md#translators). So this wont work anymore.

===========

I've imported all existing translations into the Crowdin project at https://crowdin.com/project/joomla-official-sites so at this point it should be a matter of validating everything transferred over correctly.

We also should try to ping Crowdin to see if there's a way they can expose some of the translator data (at a minimum the headers perhaps or maybe attach some info to an API call) so that all does not get completely lost.

**Comment by mbabker** [comment]
So good news is I was given info that allows us to pull a report from the API to get contributor info.  Bad news is that API serves an Excel spreadsheet [like this one right here](https://github.com/joomla/jissues/files/379072/contribs.xlsx).

**Comment by elkuku** [comment]
What the *
I wonder who paid for that feature...

Not sure if its worth the effort bringing one of those php excel readers in :(

**Comment by brianteeman** [comment]
It's not as hard as you might think. I did it which is proof of that

**Comment by elkuku** [comment]
Happy to see a PR :tongue:

**Comment by brianteeman** [comment]
If this was Joomla and not far!work I would give it a go :)

**Comment by elkuku** [comment]
Actually it **is** Joomla! (~5.0), so no excuse here :wink:

**Comment by brianteeman** [comment]
In your dreams perhaps

**Comment by MATsxm** [comment]
@elkuku no Free Open Source projects are paying for using Crowdin and as translators point of view (those who are using the more the platform) Crowdin is far ahead (with the Twitter client system) than the 20 platforms I have to deal with every day. 
Not perfect, each ones gave + and -, but far, far ahead.

**Comment by elkuku** [comment]
No offence please (anyone) I just wondered about that "strange" file format (I'd suspect that's because of a client request but this is no more than speculation of course).....

**Comment by elkuku** [comment]
I think we "solved" this.
