### ISSUE TITLE
Closed issue

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#788]
Error when editing category of a closed issue.
#### Steps to reproduce the issue

Try to add a category on a closed issue with no categories
#### Expected result

Category applied

**Comment by brianteeman** [comment]
422 RuntimeException

Invalid response from GitHub

exception: exception 'JTracker\Github\Exception\GithubException' with message 'Validation Failed' in ROOT/src/JTracker/Github/GithubObject.php:49
Stack trace:
#0 ROOT/src/JTracker/Github/Package/Issues.php(156): JTracker\GitHub\GithubObject->processResponse(Object(Joomla\Http\Response))
#1 ROOT/src/App/Tracker/Controller/Issue/Save.php(415): JTracker\Github\Package\Issues->edit('joomla', 'joomla-cms', 10470, 'open', '[plg_content_jo...', '### Summary of ...', NULL, '12', Array)
#2 ROOT/src/App/Tracker/Controller/Issue/Save.php(152): App\Tracker\Controller\Issue\Save->updateGitHub('10470', Array, 'closed', 'closed', NULL, '12', Array)
#3 ROOT/src/JTracker/Application.php(190): App\Tracker\Controller\Issue\Save->execute()
#4 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#5 ROOT/www/index.php(37): Joomla\Application\AbstractWebApplication->execute()
#6 {main}

Next exception 'RuntimeException' with message 'Invalid response from GitHub' in ROOT/src/App/Tracker/Controller/Issue/Save.php:173
Stack trace:
#0 ROOT/src/JTracker/Application.php(190): App\Tracker\Controller\Issue\Save->execute()
#1 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#2 ROOT/www/index.php(37): Joomla\Application\AbstractWebApplication->execute()
#3 {main}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/788">issues.joomla.org/jtracker/788</a>.</sub>

**Comment by b2z** [comment]
That's something specific for this issue only. API says:

Sending invalid fields will result in a 422 Unprocessable Entity response.

```
HTTP/1.1 422 Unprocessable Entity
Content-Length: 149

{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Issue",
      "field": "title",
      "code": "missing_field"
    }
  ]
}
```

@mbabker any more info in logs?

**Comment by brianteeman** [comment]
It has happens with EVERY issue that doesnt have a category when you try to add a category and it is closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/788">issues.joomla.org/jtracker/788</a>.</sub>

**Comment by b2z** [comment]
Ok, just tried on [11212](https://issues.joomla.org/tracker/joomla-cms/11212) - no bug. But for 11210 - same `422 RuntimeException`...

**Comment by zero-24** [comment]
maybe there is something missing in the database for 11210?

**Comment by b2z** [comment]
The only difference I see between these two issues is a milestone: 11212 does not have it, but 11210 has it. BTW 10470 also has it (that's where Brian had issue).

**Comment by brianteeman** [comment]
If you remove the milestone does it work ?

(Sent from a bar or I would check)

**Comment by b2z** [comment]
When I try to remove milestone I have the same `422 error`. And I have no rights to remove it on GitHub :) I tried on 10470.

**Comment by zero-24** [comment]
If you tryed on the CMS tracker it should not a permission issue as your tasks run in the context of the joomla bots ;)

**Comment by b2z** [comment]
@zero-24 I know but I have `422 error` :(
