### ISSUE TITLE
Has two tests?

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#790]
#### Steps to reproduce the issue
Use the advanced search to show items with two test and you will see this PR listed
https://issues.joomla.org/tracker/joomla-cms/9964

#### Expected result
It will have two tests and the testers names displayed at the top

#### Actual result
It shows no tests

#### Non-code explanation
There were two tests in the past but they were (correctly) reset when an update was made to the PR. But the filter doesnt recognised the reset

**Comment by zero-24** [comment]
Similiar to: https://github.com/joomla/jissues/issues/775 i guess.

**Comment by brianteeman** [comment]
Lol I reported it twice
