### ISSUE TITLE
Travis failure

### ISSUE THREAD

**Issue by elkuku** [joomla/jissues#793]
Currently the Travis build for PHP 5.4 is failing because of a package that requires (and uses) PHP >= 5.5
See: https://travis-ci.org/joomla/jissues/jobs/137112864

I'd suggest we raise our minimum to 5.5 and remove the Travis tests for 5.4 (and maybe include 7...)

**Comment by mbabker** [comment]
👍 from me

We can't go beyond that right now.  The live server is a PHP 5.5 install and requires a replacement to be upgraded past that.
