### ISSUE TITLE
cannot install joomla using docker

### ISSUE THREAD

**Issue by xhallix** [joomla/jissues#794]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.

#### Steps to reproduce the issue
https://hub.docker.com/_/joomla/
Follow the instructions
Use docker-compose up -d 

#### Expected result
Installation works

#### Actual result
Install step 2 breaks because ```throw new RuntimeException('Could not connect to MySQL'); ```in `driver/msqli.php` 

#### System information (as much as possible)
Ubuntu 14.04 lts

#### Additional comments
MysqlContainer is running and I can connect with root | example by exec into the docker container or using a query browser like mysqlworkbench

**Comment by mbabker** [comment]
This should be submitted against the Docker repository, not the repository for the issue tracker application.

https://github.com/joomla/docker-joomla

Also for reference I don't have a working environment to test against Docker with at the moment so I honestly can't debug the issue if it's something with the Joomla Docker images.

**Comment by xhallix** [comment]
thanks for the hint :)
