### ISSUE TITLE
Issue with the display of the Help & Pro BTN

### ISSUE THREAD

**Issue by MATsxm** [joomla/jissues#805]
#### Steps to reproduce the issue
Try to edit a new item.

#### Expected result
Help & Pro BTN should display the right way (AFAIR, should be a toggle or something like this)

#### Actual result
See screenshot
![screenshot-issues joomla org 2016-06-22 18-16-00](https://cloud.githubusercontent.com/assets/1972717/16285817/68c56d70-38a6-11e6-8c84-2c79d08d8484.png)

#### System information (as much as possible)
Last version Google Chrome + Yandex + FF

#### Additional comments
Seems there's an issue with the bootstrap-switch which contains wrong width causing a display issue

**Comment by mbabker** [comment]
See https://github.com/joomla/jissues/issues/774 😉

**Comment by MATsxm** [comment]
Oooops
I have to improve my search skills :stuck_out_tongue:
