### ISSUE TITLE
Loosing the selected language when a page is loaded

### ISSUE THREAD

**Issue by MATsxm** [joomla/jissues#806]
Each time the page is reloaded, you loose the current selected language

#### Steps to reproduce the issue
Select any language (example: french) then any menu or action (example in french: `Projet` -> `Montrer`) then the page will be loaded in en-GB adn have to select fr-FR again to display the french version

#### Expected result
Stay in the language selected

#### Note to @mbabker 
Thank you to say 

> NO

**Comment by elkuku** [comment]
Just to ensure that I'm on the right track. Can you confirm the following:

1. You are logged in.
1. You have set a language in you user settings (in jissues)
1. This language is different from the one you are selecting using the language selector.

If all those are "yes" then this is indeed a bug that would happen only to "power users" :wink: 

I was wondering how changing the flag images would cause this change in behaviour ...

**Comment by MATsxm** [comment]
ok... :100:% my bad @elkuku 
I had totally forgotten that my User setting were on en-GB.
I tested it (same process) with user settings on :fr: and all is fine.
Thanks

**Comment by elkuku** [comment]
Well, while I think that this should only happen when you are "testing" language stuff, I do agree that there **is** a bug - See &rArr; #808 :wink:
