### ISSUE TITLE
CLI Logger Not Working?

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#814]
It looks like I broke the `--log` option for CLI with https://github.com/joomla/jissues/pull/767 as nothing has written to the cron log since this was deployed.

**Comment by mbabker** [comment]
Yep.  Busted.  The CLI's logger provider uses the `Joomla\Input\Input` service which doesn't read from CLI.  Changing the service to `Joomla\Input\Cli` gets into a recursion loop with the debugger object.  The CLI app service has a dependency to the `monolog` service, the `monolog` service (on CLI) has a dependency to the `debugger` service, and the `debugger` service has a dependency to the app service.

**Comment by elkuku** [comment]
:disappointed:

**Comment by mbabker** [comment]
Looks like it's working with a workaround to set the logger to the app services in the front controllers versus in the services and fixing a couple alias references.  Still need to deal with the circular references at some point.

**Comment by mbabker** [comment]
It's working.
