### ISSUE TITLE
Is the bot broken?

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#815]
#### Steps to reproduce the issue

see https://issues.joomla.org/tracker/joomla-cms/11041

#### Expected result

RTC label

#### Actual result

No RTC label

#### Additional comments

It worked here: https://github.com/joomla/joomla-cms/pull/11043#issuecomment-231156028

**Comment by mbabker** [comment]
Give it some time.  Considering the domain was having issues for the better part of the last 15 hours, I expect a lot of stuff to be out-of-sync for the moment.

**Comment by mbabker** [comment]
I'm having trouble replaying some of the comment webhooks to the server (most of the issues/PRs went OK).  I opened a ticket just to make sure the GitHub payloads aren't being caught in any filters.

**Comment by mbabker** [comment]
There was a mod_security rule catching some of the webhooks.  That's been whitelisted now.

**Comment by zero-24** [comment]
Thanks!
