### ISSUE TITLE
Bad responsive display of the projects table

### ISSUE THREAD

**Issue by Sandra97** [joomla/jissues#819]
#### Steps to reproduce the issue
Under 580px, there is an horizontal scrolling due to the last column.

#### Expected result
It's possible to have this display:
![after](https://cloud.githubusercontent.com/assets/4682328/16709360/af96f690-45dc-11e6-87e7-f47b2b846521.png)

But, as we have an inline-style for these `<td>`, it means removing it and replacing it by a custom class
with this declaration: 
`white-space: pre-line;`

#### Actual result
![before](https://cloud.githubusercontent.com/assets/4682328/16709370/066d8dee-45dd-11e6-9792-73cc0b8abf3c.png)

#### Additional comments
I'm not really good in responsive table, maybe someone has a better solution?

**Comment by mbabker** [comment]
Our responsiveness with tables is a wreck to say the least.  And I'm the wrong person to ask on how to cope with that; my fix on `framework.joomla.org` to deal with excessively wide tables was to hide some columns with BS3 `hidden-xs hidden-sm` classes.

Just playing with it quickly, removing the inline style seems to be enough.  No need for the additional CSS.

**Comment by Sandra97** [comment]
I don't think removing the nowrap will change the display on phones, but I can be wrong ;)

**Comment by mbabker** [comment]
Well, I pushed that change.  Let's see what happens?

**Comment by Sandra97** [comment]
Did I already mention you're a Super Hero? ;)

**Comment by Sandra97** [comment]
Padawan is closing the issue as @mbabker is my CSS Jedi Master
