### ISSUE TITLE
The "About Us" is still a TODO

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#820]
https://issues.joomla.org/page/about

Maybe we should address that TODO at some point this decade...

**Comment by b2z** [comment]
What we are expecting to see there? Thoughts?

**Comment by mbabker** [comment]
I honestly haven't a clue.  It just seems like there should be something other than a TODO statement on the page.

**Comment by Sandra97** [comment]
I can try to write a little something for this page during the week. Warning: it will be Franglish.

**Comment by elkuku** [comment]
@Sandra97 That'd be very cool :wink: 

I believe that people are creating `@todo` items because they are expecting other people to `@do` them :stuck_out_tongue_winking_eye:

**Comment by MATsxm** [comment]
Oooooh boy... :stuck_out_tongue_closed_eyes:
