### ISSUE TITLE
Link to the T9N

### ISSUE THREAD

**Issue by MATsxm** [joomla/jissues#824]
We need to find the best way to add a BTN or link to: https://crowdin.com/project/joomla-official-sites

a kind of "**Help us translate this site**"

Ideas?

**Comment by brianteeman** [comment]
In the footer next to the report an issue link?

**Comment by Sandra97** [comment]
Nice idea but as only 3 websites are available for translation, jdocs (dedicated system), issue tracker and /3, I don't know if adding it to the CDN is currently the right option? 
I can suggest this for the issue tracker only:
[1](https://cloud.githubusercontent.com/assets/4682328/16713453/3116a550-4676-11e6-8fc6-7f4027533fe6.png)

**Comment by MATsxm** [comment]
I have no specific opinion on this matter. 
At least we have here 3 options. 
The only thing I'm sure is: do NOT mention me this :earth_africa: menu  absurdity

**Comment by MATsxm** [comment]
I like @brianteeman's idea.
In this case, we would have a dedicated link per site **OR** a global one https://crowdin.com/projects/Joomla that would promote t9n also for Core & other ressources.

@Sandra97's translate btn (NOT in the etc. menu) would be maybe more efficient?

**Comment by mbabker** [comment]
The only places we've really mentioned translations in the past were in the documentation, i.e. [here](https://issues.joomla.org/documentation/view/?page=Dependencies&path=Development) and [here](https://issues.joomla.org/documentation/view/?page=Transifex&path=Internationalisation).  Those obviously need updates too.

As for where to put something site specific, I'd go for the menu bar.  Probably the `/etc` menu versus a top level button.  Or maybe add something at the bottom of the language selector.  I dunno, I just write PHP code, don't make me make design decisions!

**Comment by elkuku** [comment]
I'd go with the option to display something next to the language selector, maybe a friendly image?
![2016-07-10-144653_1366x768_scrot](https://cloud.githubusercontent.com/assets/33978/16715749/a773f544-46ae-11e6-95c3-e0d25174be08.png)
![2016-07-10-144650_1366x768_scrot](https://cloud.githubusercontent.com/assets/33978/16715748/a76e0b5c-46ae-11e6-9914-aafb985df5db.png)
And since stuff in the footer normally wouldn't cause headache with the design department we could add it here too... 
![2016-07-10-145255_1366x768_scrot](https://cloud.githubusercontent.com/assets/33978/16715750/a77aa808-46ae-11e6-9537-07fc1895ffd3.png)
Or maybe only one or even in a different place...?

**Comment by MATsxm** [comment]
Option 1 was my first idea but I have never been a fan of Icons instead of text. Even in this case, please let's use 2016 "Flat" monochrome instead of 90s' ones (one day, we will have to talk about the flags :stuck_out_tongue_closed_eyes: ) :wink: 
something more like?
![translationicon](https://cloud.githubusercontent.com/assets/1972717/16748514/74bc709c-4792-11e6-9f92-332a1d43e392.jpg)

I also like the footer idea with: "Translate this site" if it is correct  :uk:

**Comment by brianteeman** [comment]
I am really not a fan of an icon on the main menu navigation. That really
makes translating to be a major feature when in reality it's a request for
help that will only ever be relevant to a small number of people.
Especially now you already have so many languages available

**Comment by MATsxm** [comment]
Agree even if finding a way calling for translators is not an exclusive JIssue tracker "feature".
Some are coming on the Doc and are more confortable to translate Marketing stuff or others just want to help in core strings. My job is then to "catch" translators, then work with them to find a place they will stay and be active a max of time.

**Comment by mbabker** [comment]
At least for Joomla as a whole we could link to Crowdin in that often
forgotten globe menu on the top nav.  Doesn't do much for the few sites
which are language aware (3.x landing page, help screens by way of the
wiki, tracker) but it at least adds something.  Might be the worst starting
step ever but it is at least one.

**Comment by MATsxm** [comment]
the what?

**Comment by mbabker** [comment]
https://www.youtube.com/watch?v=afMsXWRWbOk

At least I'm trying here.  Never said the idea was good, but there's two things going on here:

1) Finding a way to encourage app/site specific translations
2) Trying to make project wide T9N more prominent

**Comment by elkuku** [comment]
@MATsxm The icon looks excellent. I'd put it in right away if we all agree. (If you could find time to do it, that would be cool - I dont think that its a good idea to let @elkuku touch anything design related - he prefers PHP code :wink: )
Te me it makes sense to put it right to the language selector, so the (small) group of people it is relevant to, will find it easily.

The footer link IMHO should be just an additional thing. Having it as the only option would mean next to nothing. (@brianteeman)

So we could have a project wide footer link (2) and, for sites that are "language aware", an icon next to the, already existent, language selector (1).

**Comment by brianteeman** [comment]
-1

On 12 July 2016 at 17:09, Nikolai Plath <notifications@github.com> wrote:

> @MATsxm <https://github.com/MATsxm> The icon looks excellent. I'd put it
> in right away if we all agree. (If you could find time to do it, that would
> be cool - I dont think that its a good idea to let @elkuku
> <https://github.com/elkuku> touch anything design related - he prefers
> PHP code 😉 )
> Te me it makes sense to put it right to the language selector, so the
> (small) group of people it is relevant to, will find it easily.
>
> The footer link IMHO should be just an additional thing. Having it as the
> only option would mean next to nothing. (@brianteeman
> <https://github.com/brianteeman>)
>
> So we could have a project wide footer link (2) and, for sites that are
> "language aware", an icon next to the, already existent, language selector
> (1).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/jissues/issues/824#issuecomment-232096677>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABPH8UYQxo2enY1xg1peCrD1u_Sw0JxPks5qU7xGgaJpZM4JI0g5>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by elkuku** [comment]
Talking about the footer, I just remembered #179 and the following discussion.
This here seems to take a similar direction so, I'll better go writing some code...

**Comment by MATsxm** [comment]
@elkuku Thanks for the precious help.
I have few things to do right now (I heard there's a 3.6 around :wink:  ) and also want to check few things about this topic, but I will come back on it ASAP.

Note that everything would be easier to fix if this joke of :earth_africa: was a real menu, being part of the main menu, like it should be...

**Comment by b2z** [comment]
> As for where to put something site specific, I'd go for the menu bar. Probably the /etc menu versus a top level button.
+1

I would vote for `/etc`

**Comment by MATsxm** [comment]
Still have few things to check but meanwhile and if needed, there's also this one that is more and more used as t9n icon.
http://fontawesome.io/icon/language/

**Comment by mbabker** [comment]
We reach an action point here?

**Comment by MATsxm** [comment]
before having a global i18n solution, I would :+1: for a footer link to the general: https://crowdin.com/projects/Joomla
"Help in translation" ?

**Comment by mbabker** [comment]
Moved to website repo.  At this point I think we need to go for a global solution over a site specific one (not to mention we already link to Crowdin in a couple places).

See https://github.com/joomla/joomla-websites/issues/615

**Comment by MATsxm** [comment]
At spare time, I will make a proposal for the footer menu.
