### ISSUE TITLE
Custom period - new strings for translation? 

### ISSUE THREAD

**Issue by Sandra97** [joomla/jissues#828]
#### Steps to reproduce the issue

If you go to this page for example: [https://issues.joomla.org/activity/user/joomla-cms?lang=en-GB](user tracker activity), and display it in French (or any other language), and then, display the chart with a custom period, you'll see that the months at the top of the chart are displayed in English.
Would it be possible to make them translatable?

![cms - graphique d activite des utilisateurs 2016-07-10 14-08-17](https://cloud.githubusercontent.com/assets/4682328/16715247/4c2ee87a-46a8-11e6-9237-25293317acf8.png)

**Comment by brianteeman** [comment]
Thanks to the USA I don't recommend using a pure numeric format.

**Comment by mbabker** [comment]
And without introducing the CMS' concept of translatable date/time formats all of the day-month-year notations aren't correct for us.

**Comment by mbabker** [comment]
Another possibility might be to dig deep into the PHP API and make use of the [intl extension](http://php.net/manual/en/book.intl.php)

**Comment by mbabker** [comment]
Just deployed https://github.com/joomla/jissues/commit/75d39f5316e16a5819a83b5431f8a44be5223984 which uses the PHP intl extension to format the dates, and translate them.  I've gone through a large chunk of the languages and things seem to be fine with that snippet, so if that's the case we could make the same change to other date labels in the charts and call this complete.

**Comment by elkuku** [comment]
I am, once again, surprised by the way you find simple solutions to problems that are quite complex...
I am, almost, even more surprised that we can use the intl extension on our live server environment.
Can our non *nix devs get that thing installed? @b2z?

Should become part of the language handling class :wink:

**Comment by mbabker** [comment]
Shouldn't be too complex to install.  Per [the documentation](http://php.net/manual/en/intl.installation.php) it's just passing a flag when you compile PHP, so if you're using an `*AMP` stack it would be dependent on how that was built.  And at least from what I've seen it's enabled on any decent hosting provider these days.  And if for whatever reason you CAN'T get the intl extension, there's [Symfony's intl component](https://github.com/symfony/intl) (sadly only supports English, but at least keeps your code from erroring out).

**Comment by b2z** [comment]
I did not have a problem with it - my WampServer installation has php-intl package ;)
