### ISSUE TITLE
Calendar for custom period: Display issue

### ISSUE THREAD

**Issue by Sandra97** [joomla/jissues#829]
#### Steps to reproduce the issue
Go to this page: [https://issues.joomla.org/activity/user/joomla-cms](user tracker activity). You can see that the display of the calendar's navigation is not ok (icons+text).

#### Expected result
If we're adding 
`.ui-widget-content .ui-icon {
  color: transparent;
}`
Only the icons will be displayed (maybe not the cleanest solution, but at least it works)
![after](https://cloud.githubusercontent.com/assets/4682328/16715798/42d8c72c-46b8-11e6-8ec8-fca167953d10.png)

#### Actual result
![before](https://cloud.githubusercontent.com/assets/4682328/16715801/4537349a-46b8-11e6-811e-2ae4b1a95d82.png)

And a question: is it normal to have 2 links but 2 icons displayed per link?

**Comment by mbabker** [comment]
I honestly want to rip out that calendar and use something else.  It's the jQuery UI Datepicker which was in use in the old CMS component and I updated all the CSS pieces to current builds when I pulled in all the code.  So honestly who knows how long it's been broken.

**Comment by Sandra97** [comment]
I fully approve "use something else".

**Comment by b2z** [comment]
Do we use jQuery UI somewhere else? If no then something like [bootstrap-datepicker](https://bootstrap-datepicker.readthedocs.io/en/stable/index.html)? Or [this one](http://trentrichardson.com/examples/Intimidatetime/#Examples).

**Comment by mbabker** [comment]
The jQuery UI stuff is solely for the charts.

**Comment by mbabker** [comment]
The calendar's replaced with the [bootstrap-datepicker](https://bootstrap-datepicker.readthedocs.io/en/stable/index.html) plugin now.  I didn't include the locale support right now though.

**Comment by mbabker** [comment]
Locale support is added now.
