### ISSUE TITLE
Database dump

### ISSUE THREAD

**Issue by elkuku** [joomla/jissues#839]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.
#### Steps to reproduce the issue

From time to time there are issues that are only reproducible (or easier to debug) locally if you have a copy of the live instance to test with.

So, since all the data present in the database is also public available, could we (@mbabker) set up a script that dumps the database periodically to a public available place?
#### Expected result

A 1:1 copy of the live instance to test with locally.
#### Actual result

Only data from GitHub is available for testing.
#### System information (as much as possible)

Local dev environment.
#### Additional comments

Happy coding `=;)`

**Comment by mbabker** [comment]
We need to do something with the `#__tracker_projects` table first as that has GitHub bot credentials in it.  Otherwise there's no issue with that at all IMO.  It'll be even better if we can take https://github.com/joomla/joomla-cms/pull/10991 when it's tested out and merge it to the Framework library then we can just use native Joomla API to do it.

Aside from that, a cron scripting a `mysqldump` run is more than enough.

**Comment by elkuku** [comment]
True haven't thought of those credentials... There is a [--ignore-table](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_ignore-table) option in mysqldump :wink: 

 joomla/joomla-cms#10991 looks interesting, I remember I did one attempt years ago, maybe mine was not good enough - I'd say let's use mysqldump *until* the PR is merged...

**Comment by elkuku** [comment]
btw, I was just playing with labels and milestones... no need to hurry :tongue:

**Comment by mbabker** [comment]
Sanitized file's at https://issues.joomla.org/uploads/issuesj_tracker_2016-07-16.txt (rename to .sql and you're good to go).  Just note it's a large file, start the download and take a drink break.

**Comment by brianteeman** [comment]
Zip it up and it will be TINY

**Comment by mbabker** [comment]
https://issues.joomla.org/uploads/db.zip but it's still larger than the CMS download.

**Comment by elkuku** [comment]
Both are 404ing :(

**Comment by mbabker** [comment]
Whoops.  My FTP client was still pointing to the old server, the ZIP file's uploaded to the new one and the TXT is uploading now.

**Comment by elkuku** [comment]
looks good, THANKS!
I hope it will be updated from time to time...
