### ISSUE TITLE
Proposal for the About us Page

### ISSUE THREAD

**Issue by Sandra97** [joomla/jissues#842]
Following the #820, here is a first draft for this page. 
Thanks to proofread, review, complete it...

#### What is it  for?
The Joomla! Issue Tracker is an official Joomla! website focused on reporting Joomla! bugs, testing patches, submitting patched and/or sumitting new features.  
Four projects are currently hosted and maintened here:
* Joomla! CMS
* J!Tracker
* Patch Tester
* Weblinks
We are always looking for more people to test patches, find and fix bugs, and help clarify issue reports on our bug tracker.  Do not hesitate to join us.

#### How is the Issue Tracker powered?
Joomla! Issue Tracker is powered thanks to the [Joomla! Framework] (https://framework.joomla.org/), a free and open source PHP framework which allows to build powerful web applications by writing web and command line applications in PHP, without the features and corresponding overhead found in the Joomla! Content Management System (CMS). 

#### Who is behind issues.joomla.org?

The Issue Tracker website is the result of the hard work of [Nikolai Plath] (https://github.com/elkuku), [Michael Babker] (https://github.com/mbabker) and [Dmitry Rekun] (https://github.com/b2z). In addition to these 3 majors contributors, 24 other members are contributing to this website. You can see the full list [here] (https://github.com/joomla/jissues/graphs/contributors).

#### Back on...
Until the end of 2014, Joomla! was using JoomlaCode.org as a resource for developers to build and manage Open Source software projects centred around Joomla. In 2012 (?), Joomla! Project started to use GitHub and, in parallel, it has been decided to build Joomla's own inbuilt bug tracker, using the Joomla! Framework. 
Issues.joomla.org has been launched in Sept 2012 and keeps on growing since then. 
What's new on issues.joomla.org?
The Joomla! Issue Tracker is constantly improved and is now multilingual. Translations are done via our translation tool Crowdin and merged (nearly) automatically here.
New projects will be also added to this website:
* ?

**Comment by MATsxm** [comment]
> We are always looking for more people to test patches, find and fix bugs, and help clarify issue reports on our bug tracker. Do not hesitate to join us.

should be great for having few links to the JDoc explaining the how to contribute.

> The Joomla! Issue Tracker is constantly improved and is now multilingual. Translations are done via our translation tool Crowdin and merged (nearly) automatically here.

a link "you can help to translate" to: https://crowdin.com/project/joomla-official-sites ?

**Comment by elkuku** [comment]
> How is the Issue Tracker powered?

You should definitely include GitHub here. (something like [this](https://github.com/joomla/jissues/blob/master/Documentation/Development/Dependencies.md#github)?)

> Who is behind issues.joomla.org?

Also mention `#4`[Zehan Zhao](https://github.com/allenzhao) who did some excellent work during [GSOC 2014](https://docs.joomla.org/GSOC_2014_Project_Ideas#Project:_JIssues_tracker) - ([archive](https://www.google-melange.com/archive/gsoc/2014/orgs/joomla/projects/allenzhao.html))

@allenzhao: I hope I wrote your name correctly?

Otherwise: Great job :wink:

**Comment by MATsxm** [comment]
I would also call it:
**About The Joomla! Issue Tracker™ Project**
(with the caps)

**Comment by elkuku** [comment]
> Four projects are currently hosted and maintened here:
...
* J!Tracker

You could mention here *somehow* that this is the same thing you are talking about...

**Comment by Sandra97** [comment]
Draft n°2.
Do not hesitate to comment, proofread my Franglish, suggest new ideas...
Thank you!

## About The Joomla! Issue Tracker™ Project
#### What is it for?
The Joomla! Issue Tracker is an official Joomla! website focused on reporting Joomla! bugs, testing patches, submitting patched and/or submitting new features.  
Four projects are currently hosted and maintained here:
* Joomla! CMS
* The present J!Tracker
* Patch Tester
* Weblinks

We are always looking for more people to [test patches] (https://docs.joomla.org/Testing_Joomla!_patches), find and fix bugs, and help clarify issue reports on our bug tracker. Do not hesitate to join us. If you want to learn more about the process, please read, among others, the JDocs article on [How to fill bugs and issues] (https://docs.joomla.org/Bug_Tracking_Process) . 


#### How is the Issue Tracker powered?
The Joomla! Issue Tracker is powered thanks to the [Joomla! Framework] (https://framework.joomla.org/), integrating with [GitHub] (https://github.com/joomla/jissues/blob/master/Documentation/Development/Dependencies.md#github) to replace the existing Joomlacode solution. 
The Joomla! Framework is a free and open source PHP framework which allows building powerful web applications by writing web and command line applications in PHP, without the features and corresponding overhead found in the Joomla! Content Management System (CMS). 

#### Who is behind issues.joomla.org?

The Issue Tracker website is the result of the hard work of [Dmitry Rekun] (https://github.com/b2z), [Nikolai Plath] (https://github.com/elkuku), [Michael Babker] (https://github.com/mbabker) and [Zehan Zhao] (https://github.com/allenzhao). In addition to these 4 major contributors, 23 other members are contributing to this website. You can see the full list [here] (https://github.com/joomla/jissues/graphs/contributors).

#### Back on...
Until the end of 2014, Joomla! was using JoomlaCode.org as a resource for developers to build and manage Open Source software projects centered around Joomla. In 2012, Joomla! Project started to use [GitHub] (https://github.com/joomla) and, in parallel, it has been decided to build Joomla's own inbuilt bug tracker, using the Joomla! Framework. 
Issues.joomla.org has been launched in September 2012 and keeps on growing since then. 

#### What's new on issues.joomla.org?
The Joomla! Issue Tracker is constantly improved and is now multilingual. Translations are done via our translation tool [Crowdin] (https://crowdin.com/project/joomla-official-sites) and merged (nearly) automatically here. If this website is not yet translated in your language, join us on [Crowdin]( https://crowdin.com/project/joomla-official-sites).  
New projects will be also added to this website. Stay tuned!

**Comment by b2z** [comment]
Looks good :+1:

**Comment by zero-24** [comment]
>contributing to this website. 

maybe "contributing to this application" as the Tracker is a application? (i know it is hair splitting)

**Comment by Sandra97** [comment]
@zero-24, done and also modified 'website' into 'application' at the beginning of the same paragraph.

**Comment by MATsxm** [comment]
@zero-24 
Nope, agree!
"hair splitting" would have been saying you should say:

> is a**N** application? 
:stuck_out_tongue_winking_eye:  :wink:

**Comment by zero-24** [comment]
Thanks @Sandra97 

>"hair splitting" would have been saying you should say:
>is aN application? 

hehe 1-0 for @MATsxm

**Comment by mbabker** [comment]
I've copied the text from here, cleaned up a little Franglish and tweaked the international section a bit and published it.

https://issues.joomla.org/page/about

Thanks to all for their feedback and ideas.
