### ISSUE TITLE
The Bot don't run for the CMS Issue #11353

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#850]
#### Steps to reproduce the issue

see: https://github.com/joomla/joomla-cms/pull/11353 & https://issues.joomla.org/tracker/joomla-cms/11353

#### Expected result

`PR-staging` & `RTC` label

#### Actual result

no label

#### Additional comments

It looks like that the bot don't run on that issue?

**Comment by brianteeman** [comment]
I noticed that there was no label (eg pr-staging) and thought that might be related so i have now added  that label

**Comment by zero-24** [comment]
same issue applys to: https://github.com/joomla/joomla-cms/pull/11359

**Comment by mbabker** [comment]
mod_security looks to be blocking the webhooks still.

**Comment by zero-24** [comment]
again mod_security on https://github.com/joomla/joomla-cms/pull/11497 ?

**Comment by zero-24** [comment]
Can we do something about the mod_security issue? https://github.com/joomla/joomla-cms/pull/11056

**Comment by brianteeman** [comment]
It happens more than the above as I didn't bother to report it if I could make the change

**Comment by mbabker** [comment]
We can't get mod_security completely turned off here.  I don't have time to dig into every webhook that's failing but that last one the issue has SQL statements included in at least one comment's payload and https://github.com/joomla/joomla-cms/pull/11359 could be deciphered as XSS by mod_security.

**Comment by zero-24** [comment]
Ah ok. That explains it so if that fails the maintainer need to add them manually. Thanks.

**Comment by mbabker** [comment]
It shouldn't need to be manually but remember there are webhook payloads that are going to trigger a mod_security rule with a default configuration.  So if there's going to be a whitelist around it then it has to be a very explicit configuration.

**Comment by elkuku** [comment]
Could we use the CLI script to sync those issues with "security problems"?

**Comment by mbabker** [comment]
Should be doing that already since it'd be bypassing mod_security.  It just doesn't give the instant gratification that the webhooks do, and I don't believe the CLI scripts are doing all the automated stuff that the webhooks do.

**Comment by elkuku** [comment]
Yeah the "event" stuff is still missing. There is a proposal in #692 ...
