### ISSUE TITLE
RTL Support in the UI

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#852]
Arabic was recently added to Crowdin for translating the issue tracker.  Assuming it or any other RTL language are worked on and we pull them in, we'll need to make sure the UI can properly display pages for these languages.

**Comment by mbabker** [comment]
Arabic's deployed now and the work I've been doing for the template to support RTL display (since the same person also translated the 3.x landing page) is added in now.  All in all things aren't too bad, just some minor quirks (as expected).

**Comment by MATsxm** [comment]
Thanks for the great work!

**Comment by bosyrih** [comment]
thanks for great job. 
I'm Hussein Al-bosyri Arabic JDocs Translations WG,JDocs Working Group.
the work is perfect but one thing if there is a code in the text like source code for any file, the text must be in LTR because All codes in English that's include documents in translation pages, for better visual.
thanks again for your work.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/852">issues.joomla.org/jtracker/852</a>.</sub>

**Comment by Sandra97** [comment]
Hi Hussein,
If I understand you well, you mean, for example, being able to keep Joomla! 3.6.2 with LTR display in a RTL page, right?

**Comment by bosyrih** [comment]
Hi Sandra
No that's another thing, I mean when there is a source code for any file or any example code, The code must be in LTR,.  because the code in English language always .

**Comment by brianteeman** [comment]
Span lang=en dir=RTL

**Comment by bosyrih** [comment]
if the example code like this
=========================
protected function parse($raw)
{
    $o = new stdClass;
    $o->text = $raw;

    $this->dispatcher->trigger('onContentPrepare', array('com_tracker.markdown', &$o, new JRegistry));

    echo $o->text;
}
==================

in any screen it must be LTR not RTL.

**Comment by bosyrih** [comment]
that's mean left align not right align to the code.

**Comment by brianteeman** [comment]
Sorry I of course meant to type LTR

**Comment by bosyrih** [comment]
yes brianteeman. 
 correct

**Comment by bosyrih** [comment]
there is another issue in https://issues.joomla.org/markdown => table =>Alignment. the second line in table.  colon on the right of the line for value field in LTR language but in RTL language the line is wrong.
| --------- | -----:| this is for RTl but visually it is appear like |:----- |--------- |

**Comment by bosyrih** [comment]
![english](https://cloud.githubusercontent.com/assets/20782472/18030515/81eed19c-6cb8-11e6-8d72-2e28a4edee5e.jpg)

**Comment by bosyrih** [comment]
![arabic](https://cloud.githubusercontent.com/assets/20782472/18030542/fc9fa9ca-6cb8-11e6-8d74-67fa214c5ffa.jpg)

**Comment by bosyrih** [comment]
you can see the first photo for English(LTR) the second for Arabic(RTL).
so in alignment in table the second line visually is wrong becuase the colon on the left of the separator for value field not for item field.

and in formatting section
the same thing in line to of the table.
and ! in appear in code function name but the output is right.

**Comment by mbabker** [comment]
Some of this is rendered directly through GitHub's Markdown parser, which
IIRC doesn't let you specify something like a direction.  So we'll need to
go through the resulting markup on examples page to make tweaks as needed
and add some CSS rules in places we won't be able to manipulate the markup
(unless we want to add our own handler to the mix too).

**Comment by bosyrih** [comment]
i think that's right it's for Markdown. but this will solve a lot of problemin RTL lang. can we put as issue for future.

**Comment by bosyrih** [comment]
this will solve problem e.g
the translator translate sentences right but in view it appear deference. when viewing translate from else person they will correct the translate in wrong way. even it's right in view or display on page but still not correct when we solve it we will need to correct again the translation.

**Comment by mbabker** [comment]
For now I've got the markdown examples all wrapped in div elements and forcing LTR display since they're all hardcoded English, this way they'll at least display correctly with the language they're written in even with a RTL language active.  Still have a bunch of tweaks to make in general but at least this is one less thing to take care of.

**Comment by bosyrih** [comment]
thanks all
For now the output is perfect.
