### ISSUE TITLE
[CSS] - small display issue for RTL template

### ISSUE THREAD

**Issue by MATsxm** [joomla/jissues#855]
Just a small issue on RTL languages

#### Steps to reproduce the issue
Select ar-AA Arabic language then go back to the dropdown language selector.

See the names of languages are centered

![screen shot 2016-08-03 at 11 04 38](https://issues.joomla.org/uploads/2/81b265c74d3ef952a9081043067b27b8.png)

@Sandra97 

Could you please take a look as our 2 crazy devs have for sure better things to do ?

**Comment by Sandra97** [comment]
If there is a rtl css file, just have add this: 
```
.ui.dropdown .menu {
  text-align: right;
} 
```
and
```
.ui.dropdown .menu > .item {
  padding: 5px 5px 5px 40px !important;
}
```

And tada: 
![joomla issue tracker - joomla cms 2016-08-03 12-31-28](https://cloud.githubusercontent.com/assets/4682328/17373446/39fd95c6-5976-11e6-9e98-0db52022eac9.png)

**Comment by Sandra97** [comment]
And for the LTR version, this would be better:
```
.ui.dropdown .menu > .item {
  padding: 5px 40px 5px 5px !important;
}
```

**Comment by MATsxm** [comment]
# WHAT THE HELL IS THIS: **!important;** ???

**Comment by mbabker** [comment]
CSS added.
