### ISSUE TITLE
Stats page on tablet

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#858]
The activity chart is breaking out of its container![screen shot 2016-08-04 at 13 26 47](https://issues.joomla.org/uploads/2/7011828325190b0d4b19d10058c4720f.png)

**Comment by mbabker** [comment]
Just lob comments on the charts design on https://github.com/joomla/jissues/issues/786

That's basically a "phase 2" catch all because that all needs a lot of cleanup to be "pretty".

**Comment by brianteeman** [comment]
Just spotted it so figured figured I should report it.

**Comment by mbabker** [comment]
Part of the problem with the current chart service is it really isn't maintained anymore and wasn't built with responsiveness in mind.  But it's a lot of work to move to a new service and get the AJAX functionality that we have on some of them wired up correctly.

The day `git clone mbabker` works or there are more than 24 hours in a day, maybe it'll get a proper update.

**Comment by brianteeman** [comment]
Fair enough.
