### ISSUE TITLE
Missing text on upload buttons

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#859]
On a tablet when you add a file you get two buttons. They either have no text or its the same colour as the background

![screen shot 2016-08-04 at 13 28 48](https://issues.joomla.org/uploads/2/3dd0ddc77bb8fcc9908420f2a5e10e61.png)

**Comment by brianteeman** [comment]
Found the  cause

vendor.min.css

@media (max-width: 767px)
.files .btn span, .files .toggle, .fileupload-buttonbar .toggle {
    display: none;
}

````

@media (max-width: 767px)
.files .btn span, .files .toggle, .fileupload-buttonbar .toggle {
    display: none;
}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/859">issues.joomla.org/jtracker/859</a>.</sub>

**Comment by mbabker** [comment]
I know for a while handheld devices weren't really supporting file uploads, are they able to now?  If so, should be easy to fix the CSS, but if not I'd say we should hide the upload stuff in full.

**Comment by brianteeman** [comment]
The upload works from android
