### ISSUE TITLE
Notices in logs

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#862]
> Undefined index: new_state in src/App/Tracker/Model/IssueModel.php on line 503
> Undefined index: old_state in src/App/Tracker/Model/IssueModel.php on line 504

**Comment by zero-24** [comment]
strange. They got defined here: https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Issue/Save.php#L111-112 and added to the src array here: https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Issue/Save.php#L210-L211

any more info about that or just this lines? Do we have more notices like that or just this one?

**Comment by mbabker** [comment]
Well, those two are repeated a bunch of times, but that's really it relating to this.  Also, the model isn't only used by that controller.

**Comment by zero-24** [comment]
see: https://github.com/joomla/jissues/pull/864

**Comment by elkuku** [comment]
Do you have the PHP error log disabled currently? There is no log atm...

**Comment by mbabker** [comment]
It might be a side effect of 9bbba2a4eff6f26c71aab26e5c3f368cb1b1f223

**Comment by mbabker** [comment]
Seems fixed.
