### ISSUE TITLE
Impossible to reach the issue.tracker website due to GitHub Reauthorization

### ISSUE THREAD

**Issue by MATsxm** [joomla/jissues#863]
#### Steps to reproduce the issue

Trying to reach issues.joomla.org
#### Expected result

Being able to see and play with the issue tracker site
#### Actual result

get the Github Authorize application
![1ff9c9ef51778cc247ad82381a485df7](https://cloud.githubusercontent.com/assets/1972717/17550707/4d3d7126-5ec4-11e6-8c9d-1a73dc991721.png)
then even if you proceed, blank page then the same page again (screenshot)

**Comment by MATsxm** [comment]
Note that 
http://www.issues.joomla.org/
nor
https://www.issues.joomla.org/
can be reached

**Comment by brianteeman** [comment]
I have been having this for about a week. But every time I open developer
tools to record a video of the traffic and redirects it stops ;(

**Comment by alikon** [comment]
i've experienced the same "discontinuous" behaviuor

**Comment by MATsxm** [comment]
on FF (previous was on my default Chrome),
* can see the IssueTracker
* trying to login then the "authorize application"
* then works as expected

**Comment by zero-24** [comment]
can you try to use a browser without logged into github?

**Comment by MATsxm** [comment]
@zero-24 
This is the process on my previous comment.

- I used FF without being logged, then I can reach the site.
- Then tried to login and reach the GH "authorize application"
- Once logged then, it works as expected.

On Chrome, I can't even reach the homepage then I can't logout.

**Comment by yvesh** [comment]
Same issue on Chrome and Opera.. Can't login

**Comment by mbabker** [comment]
We found a possible issue and fix for this.  It looks like the browser was caching the 303 on our remember me checks so after getting authenticated the browser was following the cached redirect and authenticating again.  We added a no-cache directive on that process so it should help matters immensely.

**Comment by MATsxm** [comment]
Great... now go for a Ouzo!

**Comment by mbabker** [comment]
Consider it done!

![img_1541](https://cloud.githubusercontent.com/assets/368545/18808807/e0a93ce6-8274-11e6-97b6-3550499efc04.JPG)

**Comment by mbabker** [comment]
Still an issue for anyone?

**Comment by MATsxm** [comment]
Oooops, I even forgot that there was a problem.
at this point, everything seems normal here - Thanks
