### ISSUE TITLE
Cant set #11579 rtc

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#866]
422 RuntimeException

Invalid response from GitHub

exception: exception 'JTracker\Github\Exception\GithubException' with message 'Validation Failed' in ROOT/src/JTracker/Github/GithubObject.php:49
Stack trace:
#0 ROOT/src/JTracker/Github/Package/Issues.php(155): JTracker\GitHub\GithubObject->processResponse(Object(Joomla\Http\Response))
#1 ROOT/src/App/Tracker/Controller/Issue/Save.php(357): JTracker\Github\Package\Issues->edit('joomla', 'joomla-cms', '11579', 'open', 'Move travis php...', 'Pull Request fo...', NULL, '16', Array)
#2 ROOT/src/App/Tracker/Controller/Issue/Save.php(152): App\Tracker\Controller\Issue\Save->updateGitHub('11579', Array, 'open', 'open', NULL, '16', Array)
#3 ROOT/src/JTracker/Application.php(174): App\Tracker\Controller\Issue\Save->execute()
#4 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#5 ROOT/www/index.php(103): Joomla\Application\AbstractWebApplication->execute()
#6 {main}

Next exception 'RuntimeException' with message 'Invalid response from GitHub' in ROOT/src/App/Tracker/Controller/Issue/Save.php:173
Stack trace:
#0 ROOT/src/JTracker/Application.php(174): App\Tracker\Controller\Issue\Save->execute()
#1 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#2 ROOT/www/index.php(103): Joomla\Application\AbstractWebApplication->execute()
#3 {main}

**Comment by mbabker** [comment]
We had ModSec issues on data coming in, how about on our own posts?

**Comment by brianteeman** [comment]
And now we can set it as fixed ;(

**Comment by brianteeman** [comment]
Same with #11275

422 RuntimeException

Invalid response from GitHub

exception: exception 'JTracker\Github\Exception\GithubException' with message 'Validation Failed' in ROOT/src/JTracker/Github/GithubObject.php:49
Stack trace:
#0 ROOT/src/JTracker/Github/Package/Issues.php(155): JTracker\GitHub\GithubObject->processResponse(Object(Joomla\Http\Response))
#1 ROOT/src/App/Tracker/Controller/Issue/Save.php(415): JTracker\Github\Package\Issues->edit('joomla', 'joomla-cms', 11275, 'open', 'Correct Alt tex...', 'Pull Request fo...', NULL, '16', Array)
#2 ROOT/src/App/Tracker/Controller/Issue/Save.php(152): App\Tracker\Controller\Issue\Save->updateGitHub('11275', Array, 'closed', 'open', NULL, '16', Array)
#3 ROOT/src/JTracker/Application.php(174): App\Tracker\Controller\Issue\Save->execute()
#4 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#5 ROOT/www/index.php(103): Joomla\Application\AbstractWebApplication->execute()
#6 {main}

Next exception 'RuntimeException' with message 'Invalid response from GitHub' in ROOT/src/App/Tracker/Controller/Issue/Save.php:173
Stack trace:
#0 ROOT/src/JTracker/Application.php(174): App\Tracker\Controller\Issue\Save->execute()
#1 ROOT/vendor/joomla/application/src/AbstractWebApplication.php(134): JTracker\Application->doExecute()
#2 ROOT/www/index.php(103): Joomla\Application\AbstractWebApplication->execute()
#3 {main}
