### ISSUE TITLE
Support Change Base Branch Feature

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#867]
I changed the base branch of https://issues.joomla.org/tracker/joomla-cms/10797 using [GitHub's new feature](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) and now the issue "timeline" is filled with a bunch of extra stuff.  Based on that blog post it doesn't seem like they've made any API changes yet for this feature, but we'll want/need to support this to be able to update our data correctly (i.e. removing commits).

**Comment by zero-24** [comment]
>and now the issue "timeline" is filled with a bunch of extra stuff.

what bruch of extra stuff do you mean? Or I'm the only one how don't see that?

This is what i can see: 
![image](https://cloud.githubusercontent.com/assets/2596554/17819894/70b90218-664a-11e6-84e5-954569cdebf3.png)

**Comment by mbabker** [comment]
Looks like they disappeared sometime between after my "rebased to 3.7" comment and when you screencapped that.  But for a bit there were a bunch of extra commits on the timeline.

**Comment by zero-24** [comment]
maybe the bot synced that away via the CLI?

**Comment by mbabker** [comment]
Seems no work necessary.
