### ISSUE TITLE
Low contrast on top menu

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/jissues#873]
#### Steps to reproduce the issue
Just go to the `/etc` menu and click on a sub-menu item, when a sub-menu item is active, the contrast between text and background is very low.

#### Expected result
Normal contrast level for active sub-menu items.

#### Actual result
![jissuelowcontrast](https://cloud.githubusercontent.com/assets/733133/18034859/18cfc8c0-6d48-11e6-9b12-a259f719fb3a.PNG)

**Comment by mbabker** [comment]
It's a core template issue, we aren't doing anything special with the styling there beyond using the active class.

**Comment by mbabker** [comment]
It's fixed in the template repo.

<img width="175" alt="screen shot 2016-08-28 at 11 07 24 am" src="https://cloud.githubusercontent.com/assets/368545/18034917/a7ea54d2-6d0f-11e6-9cb7-2109980b63fc.png">

**Comment by jeckodevelopment** [comment]
Thank you
