### ISSUE TITLE
0 UnexpectedValueException

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/jissues#876]
#### Steps to reproduce the issue
Trying to set as RTC this PR https://github.com/joomla/joomla-cms/pull/11899

#### Expected result
Issue saved

#### Actual result
Error at this URL: https://issues.joomla.org/tracker/joomla-cms/11899/edit-save 

![jissues](https://cloud.githubusercontent.com/assets/733133/18230540/01648aca-729f-11e6-952a-4d5505093efd.PNG)

**Comment by elkuku** [comment]
Ref: #834

**Comment by mbabker** [comment]
Let's keep this all in one issue.
