### ISSUE TITLE
Menu height

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/jissues#879]
The height of the top menu on jissue is higher than the other websites. 
Is there a reason?

![jmenu](https://cloud.githubusercontent.com/assets/733133/18257905/d2d0f77e-73cb-11e6-89b6-ef3142b6bce2.PNG)

`height: 36px`

![jissuemenu](https://cloud.githubusercontent.com/assets/733133/18257919/e66a873c-73cb-11e6-99ba-f631baac8792.PNG)

```
height: 42px
border: 1px
padding: 5px
```

**Comment by mbabker** [comment]
Probably that new item button.

**Comment by mbabker** [comment]
Actually, it's the user avatar.  Make it any smaller and it's useless.

**Comment by jeckodevelopment** [comment]
it's not a real issue. 
Let's keep it as it is!
