### ISSUE TITLE
Still getting issues opening 

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#889]
Still getting problems opening some of the issues

This is one of them
https://issues.joomla.org/tracker/joomla-cms/12078

**Comment by mbabker** [comment]
Direct linking to things is still randomly redirecting to the homepage but it's difficult to debug since opening the dev toolbar in Chrome makes it work right.  So without some kind of details what's causing that redirect I can't do anything else.

**Comment by brianteeman** [comment]
That's pretty much it. Note it was not just a direct link in an email but
also from the index.page

**Comment by mbabker** [comment]
I get that part but it's the technical side that needs figuring out (like when George pointed out the cached redirect to finally do something with the login loop).  I looked at the Apache log earlier and there was nothing useful there except for the 303.

**Comment by brianteeman** [comment]
Not had this problem for a long time now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/889">issues.joomla.org/tracker/jtracker/889</a>.</sub>
