### ISSUE TITLE
Missing sha

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#895]
I have seen this a few times today where you cant submit a test result because of a missing sha

Example Pr is https://issues.joomla.org/tracker/joomla-cms/12431

You can see instead of the SHA a link which gives a 500

**Comment by mbabker** [comment]
Intentionally added - https://github.com/joomla/jissues/commit/9ef60aa22475ce96d0bfcbc77a1fc6ac0479483e - #881

It's only a partial fix but it's addressing the issue of an invalid data record.

I think I might have found the path though that can produce this issue.  We've got two JavaScript methods submitting the test result; one includes the SHA and the other doesn't (this one is `JTracker.submitTestWithComment`), so I'm trying to trace my way back up that to get the missing data.

**Comment by mbabker** [comment]
If I've got the right code path figured out here, this is how you can test whether it's fixed or not.

First, ensure the browser cache is refreshed as the `jtracker.min.js` file is changed.

Set the test result to (un-)successful, add a comment using the form at the bottom of the page, and submit with that button.  It should add the comment and the test result.

With the test result option set to "Not tested", submitting the comment by that button at the bottom of the page should NOT trigger the script to submit a test result.

**Comment by brianteeman** [comment]
Thanks. Will test in the morning. Can't test from my phone.

**Comment by brianteeman** [comment]
seems ok if I tested correctly on 12431<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/895">issues.joomla.org/tracker/jtracker/895</a>.</sub>

**Comment by mbabker** [comment]
Looks like all is fine.
