### ISSUE TITLE
Language Change Label Incorrectly Removed

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#898]
See https://github.com/joomla/joomla-cms/pull/12516

When I opened the PR, it correctly added the label.  I pushed a couple of commits after I opened it then the label was removed.  The language change is still there.

**Comment by zero-24** [comment]
can you check if you get any issues in the log about that issue / PR?

**Comment by zero-24** [comment]
Can you try a commit e.g a sync commit (this should trigger the bot) ;)

**Comment by zero-24** [comment]
errors like this: https://github.com/joomla/jissues/issues/893 maybe

**Comment by mbabker** [comment]
There is nothing in the log, so it isn't erroring out.  It is most assuredly removing the label though.

**Comment by zero-24** [comment]
Can you see what type of trigger is made? Maybe the got an empty pulls event triggerd if you change a description / title?

**Comment by mbabker** [comment]
What do you mean "what type of trigger"?  We don't have different types; it's just responding to a pull request webhook.  What data is sent is the same regardless of the action taken, we just have different paths based on something being created and updated.

**Comment by mbabker** [comment]
There is nothing in the log, so it isn't erroring out.  It is most
assuredly removing the label though.

**Comment by zero-24** [comment]
The only thing i can think of that there was an empty hook where the files are empty.

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/12532

I changed the title and the tests label was removed.  Something is most assuredly not right here.  Webhook payload - https://gist.github.com/mbabker/9848db88ac34d38636cabb8a5b1d1cb9

**Comment by elkuku** [comment]
@zero24 if  you could check that the CLI script isn't the culpable here...
That would be REALLY cool ;)

Am 25.10.2016 20:46 schrieb "zero-24" <notifications@github.com>:

The only thing i can think of that there was an empty hook where the files
are empty.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/jissues/issues/898#issuecomment-256135979>, or mute
the thread

**Comment by zero-24** [comment]
hmm can we add here: https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php#L443 a check to be sure that we get the changed files from the pull request?


https://github.com/joomla/jissues/pull/902

**Comment by zero-24** [comment]
@elkuku i don't know how the CLI script is working but if i saw it correct it just runs the PR-<branch> label stuff?

**Comment by mbabker** [comment]
The method is already logging errors if it doesn't pull the list of files (nothing in the logs for those errors and the loggers are configured to catch messages with a minimum level of "warning").  So since the API calls aren't failing, that would indicate the API is returning an empty response.  And that's concerning if that indeed is the case.

**Comment by zero-24** [comment]
Is there a chance to get the content of the array so we can check?

**Comment by zero-24** [comment]
we have similiar issues here: https://issues.joomla.org/tracker/joomla-cms/12626 (the categories are not updated based on the last changes) for me it looks like a general problem.

IIRC we did not change much at that place in the past? So i guess that there is a problem with the github sync / webhook or there is a change? Can we see that there was a webhook on that pull request?

**Comment by mbabker** [comment]
Anyone with admin access on the GitHub repos can view the webhook config and activity.  https://github.com/joomla/joomla-cms/settings/hooks

**Comment by zero-24** [comment]
ok 404 for me but I'm also not sure if that would help me as i'm not sure that i understand this page.

**Comment by mbabker** [comment]
If you can see that section you can see all of the configured webhooks for the repo, each sent webhook payload, and the response from the remote server.

**Comment by mbabker** [comment]
Looks fixed by https://github.com/joomla/jissues/commit/f29998267c1762538daddad54969bd82caa39ff6
