### ISSUE TITLE
Implement a issue cron job for the `No Code Attached yet` label

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#903]
#### Steps to reproduce the issue

Some issues that are added via Github and not the tracker don't have the `No Code Attached yet` label
#### Expected result

The label should be added to all issues
#### Actual result

Some issues that are added via Github and not the tracker don't have that label
#### Additional comments

Maybe it is possible to implement a cronjob that can do this like we do it for branches?

https://github.com/joomla/jissues/blob/master/cli/Application/Command/Update/Pulls.php

so we get there a issues.php that contain similiar code?
I'm not sure if that is the right place?

**Comment by mbabker** [comment]
The source shouldn't matter for the issue.  Whether it's created on the tracker or GitHub it should be firing a webhook event and whatever label(s) are desired should be getting attached through that process if they aren't already.

Also that script isn't actually running.  It was just a utility file for some quick stuff.

**Comment by zero-24** [comment]
hmm than it looks like it is failing here: https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsIssuesListener.php#L38 ?

**Comment by mbabker** [comment]
Well, that'd be the code that's firing.  And per https://developer.github.com/v3/activity/events/types/#issuesevent the action is still valid.

**Comment by zero-24** [comment]
everything is fine now even if it was created on github. Thanks for fixing!
