### ISSUE TITLE
Missing SHA on testing

### ISSUE THREAD

**Issue by yvesh** [joomla/jissues#911]
#### Steps to reproduce the issue

At JWC 2016 we experienced that everyone testing 12824 at joomla core received an Missing SHA error when trying to mark it tested successful. 

Not sure if this is some left over from #895 

#### Expected result

Test should be submitted successful.

#### Actual result

Missing SHA error

**Comment by sanderpotjer** [comment]
Same for issue 12852

**Comment by mbabker** [comment]
Everything in the database looks fine for now.  Open new issues if this comes up again please.
