### ISSUE TITLE
Website admin panel doesn't work after trying to upload a new version of Joomla

### ISSUE THREAD

**Issue by JaneZhilina** [joomla/jissues#917]
#### Steps to reproduce the issue
Installed Joomla template
Started building the website atmdance.ru
Couldn't install the needed language to change the text in the website template
Saw, that Joomla needed an upgrade to Joomla 3.6
Clicked to upgrade
Waited for 5 minutes but there was no progress in downloading a new version of Joomla
Closed the window atmdance.ru/administrator

#### Expected result
Expected to enter the control panel atmdance.ru/administrator

#### Actual result
The control panel of Joomla doesn't open. URL atmdance.ru/administrator shows HTTP ERROR 500

#### System information (as much as possible)
Template S5
URL atmdance.ru
Browser Chrome![screen shot 2016-12-02 at 01 48 16](https://issues.joomla.org/uploads/2/93a0f169345df4c8b93738e8815d89ea.jpg)

**Comment by b2z** [comment]
Hello!

You are using wrong tracker. This tracker is for Joomla Issues Application, not for Joomla! CMS. The tracker for Joomla! CMS is http://issues.joomla.org/.

BTW your question is not CMS related. Please ask for help on https://forum.joomla.org/viewforum.php?f=26 or on Russian forums like http://joomlaforum.ru/.
