### ISSUE TITLE
Vagrant file link?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/jissues#918]
Hello,

The current box defined is:

https://dl.dropboxusercontent.com/s/nc9fdcl4mtgsve3/debian-7-64-elkuku-4.box

But this doesn't exist it's a 403. Do you happen to have the new url?

**Comment by b2z** [comment]
Hi!

Seems that we need to upload it somewhere and change the path in our vagrant file.
Another options is to create completely new box with all needed features.

**Comment by mbabker** [comment]
It'd probably be a good idea to build a new box.  IIRC that image was PHP 5.4 based and our dependencies are now declared against PHP 5.5 and the server running PHP 5.6.

**Comment by b2z** [comment]
@mbabker agree. Wait for PR from me ;)

**Comment by b2z** [comment]
You can test #919
