### ISSUE TITLE
Issue Status As Labels

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#924]
Continuation of https://github.com/joomla/jissues/issues/318

**Comment by b2z** [comment]
@mbabker thanks.

@nibra @demis-palma is it a must have feature?

**Comment by zero-24** [comment]
I think this would make it more complicated for syncing and is also dublicate information.

We can see on the RTC label in the past what issues we can have if syncing don't work or at least not correct :)

**Comment by b2z** [comment]
I am closing it for now. If the feature is a must have feel free to vote for reopen ;)
