### ISSUE TITLE
req: Inserting version for Htaccess.txt

### ISSUE THREAD

**Issue by mandville** [joomla/jissues#928]
Wish to request that on release of updates, (for clarification any update to any branch) the version it was released with is inserted as comment and possibly file size currently only the year is coded 
reasoning, ensures up to date version of htaccess is used. 
experince shows that some htaccess for j2.5 still being used on j3 sites

**Comment by zero-24** [comment]
Please move this issue to the CMS repo ;) and please explain in detail what you want as i'm not sure what you want to do or request.

**Comment by mbabker** [comment]
Just a guess, something in the .htaccess file indicating a version or last revision date.
