### ISSUE TITLE
Blocked User Support

### ISSUE THREAD

**Issue by mbabker** [joomla/jissues#929]
Given the project leadership has elected to make use of GitHub's blocked user feature which blocks users from interacting with a GitHub organization's repositories, we are now required to ensure we support this to ensure the block cannot be bypassed.

**Comment by elkuku** [comment]
It seems that information about blocked users is only available via the GitHub UI . I can't find any method in the API returning this information.
Should we maintain a separate list of blocked users? That feels quite ugly...

**Comment by mbabker** [comment]
Well, if it's not available then it's not available and we therefore have to rely on the GitHub API to do its thing.  Best thing I could suggest is block a user on a test repo, have that user try to open an issue or comment on something, and see what the API kicks back.

**Comment by zero-24** [comment]
@mbabker can you block me from the https://github.com/jtester/tests repo so we can test that?

**Comment by elkuku** [comment]
It looks like only organizations are able to block users..
@zero-24 I transferred that test repo to an organization and blocked you :tongue: Please try...

Not sure if the repo transfer leads to syncing errors since the url has changed - please report...

**Comment by zero-24** [comment]
![image](https://cloud.githubusercontent.com/assets/2596554/22176478/1535cb7e-e00c-11e6-9c28-a9244f321eee.png)

@elkuku can you try with your user that this  error is not realted to the change to the organization?

**Comment by elkuku** [comment]
OK I tried a different approach now.. please try again :wink:

**Comment by zero-24** [comment]
looks like that it works as i get now a 403 error:
![image](https://cloud.githubusercontent.com/assets/2596554/22176656/ad630382-e00f-11e6-8445-6b5bb3a6093e.png)

**Comment by elkuku** [comment]
Well I think thats "it". So basically we "support" the blocked user feature...

**Comment by mbabker** [comment]
Works for me.

**Comment by zero-24** [comment]
@elkuku can you unblock me than :smile:

**Comment by elkuku** [comment]
@zero-24 you have been unblocked :wink:

**Comment by zero-24** [comment]
Thanks :smile:
