### ISSUE TITLE
Error SEO Settings

### ISSUE THREAD

**Issue by nvthuong11** [joomla/jissues#932]
Hi,
I installed the new version of Joomla 3.6.5. When I turned on all the established SEO. Front-end when I click on a category or article, it is an error. Please see pictures:
https://postimg.org/image/3uarl27gz/
https://s24.postimg.org/kmabmd8z7/image.png

**Comment by zero-24** [comment]
This sounds to me like a configuration / site error. Please contact our forum about that kind of questions. You can find ot here: https://forum.joomla.org

Just a quick idea did you enable the core htaccess on your site?

Thanks for understanding.

**Comment by nvthuong11** [comment]
Hi,

Yes. I'm sorry.

Happy new year

Thank you.
