### ISSUE TITLE
Pull Request is not a pull request and there are no ways to push the test buttons #13650

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#936]
#### Steps to reproduce the issue

https://issues.joomla.org/tracker/joomla-cms/13650
https://github.com/joomla/joomla-cms/pull/13650

#### Expected result

There are buttons to test and alter the tests

#### Actual result

There are no buttons to test and alter the tests

![problem](https://cloud.githubusercontent.com/assets/2596554/22153299/0eb200fa-df27-11e6-90b2-837944bb21c8.PNG)
![works](https://cloud.githubusercontent.com/assets/2596554/22153301/133b0126-df27-11e6-8017-37d57000524f.PNG)

**Comment by mbabker** [comment]
Fixed.

**Comment by zero-24** [comment]
Thanks :+1:
