### ISSUE TITLE
Administrator, Menu, Modules Issue and Joomla Update

### ISSUE THREAD

**Issue by Fianza** [joomla/jissues#938]
I think that I'm having trouble with the latest Joomla version, 3.6.5. The administrator has some faults with the Side Menu and when creating modules. JSN Position chooser and Show Tilte buttom do not work. They completely changed the design of inserting modules and I can not also insert as before a single article. It is very frustrating, I will appreciate any help.

![screen shot 2017-01-24 at 15 35 01](https://issues.joomla.org/uploads/2/d32cd29fb57e28919d3e302f49db0292.jpg)

**Comment by mbabker** [comment]
Please file this issue on the [CMS repository](https://github.com/joomla/joomla-cms/issues), this repo is for issues regarding the issue tracker itself.  Thanks.
