### ISSUE TITLE
PR not visible on issues.joomla.org

### ISSUE THREAD

**Issue by csthomas** [joomla/jissues#942]
#### Steps to reproduce the issue
I have created a PR for joomla https://github.com/joomla/joomla-cms/pull/13895
but there is no issue at  https://issues.joomla.org/tracker/joomla-cms/13895
```
404 RuntimeException

Invalid Issue
```

#### Expected result

Issue should appears at joomla tracker.

#### Actual result

Issue does not exists at joomla tracker.

#### Additional comments
`joomla-cms-bot` did not start on github and do not add any label.

**Comment by mbabker** [comment]
Added.

**Comment by csthomas** [comment]
Thank you
