### ISSUE TITLE
error message abou stdclass to int on saving a issue

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#949]
#### Steps to reproduce the issue

Save an pr on issues.joomla.org

#### Expected result

No error message

#### Actual result
![wp_ss_20170219_0001](https://cloud.githubusercontent.com/assets/2596554/23102160/3530768c-f6a4-11e6-9277-e9418b455a30.png)

#### System information (as much as possible)

https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Issue/Save.php#L366

**Comment by b2z** [comment]
Is it happening on specific issue?

**Comment by zero-24** [comment]
No on every issue i edit on issues.joomla.org

**Comment by b2z** [comment]
Hmm... I am trying to edit & save issues and do not have any errors. What do you change on edit?
