### ISSUE TITLE
No pagination on menu type "view all categories"

### ISSUE THREAD

**Issue by sjkelley** [joomla/jissues#951]
In Joomla 3.6.5 there is no category pagination in the "View All Categories" menu item type.  "Pagination" is set to "Show" and "# of Articles" is set in the menu item parameters.  

Article pagination works correctly, but the list of categories is not paginated.

Pagination code needs to be added to /components/com_content/views/categories/tmpl/default_items.php

**Comment by zero-24** [comment]
@sjkelley please post this issue / PR to https://github.com/joomla/joomla-cms 

this is the place for issues with the custom issue tracker on top of github. https://issues.joomla.org ;)

**Comment by sjkelley** [comment]
Oops, sorry!
