### ISSUE TITLE
"PR-staging" removed after set "Easy Test" on "Yes"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/jissues#962]
#### Steps to reproduce the issue
Set "Easy Test" on "Yes" at #15464 on Issue Tracker, at Github "PR-staging" is removed

**Comment by zero-24** [comment]
@mbabker could it be that the pull update event is triggerd without files / branch etc. data?

**Comment by mbabker** [comment]
Even if that happens the code shouldn't be removing already set labels arbitrarily.  So there's a bug in that workflow if labels are getting removed because there's no data.

**Comment by zero-24** [comment]
I'm going to check that. Thanks!

**Comment by zero-24** [comment]
https://github.com/joomla/jissues/pull/963 Would be the PR for that. Let's try if that fixes the issue :)

**Comment by b2z** [comment]
#963 fixed it?

**Comment by franz-wohlkoenig** [comment]
Same behaviour, test on [#17896](https://github.com/joomla/joomla-cms/pull/17896): Set "Easy Test" on "Yes" removes Label "PR-staging".

**Comment by franz-wohlkoenig** [comment]
@b2z can this Issue become also a "Bug"-Label like ?

**Comment by b2z** [comment]
@franz-wohlkoenig  sure :)

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report #947
