### ISSUE TITLE
Travis fails on PHP nightly only because of missing hyphen 

### ISSUE THREAD

**Issue by zero-24** [joomla/jissues#964]
#### Steps to reproduce the issue

https://travis-ci.org/joomla/jissues/jobs/225123398

#### Expected result

Green Travis

#### Actual result

Unhappy travis

#### Additional comments

```
FILE: ...ravis/build/joomla/jissues/cli/Application/Command/Export/Langfiles.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AND 1 WARNING(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 5 | WARNING | Invalid year span "2012" found; consider "-2012" instead
 5 | ERROR   | A hyphen must be used between the earliest and latest year
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
```

But they are fine?
https://github.com/joomla/jissues/blob/master/cli/Application/Command/Export/Langfiles.php#L5

Or do they request us to use?

```
 @copyright  Copyright (C) 2012-2014 Open Source Matters, Inc. All rights reserved.
```

**Comment by mbabker** [comment]
I would consider this an upstream issue between PHP_CodeSniffer or PHP core itself.  Either PHP_CodeSniffer 1.x won't work with PHP 7.2 or there's been a B/C breaking change in 7.2 that affects PHP_CodeSniffer.

**Comment by b2z** [comment]
That's funny issue :)

**Comment by zero-24** [comment]
Ok closing than as upstream issue. Thanks!
