### ISSUE TITLE
Test and vote on closed items

### ISSUE THREAD

**Issue by elkuku** [joomla/jissues#965]
Currently you can submit test results and vote on closed items.
Not sure if this is a bug or a desired feature :wink:

**Comment by alikon** [comment]
assuming that a reply to a closed issue would normally add no value...
sometimes 
it can be considered usefull because as an example cause of it  you need to re-open  an issue for a valid whatever reason 
... 
not so strange workflow for me

**Comment by rdeutz** [comment]
Most likely it will not make a change, might better to guide people to open a new issue

**Comment by elkuku** [comment]
not an issue
