### ISSUE TITLE
J3.7 tags and custom fields and version control

### ISSUE THREAD

**Issue by pulsarinformatique** [joomla/jissues#966]
Hi
Seems that any change on the tags or custom fields value in an article doesn't generate a new version of the article. 

#### Steps to reproduce the issue

Create a custom field (any type) and then create an article with this custom field. save it. now change the value of the custom field and check if a new version of the article has been generated (with the VERSION button).

#### Expected result
When you change the tags or the values of a custom field inside an article we may expect a new version to be generated

#### Actual result

no new version is generated. the control version only applies to the #__content table

thanks

cyril

**Comment by franz-wohlkoenig** [comment]
@pulsarinformatique can you please open the Issue at https://github.com/joomla/joomla-cms and close this Issue as this repository is about Issue tracking application.
