### ISSUE TITLE
Only for a few users : Application Instantiation Error: Could not connect to MySQL

### ISSUE THREAD

**Issue by WebAtelier47** [joomla/jissues#968]
#### Steps to reproduce the issue
Access to website, frontend or backend

#### Expected result
The website

#### Actual result
Only for a few users Application Instantiation Error: Could not connect to MySQL.

#### System information (as much as possible)
Joomla 3.7.1
Host OVH
PHP 7.0.15
MYSQL 5.5.55-0+deb7u1-log

#### Additional comments
The Problem was resolved by clearing the user's browser cache

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns " Issue tracking application extending GitHub's issues and pull requests for the Joomla! project" and close this Issue, thanks.

**Comment by WebAtelier47** [comment]
Sorry, it is no possible it was a bug ?

**Comment by mbabker** [comment]
A "Could not connect to MySQL" error indicates either a misconfigured site or the remote MySQL server being unavailable.  Users having this response in their browser cache points to the way you have your server caching configured (`.htaccess` possibly) as Joomla core doesn't really cache responses or send browser caching headers, especially through its error page handler.

**Comment by franz-wohlkoenig** [comment]
If you want to report a Bug please use https://github.com/joomla/joomla-cms not this Repository, whoich belongs to Issue Tracker.

**Comment by WebAtelier47** [comment]
Oups sorry

**Comment by franz-wohlkoenig** [comment]
No Problem, please feel free to report Issues at given Url.

**Comment by WebAtelier47** [comment]
OK i am trying this...
