### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#969]
Spotted this a few times now where images are missing and the link to the image says

```
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>github-cloud.s3-website-us-east-1.amazonaws.com</BucketName>
```

really not sure if this is a github issue or a jissues issue so thought best to be safe and report it

**Comment by zero-24** [comment]
IIRC images you upload to jissues are stored on our servers and images you upload to github are on the Github / amazonaws servers.

**Comment by zero-24** [comment]
Did you found the reason?

**Comment by brianteeman** [comment]
no but as the container is a github one there isnt much we can do here

**Comment by zero-24** [comment]
ok :)
