### ISSUE TITLE
Mod_articles_latest gets wrong module id

### ISSUE THREAD

**Issue by TheWhykiki** [joomla/jissues#972]
If you use more than one mod_articles_category Module the resulting $module->id is in template-file or module chromes always the last used mpodule of this type. This causes wrong headlines and wring module appearance

**Comment by zero-24** [comment]
@TheWhykiki this is the tracker for issues with our custom issue tracker. Please post issues with the CMS itself here: https://github.com/joomla/joomla-cms/issues/new
