### ISSUE TITLE
Problem with position buttom in modules

### ISSUE THREAD

**Issue by Fianza** [joomla/jissues#978]
Hi!

I'm having problems with the JSN Position chooser in modules. When I press the buttom it appears blank I can not select any position.  I will appreciate any help you can give me.

![position-chooser](https://user-images.githubusercontent.com/25308443/27966116-10a32f4c-630c-11e7-925a-3abe54299b09.png)

**Comment by franz-wohlkoenig** [comment]
Please use JSN-Forum as this Repository is for "Issue tracking application extending GitHub's issues and pull requests for the Joomla! project."
