### ISSUE TITLE
Long menu on admin UX wont scroll or display

### ISSUE THREAD

**Issue by misrajitas** [joomla/jissues#984]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.

#### Steps to reproduce the issue

I have more than 30 menus, (is a big multiple site) when in the administrator interface, I am not able to scroll down to see all menus, and I have to zoom out to view and administrate the menus

#### Expected result

When in the lower menu, is should scroll

#### Actual result

I can not see past the 17th menu
![screen shot 2017-08-04 at 2 32 00 pm](https://user-images.githubusercontent.com/3765659/28985617-394b86ac-7918-11e7-93d3-1c3e428e2d28.png)

**Comment by mbabker** [comment]
1) As noted, this repository is for issues with our issue tracker, not Joomla itself.
2) The current Joomla version supports a scrollbar for the menus as shown in the attached screenshot.
3) Just on a quick glance of your site, it seems you have customized the backend template a bit.  So your customizations may be missing support for this feature.  See https://github.com/joomla/joomla-cms/pull/9375 and other referenced items for the relevant changes.

![screen shot 2017-08-04 at 3 26 14 pm](https://user-images.githubusercontent.com/368545/28985707-6bb57312-7929-11e7-9bbf-926c66944d1f.png)
