### ISSUE TITLE
GiHub profile sync not working

### ISSUE THREAD

**Issue by n9iels** [joomla/jissues#988]
When I try to sync my GitHub profile (I have a new picture) nothing seems to happen. There is a success message, but my old picture keeps visible instead of the new one.

**Comment by mbabker** [comment]
Made a small tweak in the function refreshing avatars, should work better now.

**Comment by b2z** [comment]
@n9iels is it ok now?

**Comment by n9iels** [comment]
woops totally forgot this... My picture is changed, so looks like it works! :smile:

**Comment by zero-24** [comment]
test
