### ISSUE TITLE
TinyMCE plugin's setting "Valid elements" crash formatting in editor

### ISSUE THREAD

**Issue by xakepok** [joomla/jissues#989]
#### Steps to reproduce the issue

Go "Administrator area" -> plugins -> TinyMCE plugin, and insert any tag (or any text) in field "Valid elements".
Go to editor in any component's settings, where exist Tiny MCE editor.
Edit text in editor and save (or click Initial code button).

#### Expected result

Normal formatting code.

#### Actual result

Formatting in editor is crash.

#### System information (as much as possible)

Joomla 3.7.5.

#### Additional comments

If field "Valid elements" in plugin's settings is empty, plugin works normal.

**Comment by franz-wohlkoenig** [comment]
Please report issue at https://github.com/joomla/joomla-cms as this Repository is about Issue tracking application.

**Comment by xakepok** [comment]
Ok
