### ISSUE TITLE
pr present on github but not on issue tracker

### ISSUE THREAD

**Issue by alikon** [joomla/jissues#991]
Not sure if should be considered like an issue cause  i've messed up https://github.com/joomla/joomla-cms/pull/18166 

#### Steps to reproduce the issue

- submit a pr 
- close it 
- delete the branch
- restore the branch
- change something
- reopen the pr

#### Expected result
the pr is searchable and present in the issue tracker

#### Actual result
the pr is not searchable and a wrong  response is returned
![screenshot from 2017-09-29 19-06-03](https://user-images.githubusercontent.com/181681/31027209-bbf2fdd0-a549-11e7-8767-bfaa8c70f8a1.png)

cause https://github.com/joomla/joomla-cms/pull/18166 is not present in the tracker items list
![screenshot from 2017-09-29 19-09-23](https://user-images.githubusercontent.com/181681/31027287-f760292e-a549-11e7-8298-4801a623a34a.png)

**Comment by mbabker** [comment]
Fixed for now

**Comment by alikon** [comment]
thanks
