### ISSUE TITLE
Joomla Update: Nightly Builds not working

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/jissues#993]
#### Steps to reproduce the issue
Using custom URL `https://update.joomla.org/core/nightlies/next_patch_list.xml` to check for Nightly Builds per "Check for Updates".

Since a few Days i get " No updates available." and " You already have the latest Joomla version, 3.8.2-dev." but at https://developer.joomla.org/nightly-builds.html Updates are there.

**Comment by zero-24** [comment]
please see: https://github.com/joomla/update.joomla.org/pull/72 this repor is about the issue tracker :P website issues goes to https://github.com/joomla/joomla-websites

**Comment by franz-wohlkoenig** [comment]
thanks for solving Issue @zero-24 – wasn't sure where to post. So its expected that Update works now (get no update now as before)?

**Comment by zero-24** [comment]
Michael need to push the changes first.

**Comment by franz-wohlkoenig** [comment]
@zero-24 its expected that Behaviour is still the same? Shpuld i report it at https://github.com/joomla/joomla-websites?

**Comment by franz-wohlkoenig** [comment]
all fine, Upate works now. Thanks all.
