### ISSUE TITLE
First PR message

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#995]
Github will now label a PR if it is the submitters first PR

I dont know if it is exposed in the API but it would be great if we could have an automatic reply - thanking them for their first PR etc

**Comment by zero-24** [comment]
@brianteeman can you suggest a text here too?

**Comment by brianteeman** [comment]
the text is the easy part

**Comment by zero-24** [comment]
The code too 😄 But to suggest a PR i would like to have the text ;)

**Comment by zero-24** [comment]
see: #997 i have just left the text open

**Comment by brianteeman** [comment]
ok i will suggest some text later after dinner

**Comment by zero-24** [comment]
Thanks 👍
