### ISSUE TITLE
Lock closed items

### ISSUE THREAD

**Issue by brianteeman** [joomla/jissues#996]
We did discuss this in the past but didnt really do anything about it

To prevent people commenting on closed issues (which only a few people even see) we should either automatically lock them after a period of time - perhaps 3 weeks

OR we have an autoreply when people post on closed issues - this will save some of us quite a bit of time

**Comment by franz-wohlkoenig** [comment]
Prefer autoreply similar we wrote now like that comment on closed Issues didn't get Notice and better to open a new Issue.

**Comment by zero-24** [comment]
@brianteeman can you suggest a text?

**Comment by brianteeman** [comment]
the text is the easy part

**Comment by zero-24** [comment]
hmm the code part is simple here too but I'm not sure as that could spam us on issues where we first close and than send a comment that we closed and on PRs where we merge and there is a "Thanks" like comment.

**Comment by brianteeman** [comment]
I've been looking at the stalebot app and it looks really useful (when configured correctly)

A lot of time is wasted chasing up old issues and this could and should be automated. Plus we have issues that are very old and clearly not going to be addressed.

https://probot.github.io/apps/stale/

**Comment by zero-24** [comment]
hmm what about a cronjob that is doing this with a few lines of code? I'm not sure if we should give all that nice services write access to our repos?

**Comment by brianteeman** [comment]
stalebot does a lot more than just closing - its used by github themselves so i wouldnt worry about anything


PS Happy Birthday

**Comment by zero-24** [comment]
> stalebot does a lot more than just closing - its used by github themselves so i wouldnt worry about anything

hmm just want to bring that up as i don't want to much services access to our repos in general but fortunately I'm not in power ;)

> PS Happy Birthday

Thanks 😃

**Comment by mbabker** [comment]
And we don't have the manpower to write and maintain all the tools ourselves, regardless of how many people/teams try to do so.  It's all about balance 😉

**Comment by brianteeman** [comment]
and reinventing the wheel goes against everything opensource is about

**Comment by zero-24** [comment]
Now it sounds like I'm against opensource. ;) That was **not** my intention. If the person in power here decide to use that 3rd party service and assign push access great.

**Comment by mbabker** [comment]
Those of us who know you know you're someone who would prefer to keep everything in-house with minimal third party access (if any at all).  I'm sure a lot of us feel the same way at different times with different resources, but at the same time we have to balance that against our capabilities and resources.  Sometimes, you just have to use someone else's tools because you can't run all the things yourself (it's why we host on GitHub instead of running our own GitHub Enterprise or a self hosted GitLab system, we all remember how well self hosting our SVN and issue tracker went for us).
