### ISSUE TITLE
Tag creation time problem of joomla3.7.4

### ISSUE THREAD

**Issue by ivyangyong** [joomla/jissues#998]
Joomla3.7.4 background Joomla\administrator\components\com_tags, set the position in the system settings - > Global Configuration - > server, set the current time zone (Shanghai), then create new tag, preservation after the completion of the created_time label than the current system time ahead of 8 hours, than in the database created_time 16 hours in advance.

**Comment by franz-wohlkoenig** [comment]
Please write in english as this is an english-spoken Repository.

**Comment by ivyangyong** [comment]
Ok,I'm sorry!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtracker/998">issues.joomla.org/tracker/jtracker/998</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository is for the Issue tracking application. For this Reason please close this Issue.
